### ISSUE TITLE
Is it necessary to headerUnlink() headers?

### ISSUE THREAD

**Issue by dcantrell** [rpm-software-management/rpm#1072]
I use rpmReadPackageFile() to get RPM headers then use headerGetString() and headerIsSource() during the lifetime of the program.  At the end, I call headerFree() on the RPM headers I read in at the beginning but these are not freed because the reference counts are at 67.  I see headerUnlink() is not available directly, so I don't know what I'm doing incorrectly.  The program itself functions but it's leaking memory at the end.

Do headerGetString() and headerIsSource() increment the reference count?  Looking at the lib/ source, I don't see that obviously standing out.  I only see headerLink() doing and it's not called from many places.

I've modified my local librpm and have it dumping the Header nrefs count.  When I call rpmReadPackageFile(), that reference count becomes 1.  At the end of the program when I call headerFree(), it's 67.  What is the correct way to read a header and not have the reference count grow?  Thanks.

**Comment by pmatilai** [comment]
That sounds really, really bizarre and wrong.

headerUnlink() is an internal-only leftover, you always simply call headerFree() when you're done with it, and that takes care of the refcount internally. There aren't that many cases where you'd call headerLink() either, typically its used to hang on to a header retrieved from rpmdbNextIterator() (because you only get a weak ref there). 

And like you noticed, rpm internals don't generally call headerLink() either, headerGetString() and the like certainly do not. The main (and probably only) candidate for wildly increasing reference count that I can think of is calling rpmteHeader() without calling headerFree() when done.

What version of rpm are we talking about here, and is the source to your program somewhere that I could see?

**Comment by dcantrell** [comment]
It was definitely weird and confusing and after staring at it for a while, I decided to ask.  However, running regular rpm operations with my modified librpm that displays the reference count showed everything behaving normally.  The bug has to be in my code.

Looked at it again just now and found it.  It was a separate function for a separate part of the code that was using headerLink().  Thought I had gotten rid of all those.  Leak fixed, everything working normally now.

For reference, my project is rpminspect:  https://github.com/rpminspect/rpminspect
