### ISSUE TITLE
RFE: Fix license permissions

### ISSUE THREAD

**Issue by nim-nim** [rpm-software-management/rpm#1090]
Some upstreams are very new to git and are committing license file with executable permissions (probably from windows or OSX)

rpmlint rightly points out something is suspicious

Since I can’t imagine a case where we would want to package an executable license file, please attr license files by default to 0644, so packagers do not need to sprinkle their %preps with manual chmods

**Comment by Conan-Kudo** [comment]
This could be done as a buildroot policy (brp) script, couldn't it?

**Comment by pmatilai** [comment]
So... a general purpose `brp-setperms [options] <path> [...]` script, anyone? :innocent: 
That could then be used for adding brp-macros for tweaking license and doc (#567) permissions, plus who knows what else.

**Comment by ffesti** [comment]
What about an premissions macro in fileattr files to set the permission for a give file type?

**Comment by pmatilai** [comment]
Extending fileattr to cases other than dependency generator would have various uses, but it's also quite non-trivial. As it currently is, all that fileattr stuff is buried inside a rpmfcGenerateDepends() call that occurs after file data has been inserted to packages (otherwise it wouldn't know what files to process), the machinery would have to be lifted out and extended in various ways to accommodate uses like this. It'd also cause a possible chicken-egg situation as permissions can affect the fileattr classification.

**Comment by pmatilai** [comment]
Should be done as a part of #567.

**Comment by pmatilai** [comment]
This should be done together with #567.

**Comment by pmatilai** [comment]
Actually, makes more sense to just merge this into #567.
