### ISSUE TITLE
RFE: add database change notification API

### ISSUE THREAD

**Issue by pmatilai** [rpm-software-management/rpm#1124]
Traditionally rpm-related daemons have been watching for changes in /var/lib/rpm/Packages file, but hardcoded paths were always ugly and no longer feasible at all because of multiple supported backends with different file names and semantics over them.

We recently added rpmdbCookie() API for checking if the database has changed, and rpmdbStat() and rpmdbFStat() go to the same direction as well, but none of these serve the daemon case particularly well as it should not be necessary to poll.

I know sqlite supports notification hooks, and IIRC BDB does too. I think ndb doesn't keep track of who has the db open and no idea how easy/hard implementing that would be. @mlschroe, thoughts ?

**Comment by mlschroe** [comment]
I don't think sqlite notification hooks work for different processes.

**Comment by pmatilai** [comment]
Hmm, so it seems. Probably memories getting mixed up with BDB which I do think supports multi-process notification (which of course is all part of the reason its such a weird beeast). Since we can't really expect help from the database itself here, so the options are limited.

**Comment by mlschroe** [comment]
A linux specific way would be to offer some functions around inotify().

We can also try something more generic: We could create a named pipe in /var/lib/rpm. At the start of the transaction we open the pipe O_WRONLY, at the end we simply close the fd.

Some other process that wants to be notified can open the named pipe with O_RDONLY|O_NONBLOCK and then use poll/select on the fd. (Reading will not block for some reason if there is no writer.) When rpm opens the named pipe for writing nothing will happen, but closing it will make all the select/poll users get a read event (because of the EOF).

**Comment by pmatilai** [comment]
Yeah, something built around a named pipe puts actually rpm in control of the thing, and also has the benefit of being generic.

**Comment by cgwalters** [comment]
Just to echo https://github.com/rpm-software-management/rpm/pull/1255#issuecomment-645103007
here - inotify is used today for e.g. `/usr/share/applications` - when you e.g. `zypper/apt/yum/whatever install firefox` that's how the desktops pick up the change.

As far as portability, there are already a *lot* of cross platform wrappers for inotify.  For example, GLib has one.

So I think the simple solution is:

- Add an API to librpm to get a directory file descriptor (or path) to the rpmdb directory
- Change the code to whever something is written call `touch()` on that directory
- Suggest that higher level libraries use inotify (not rpm itself)

**Comment by Conan-Kudo** [comment]
@cgwalters Okay, and how do non-Linux systems do this?

**Comment by ffesti** [comment]
With the dbus announce plugin we now have a way to be notified by changes. I doubt we'll add  another mechanism any time soon. Closing.
