### ISSUE TITLE
RFE: rpm without database

### ISSUE THREAD

**Issue by lnussel** [rpm-software-management/rpm#1151]
How about not storing rpm headers in some binary database anymore but rather as individual files on disk?

Ie rather than stuffing them into /usr/lib/sysimage/rpm/Packages.$format just dump them as is, eg
/usr/lib/sysimage/rpm/installed/hello-1.2-3.x86_64.rpm

That opens several possibilities

- The database format does not matter anymore. The "database" could be moved back to /var as it would be  just a cache of indices that can be thrown away any time. rpm could just re-create them if needed or asked to.
- A diff of the file system tree of different versions of the operating system (eg snapper snapshots) would show right away what  packages changed.
- Similarly it would make life easier for container layers as  there's no binary database blob involved.
- One does not actually need rpm for simple introspection. `ls` is  sufficient for the equivalent of `rpm -qa`. In fact given simple  packages, basic rpm operations could be emulated in shell even.
- rpms could "package" their header as %ghost. So the header would actually be part of the file system representation of the package.

**Comment by lnussel** [comment]
With uncompressed payload one could even copy the full rpm into /usr/lib/sysimage/rpm/installed and reflink the data.

**Comment by Conan-Kudo** [comment]
This would essentially make it so rpm can behave the same way dpkg does, and opens us to the same problems dpkg has:

* People can and will randomly manipulate files to force the package manager to do weird things (it's even documented in various troubleshooting guides)
* It is not possible to atomically update package information, nor provide any transactional qualities. This means also it's possible to have races all over the place, depending on filesystem and OS semantics.

I don't think it's a bad idea to provide a way to export this, but I wouldn't think of it as a good idea to make rpm _rely_ on it. Also, with the exception of ndb, pretty much all rpm backends have been externally introspectable. So unless you're using ndb, you're usually able to at least read the database without rpm.

I also don't think the binary blob "issue" is particularly compelling for the container case, because container images and their layers are almost entirely made of binary blobs. If this hasn't been optimized for already, people are not doing their jobs well. 😜 

And the potential benefit of moving it back into `/var` (which, to be clear, is only an issue on RPM-OSTree and SUSE distributions) is negated by the fact that we'd _still_ need stuff in `/usr/lib/sysimage/rpm` to rely on. But we'd wind up with a state synchronization problem on top of it, which just makes everything worse.

So in the end, I'm not sure this is a good idea.

**Comment by lnussel** [comment]
>     * People can and will randomly manipulate files to force the package manager to do weird things (it's even documented in various troubleshooting guides)

Well, obfuscating the database for the purpose of avoiding people to mess with it doesn't sound like an overly good motivation. RPM headers would still be binary and are signed, so you can't arbitrarily edit them like text files anyways.
 
>     * It is not possible to atomically update package information, nor provide any transactional qualities. This means also it's possible to have races all over the place, depending on filesystem and OS semantics.

I have no insight to the other database formats so can't comment on how that is handled. For setups that never modify the running system but rather either prepare images or modify snapshots the transactional capabilities of rpm do not matter anyways. If anything goes wrong, no new snapshot/image gets produced.

**Comment by Conan-Kudo** [comment]
> I have no insight to the other database formats so can't comment on how that is handled. For setups that never modify the running system but rather either prepare images or modify snapshots the transactional capabilities of rpm do not matter anyways. If anything goes wrong, no new snapshot/image gets produced.

But that's not even close to the common case that RPM is used for. Any feature added to RPM must be considered holistically useful and made relatively safe (within the context of RPM packaging management). Virtually everything is safe in the model of using installroots and snapshots, but most usage of RPM is on live systems, so that makes it difficult to justify this feature.

**Comment by pmatilai** [comment]
Would it be possible to implement a "filesystem" database backend? Most likely. We've even tossed it around a few times between ourselves, but there's just very little benefit and all manner of downsides, such as those @Conan-Kudo already mentioned. I wouldn't call locking, atomic operations and the like "obfuscation".

I don't see us working on this, and because of those issues I don't see us wanting to maintain one even if somebody else did the work up front.

**Comment by lnussel** [comment]
Note that installing the headers on disk as part of package installation does not exclude actually using one of the existing database formats.

**Comment by Conan-Kudo** [comment]
@lnussel If you want that, just write a post-transaction trigger to run `rpm --exportdb` somewhere...

**Comment by lnussel** [comment]
that's a good start at least. There's also --importdb. So with slightly more code that could sync back and forth with a directory
