### ISSUE TITLE
API documentation generation broken with doxygen > 1.8.7

### ISSUE THREAD

**Issue by pmatilai** [rpm-software-management/rpm#131]
For whatever reason, the modules page is not generated anymore with newer doxygen versions, see http://ftp.rpm.org/api/4.13.0/ vs http://ftp.rpm.org/api/4.12.0.1/. In git master the main page is supposed to have content as well but that's also missing when the modules breakage happens.

I chased the breakage starting with doxygen 1.8.8 but didn't spot anything obvious,  it's not warning or whining about anything that I can see. Help figuring that out would be most welcome.

**Comment by rpm-maint** [comment]
On 20 January 2017 at 10:01, Panu Matilainen <notifications@github.com> wrote:
>
> For whatever reason, the modules page is not generated anymore with newer doxygen versions, see http://ftp.rpm.org/api/4.13.0/ vs http://ftp.rpm.org/api/4.12.0.1/. In git master the main page is supposed to have content as well but that's also missing when the modules breakage happens.
>
> I chased the breakage starting with doxygen 1.8.8 but didn't spot anything obvious, it's not warning or whining about anything that I can see. Help figuring that out would be most welcome.

Hi
You could open a BZ so that the FC maintainers could bring their expertise.
See you

**Comment by pavlinamv** [comment]
The problem is because:

> In version 1.8.8 a change has taken place about handling files
> with unknown / unsupported extension. Till that version they were seen as
> C-like files. In version 1.8.8 and up they are skipped, but it is possible
> to use your own extension and map it to a supported version. 

Thus files
doc/librpm/Doxyheader 
doc/hacking/Doxyheader
are skipped and that is why "Modules" are missing.

To solve the problem: 
Add to both files "Doxyheader" an extension. According to the extension, change files "hacking.doxy.in" and "librpm.doxy.in" as it is in change.diff (for extension "xxx").

Another option is to configure "hacking.doxy.in" and "librpm.doxy.in" to process files without extension (no_extension). Doxygen would start to go through all files without extension - README,  INSTALL, ...   as C files, which could lead to undesired results. Therefore I prefer the first option.

[change.txt](https://github.com/rpm-software-management/rpm/files/753006/change.txt)

**Comment by pmatilai** [comment]
Oh. I suppose it even makes sense. Fixed now, by simply giving the Doxyheader files a .h extension (commit e8438555279b9a4e406ffd0edfc224de1c2862a6).

Thank you for figuring this out!
