### ISSUE TITLE
Is there a way to handle Requires(Pretrans) dependency in a single transaction

### ISSUE THREAD

**Issue by keerthanakalyan** [rpm-software-management/rpm#1337]
I have a package A with package B as Requires(pretrans) dependency. While trying to install pkg A if B is not already installed on the system it gives "error: Failed dependencies". Even though I add package B as part of the installation. 

```
#] $ rpm -ivh B-1.0-1.x86_64.rpm A-1.1-1.x86_64.rpm
error: Failed dependencies:
        B is needed by A

```

I verified the same in dnf and it gives the same dependency error. 
Does RPM provide any API to query the Requires(pretrans) dependencies and  create two transactions in package managers instead of a single transaction?

**Comment by pmatilai** [comment]
As per the name, a *pretrans* dependency has to be present prior to transaction start and cannot be satisfied by other packages in the transaction, because the transaction hasn't started at that point! That behavior is the whole point of that special dependency type.

The dependency info is of course queriable via API (and cli), but rpm doesn't offer any special aid to construct multiple transactions in such a situation, it's up to the API user to do so.
