### ISSUE TITLE
Transaction ordering should break dependency loops at weak dependencies (if there are any)

### ISSUE THREAD

**Issue by t8m** [rpm-software-management/rpm#1346]
RPM now considers weak dependencies during the transaction ordering. However weak dependencies were sometimes also used as a way to actually break the dependency loops between the packages.

For that reason the transaction ordering algorithm should break dependency loops at weak dependencies if there are any.

**Comment by pmatilai** [comment]
Yup, weak dependencies can and do create massive loops that do not exist without them as weak dependencies are more liberally sprinkled around. They should be taken into account in ordering but not equal to hard dependencies (including pre- and other variants and their side-effects)

**Comment by jamescassell** [comment]
This seems like a rather important issue to fix... it could help eliminate lots of otherwise-unnecessary `%posttrans` and `%pretrans` scripts that exist only due to dependency-order unpredictability.

**Comment by dmnks** [comment]
Yet another practical example from Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2252661

**Comment by pmatilai** [comment]
Thinking some more on this, I believe the right thing here is treating regular (as in not having (post/pre) type qualifiers) weak dependencies as implicit "meta" dependencies, which is exactly how they are *normally* used (eg that fwupd case).

For the rare case where packagers do want them to affect ordering for actual use in scriptlets, they can use Recommends(post) or such. That is, once we really fix #624 . Only, to keep them from messing up hard requires, we demote them to non-qualifier dependencies (this we already do since commit d6353c96fed98a8d30d9ebadf4d6a19a5149edee)

This is of course different from hard dependencies, but weak dependencies *are* fundamentally different.
