### ISSUE TITLE
invalid memory read in rstreqn / rpmdsNewPool

### ISSUE THREAD

**Issue by hannob** [rpm-software-management/rpm#137]
The attached file causes an invalid memory read access with rpm -i --test.

[rpm-invalidread-rpmdsNewPool-rstreqn.zip](https://github.com/rpm-software-management/rpm/files/736808/rpm-invalidread-rpmdsNewPool-rstreqn.zip)

asan error:
```
==5681==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x000000442d96 bp 0x7ffccc0307b0 sp 0x7ffccc02ff10 T0)
==5681==The signal is caused by a READ memory access.
==5681==Hint: address points to the zero page.
    #0 0x442d95 in __interceptor_strncmp.part.68 (/r/rpm/rpm+0x442d95)
    #1 0x534748 in rstreqn /f/rpm/rpm/lib/../include/rpm/rpmstring.h:127:13
    #2 0x534748 in rpmdsNewPool /f/rpm/rpm/lib/rpmds.c:349
    #3 0x58f49b in addTE /f/rpm/rpm/lib/rpmte.c:163:19
    #4 0x58f49b in rpmteNew /f/rpm/rpm/lib/rpmte.c:241
    #5 0x512642 in addPackage /f/rpm/rpm/lib/depends.c:438:9
    #6 0x5122e9 in rpmtsAddInstallElement /f/rpm/rpm/lib/depends.c:493:12
    #7 0x57a1d4 in rpmInstall /f/rpm/rpm/lib/rpminstall.c:584:11
    #8 0x5057ae in main /f/rpm/rpm/rpmqv.c:295:12
    #9 0x7f6ad35aa78f in __libc_start_main (/lib64/libc.so.6+0x2078f)
    #10 0x41c648 in _start (/r/rpm/rpm+0x41c648)

**Comment by hannob** [comment]
Update: Still unfixed in 4.13.0.1.

**Comment by pmatilai** [comment]
It'll cleanly fail on signature checking (rpm -K) however, which is what you're supposed to do for unknown packages before even considering installation. That's usually considered the minimal criteria for rpm.

The underlying issue here is that practically ALL of rpm assumes tags are of the correct type, and funky segfaults happen when they're not. There are countless variations of the theme, most of the other cases in this report batch have similar issues but also happen to have something else that will cause them to fail earlier. Making all of rpm check for tag types and return codes for all retrievals, modifications etc is a colossal task and is just not going to happen in a 0.1 release.

**Comment by pmatilai** [comment]
The immediate crasher was already addressed, the underlying larger issue of tag validation will be tracked in #242 from here on.
