### ISSUE TITLE
Possible deadlock when macro tracing and debug is turned on

### ISSUE THREAD

**Issue by mlschroe** [rpm-software-management/rpm#1418]
This deadlocks for me:
```
rpm -vv --eval '%trace'
```
It hangs because rpmlog() tries to expand `%{?_color_output}^{!?_color_output:auto}` leading to another call to rpmlog().

We could temporarily clear print_expand_trace in the printExpansion() function but I think a better fix would be to revert commit 7f220202f20c69d6f3fd957325cdbe692bbabedd. It's weird that printExpansion() uses rpmlog, but printMacro() does not. Also, the line is printed with multiple rpmlog calls, leading to `D:` being spread into the output.

The commit does not include a rationale, so it's hard to tell why this was changed in the first place.

**Comment by mlschroe** [comment]
Maybe it was done because expand_trace is turned on if the macro recursion limit is reached. Hmm. Should printMacro() also use rpmlog?

**Comment by pmatilai** [comment]
Looks like https://bugzilla.redhat.com/show_bug.cgi?id=613010 was the background to diverting the spew to the debug log, but I'm not sure that is such a constructive thing to do because it now doesn't even say which macro we tripped on.

rpmlog() is used in multiple places in macros.c so we'll need to somehow untangle the rpmlog color configuration from this anyway, so from that perspective it might make sense to just change printMacro() to use rpmlog() too. No firm opinion on that though...
