### ISSUE TITLE
Do not parse header when validating signatures

### ISSUE THREAD

**Issue by DemiMarie** [rpm-software-management/rpm#1468]
Currently, `rpm -K` parses the header as well as the signature.  If it only parsed the signature, the attack surface would be much smaller, as a far simpler parser could be used.

**Comment by pmatilai** [comment]
Would be wonderful if things were that simple.

But there's no such thing as "the signature", there are multiple digests and signatures ranging over various parts of the package, mostly contained in the signature header (so you need to parse an unprotected header anyhow) but the payload digests are, for security, in the main header.

Rpm does parse of the header intro and a simple text retrieve when signature checking, not because its fun to do but it needs to. The act of actually importing (aka loading) the main header which involves a far more complex set of operations is only done after the signature and digests checks pass.

**Comment by DemiMarie** [comment]
> Would be wonderful if things were that simple.
> 
> But there's no such thing as "the signature", there are multiple digests and signatures ranging over various parts of the package, mostly contained in the signature header (so you need to parse an unprotected header anyhow) but the payload digests are, for security, in the main header.

The signature header will typically be the same for all packages, except for the actual digests and signatures.  This makes an external validator trivial.

> Rpm does parse of the header intro and a simple text retrieve when signature checking, not because its fun to do but it needs to. The act of actually importing (aka loading) the main header which involves a far more complex set of operations is only done after the signature and digests checks pass.

Good to know.  To clarify: do we ever call `headerImport()` on an unverified header?

**Comment by pmatilai** [comment]
`headerImport()` is a public API function, it's up to the caller what sort of verification is needed in a given situation. Within rpm, it depends on configuration and API switches and whatnot. 

Anyway, rpm can't just stop parsing the things it does now, so I'm going to close this.
