### ISSUE TITLE
rpmsign asks for key password twice per file

### ISSUE THREAD

**Issue by Arusekk** [rpm-software-management/rpm#150]
Because of `makeGPGSignature()` being called separately for header and contents ([sign/rpmgensig.c:403](https://github.com/rpm-software-management/rpm/blob/master/sign/rpmgensig.c#L403)), and that GPG asks for password itself — each time it is called — signing every single rpm requires typing the password twice.

This could be fixed in two ways:
 * by temporarily storing the password in memory and giving it to GPG when it needs to open the key
 * opening the secret key once, and then signing the packet with the key being already opened.

**Comment by pmatilai** [comment]
Right, since rpm >= 4.13 the expectation is to have gpg-agent handle this. Distros have been patching rpm to use gpg2 but as of 4.13 upstream still defaults to gpg1 so I guess this is the behavior you get with real upstream defaults. Dangers of distro patches...

As a workaround you should be able to set %__gpg to /usr/bin/gpg2 after which the agent will take care of this.

**Comment by dmnks** [comment]
Closing as per https://github.com/rpm-software-management/rpm/issues/150#issuecomment-278279277.

**Comment by mgdepalma** [comment]
Looks to me that taking the best of the sources rpm-4.11.1 and perhaps misguided or for profit took over needs to reconcile in the best interest of the open source community need merge. I am working on such task for rpm-4.15.1
