### ISSUE TITLE
Can't use `--define "_gpg_name Foo"` any more

### ISSUE THREAD

**Issue by jsumners** [rpm-software-management/rpm#153]
Example project -- https://github.com/jsumners/staticdhcpd-rpm

When the build script in that project is run it looks for a sibling file `gpg-env`. If found, it sources the file and generates the build command like so:

```
rpmbuild --define "_topdir ${CWD}/rpmbuild" \
      --define "_signature ${signature}" \
      --define "_gpg_path ${gpg_path}" --define "_gpg_name ${gpg_name}" \
      --sign --ba rpmbuild/SPECS/${SPEC1}
```

This works just fine in a RHEL 6 environment. But if you do it in a RHEL 7 environment it fails saying:

```
You must set "%_gpg_name" in your macro file
```

**Comment by pmatilai** [comment]
Yup, signing support was removed from librpmbuild between RHEL 6 and 7 as insecure, rpmbuild --sign option is only minimally supported through a popt alias which certainly wont handle this case.

**Comment by jsumners** [comment]
As a user, those details don't matter to me. The `--sign` option is still there. The ability to specify environment variables via `--define` is still there. The combination should still work.

**Comment by stephan57160** [comment]
Agreed with jsumners
> As a user, those details don't matter to me

Confirmed with pmatilai: 
> minimally supported
> wont handle this case

Even the --macros is not passed properly to rpmsign, when called from rpmbuild ...
At least, documentation is updated, somewhere, to provide info on that topic ?

**Comment by n3npq** [comment]
I would also suggest that the current implementation which does not permit a single build-and-sign operation has a larger attack surface, permitting an unsigned package to be modified until signed.

I do not understand the reasoning that claims that a single build-and-sign command is deemed "insecure". Perhaps what is meant is that users were using secret keys with no passwords in automated builds to avoid having to supply the password for the secret key. But that is an "insecure" usage and not an "insecure" implementation.

**Comment by n3npq** [comment]
See issue #454 for a suggestion to pass passwords to helpers (like rpmbuild) using kernel keyrings, the same mechanism commonly used to hold file system passwords when needed.

**Comment by n3npq** [comment]
To clarify how kernel keyrings could be used to preserve --sign behavior ...

The popt alias for rpmbuild --sign extracts the names of just built *.rpm files from stdout and invokes  rpmsign on those packages.

The rpmbuild options like --macros and --define are not copied to rpmsign.

Instead of copying options forward (which is doable) from rpmbuild to rpmsign, rpmsign should attempt to retrieve the password that gpg expects from a conventionally named kernel keyring entry.

the rpmsign helper use exec2) so that rpmsign becomes a direct child of  rpmbuild (that already happens with a popt exec alias, but obscurely) with the set of packages as arguments.

Kernel keyring access controls are then used to protect the password while being passed through the sequence  rpmbuild -> rpmsign -> gpg and either rpmbuild or rpmsign reads the password and stores in the keyring for each set of packages. 

If the keyring access control is per-session, then the password can be loaded outside of rpmbuild invocation for retrieval by rpmsign through other means.
