### ISSUE TITLE
Tag alpha rpm versions?

### ISSUE THREAD

**Issue by romulasry** [rpm-software-management/rpm#1614]
Thoughts?

    Pre-release status = true

**Comment by pmatilai** [comment]
Um, tag what, where? I have no idea what you mean by this.

**Comment by ffesti** [comment]
Well, the page says "Draft" for a reason. 4.17.0-alpha is not tagged because it is not out yet. All actual releases are tagged in the git repository. Note that we did not always do alpha releases in the past. RPM is such a central component of the distribution that we don't really expect people to volunteer their systems to test alpha versions. But for the last few releases alphas were used to give an idea what changes are going to be in the up coming release and to give a signal for still unfinished features to hurry up if they still want to make it in.

Closing.
