### ISSUE TITLE
Upgrade lua library dependencies

### ISSUE THREAD

**Issue by daurnimator** [rpm-software-management/rpm#165]
The libraries in 'luaext' are ancient (from 2003!) vendored in versions of [lrexlib](https://rrthomas.github.io/lrexlib/) and [lposix](http://webserver2.tecgraf.puc-rio.br/~lhf/ftp/lua/#lposix) (which was superceded by [luaposix](https://github.com/luaposix/luaposix))

It's time to upgrade. and even more preferable: make rpm depend on those libraries dynamically rather than vendoring them in.

**Comment by pmatilai** [comment]
How's the compatibility record of these modules upstream? The problem is, these modules are used from package scripts and we don't want to break (the same problem exists with Lua itself of course).
The other problem is that in particular the lposix module is forked to some extent to protect rpm.

**Comment by daurnimator** [comment]
> How's the compatibility record of these modules upstream?

Rather good incrementally; but 14 years is a lot of incremental changes...

**Comment by pmatilai** [comment]
So I finally had a closer look at this. It would've been one thing to pull in a few new functions and bugfixes, but one library has been replaced entirely with a far more complicated, multi-source thing, and the other has also grown hugely in complexity. All that increased complexity means more things that can go wrong, on top of all the compatibility concerns for changing to an entirely different poxix library. 

The posix extensions are not there so that scriptlet writers can rewrite the entire unix userland in Lua. They're there to allow basic path manipulation and executing helpers, which they achieve just fine as it is. I don't think I've ever seen a single use of the rexlib. So this is all complexity that we don't actually need, at non-trivial risk to users. More is not always better, not at all.

We're not going to upgrade and/or replace those libraries at all, because there's *no need* whatsoever. Adding rpm-specific helpers where relevant is going to help scriptlet writers much more than maximal coverage of the posix api.

**Comment by Thaodan** [comment]
Is there a chance to revive this? from a quick look they seem  pretty interchangeable.
The main difference is see its more modern and complex. Not vendoring comes with the advantage not needing to maintain the code anymore and not duplicating those libraries on the system.

**Comment by pmatilai** [comment]
See my comment above, the situation has not changed one in any way.
