### ISSUE TITLE
Make RPM consistent with DNF

### ISSUE THREAD

**Issue by j-mracek** [rpm-software-management/rpm#1681]
RPM and DNF have several differences in CLI and API. In long term it will be nice to improve consistency between similar or related components. As an example I can use handling of epoch. See `rpm -q dnf` and `dnf repoquery dnf`. Also the output for `--queryformat="%{epoch}"` differs. DNF shows `0` and RPM `(none)`.

API differs in `evr` handling too. DNF skips `0` epoch, but rpm not. I am sure that there are more examples of inconsistency.

Both component are important for many users and we can make their life better when we will improve the consistency.

See also: https://github.com/rpm-software-management/libdnf/issues/1228

**Comment by pmatilai** [comment]
As the original author of repoquery (in the yum era), certain differences were quite intentional.
For `--queryformat="%{epoch}" ` 0 vs none difference the issue is rpm showing the *real* situation whereas createrepo turns a non-existent epoch to zero making it impossible to differentiate. Similarly in EVR, rpm shows the epoch IFF it really exists.

**Comment by pmatilai** [comment]
There's too much history and too many queries out there to change how rpm behaves here. Also queryformat supports testing for tag existence too and that'd break if we didn't differentiate between 0 and NULL, effectively.

Note that for the particular case of epoch, you can use `%{epochnum}` extension to always get an integer value. Dnf could add support for that.
