### ISSUE TITLE
RFE: gathering the release notes

### ISSUE THREAD

**Issue by juhp** [rpm-software-management/rpm#1683]
I was wondering if it would not be good idea to collate all the recent release notes into one big file
(I dunno say `RELEASES`?) which would make checking the rpm change history of releases much easier.

eg Just now I was trying to work out when `rpmspec` gained support for --with/--without
but pretty much gave up now - hunting through all the release notes on the wiki is too difficult
and ChangeLog of commits is too low-level and dense.

**Comment by juhp** [comment]
Well I just found https://rpm.org/timeline.html which seems close to this.
So maybe this rpmspec feature I was looking for just slipped off or didn't make the relnotes...

**Comment by juhp** [comment]
(My guess is that `rpmspec -P --with` support was probably added in 4.15.0?)

**Comment by pmatilai** [comment]
with/without support in rpmspec was never specifically mentioned anywhere at all because it happened as a part of a more generic change (see commit 1896e58ffdf2278c47fea5f6e7d29bbf81eac1ad). The first released version with those aliases is actually 4.15.1. Basically just something that fell through the cracks.
