### ISSUE TITLE
Create CONTRIBUTING.md with contribution instructions

### ISSUE THREAD

**Issue by DemiMarie** [rpm-software-management/rpm#1707]
As per @pmatilai in <https://github.com/rpm-software-management/rpm/pull/1677#issuecomment-862402804>:

> It's a bit late by now, but of course it would've helped. I've said many many times that these kind of mega PR's have close to zero chance of being accepted because they're not meaningfully reviewable on GH.
> 
> PR's can be more than one commit but the commits need to be _closely_ related in the sense that all of them must go in at once or not at all. Sprinkling anything unrelated into it will quite effectively stop a review from progressing. Far worse is multiple mega PR's overlapping and containing different versions of commits etc.

Ideally this information should be in CONTRIBUTING.md, so other contributors do not make the same mistakes I did.

**Comment by DemiMarie** [comment]
CONTRIBUTING.md should also include whether dependent commits (where the second commit requires the first, but the first can be included without the second) should be the same or separate PRs.

**Comment by pmatilai** [comment]
Yes contributing and coding style docs are one of the many many things missing.

Short of those... we're just following commonly used best practises. While various details such as exact indentation and media differ, for the kernel docs provide excellent general guidance on both topics:
- https://www.kernel.org/doc/html/latest/process/submitting-patches.html
- https://www.kernel.org/doc/html/latest/process/coding-style.html 

A PR with multiple commits is similar to a patch series, but email is far more flexible media for that than GH, because one can properly review each patch on their own merits and apply individual patches easily. A GH PR is technically an all or nothing proposition, and reviewed as such. As a ballpark rule, the resistance to getting reviewed and merged grows exponentially with number of commits because it's just so much more trouble than it's ever worth.

**Comment by pmatilai** [comment]
Initial doc added in #1709
