### ISSUE TITLE
Mono dependencies are not always completely accurate

### ISSUE THREAD

**Issue by LaurentTreguier** [rpm-software-management/rpm#185]
From what I have seen of the [`mono-find-requires`](https://github.com/rpm-software-management/rpm/blob/master/scripts/mono-find-requires) script, `monodis --assemblyref` is used to find out dependencies with mono assemblies. While it seems to work mostly well, I've had an issue recently packaging [fsharp](https://github.com/fsharp/fsharp).

You can see more details [here](https://github.com/fsharp/fsharp/issues/699). Apparently some dependency versions can be forced with a config file, but this is not taken into account by `mono-find-requires`.

Does anyone know if there is some way to take those config files into account to correct the dependencies versions when possible and have more accurate dependencies ?

**Comment by pmatilai** [comment]
The Mono dependency extraction scripts were contributed by an "outsider" about ten years ago and have been untouched ever since, so it's not exactly a big wonder that world around them has moved on a bit.

My knowledge about Mono ends shortly after the "it exists" level, so this would be a case of patches welcome - somebody who actually knows something about Mono would need to investigate.

**Comment by LaurentTreguier** [comment]
My knowledge of Mono is about the same for now... But I'm willing to learn more and work on it ; the script doesn't seem to be too complex and getting the correct dependencies look like a matter of parsing some XML

**Comment by ffesti** [comment]
Reading the linked issue that might be a problem with how fsharp was handling their symbols. I really don't know what to do here. Closing for now. Feel free to reopen if new details emerge.
