### ISSUE TITLE
Ignore subkeys that are expired or cannot be used for signing

### ISSUE THREAD

**Issue by DemiMarie** [rpm-software-management/rpm#1911]
Such keys should be ignored by RPM.

**Comment by DemiMarie** [comment]
@pmatilai @ffesti is it okay if I make a PR for this?  It is a somewhat substantial change.

**Comment by pmatilai** [comment]
We don't look at expiry dates on main keys, on purpose. How are subkeys different?
Ignoring keys that can't be used for signing seems reasonable though, I guess.

**Comment by teythoon** [comment]
> We don't look at expiry dates on main keys, on purpose. How are subkeys different?

I suppose you do that so that old signatures still check out even after the issuing certificate expires, e.g. old distribution certificates.

Note that outright ignoring expiration times is not the best way to accomplish this.

A consequence of ignoring expiration times is that expired certificates can still issue new signatures.  Imagine an old distribution  signing key being exfiltrated after it is expired.  Now, all installations that still have that old certificate in their set of trusted certificates will consider newly created signatures valid, even though their copy of the certificate says it is expired.

A better way is to look at the creation time of the signature you want to verify, then ask the question whether the certificate and its signing subkeys are valid at that point in time.

**Comment by pmatilai** [comment]
The problem with expiration is that people have software installed and it doesn't get uninstalled or inaccessible by a clock ticking someplace (similar issue with revocation). But "valid at the time of signing" is indeed a much better way to look at it.

**Comment by DemiMarie** [comment]
> A consequence of ignoring expiration times is that expired certificates can still issue new signatures. Imagine an old distribution signing key being exfiltrated after it is expired. Now, all installations that still have that old certificate in their set of trusted certificates will consider newly created signatures valid, even though their copy of the certificate says it is expired.
> 
> A better way is to look at the creation time of the signature you want to verify, then ask the question whether the certificate and its signing subkeys are valid at that point in time.

This alone isn’t sufficient for primary keys.  The person with a copy of the secret key can just make a signature that claims to be from when the key was still valid.  They could also create a new self-signature that makes the key no longer expired. 
 A better solution is for distributions to generate their signing keys on smart cards, so that they can securely erase them once they are no longer in use.  Cryptographic Message Syntax, which is used by Windows for its code signing, solves the problem by means of a third-party time-stamping countersignature, which proves that the signature was actually made before a certain point in time.

That said, RPM needs to be able to handle expired signatures in the rpmdb.  Could `RPMRC_NOTTRUSTED` be used for that?

> We don't look at expiry dates on main keys, on purpose. How are subkeys different?
> Ignoring keys that can't be used for signing seems reasonable though, I guess.

Subkeys are different because they provide a mechanism for key rotation.  Someone in possession of a subkey cannot simply increase the subkey’s validity arbitrarily, as only the primary key can create a new subkey binding signature.  One should also be able to revoke a subkey and mark signatures made by the subkey after a certain point as no longer valid.  This requires that RPM support subkey revocation.  I might be able to implement this, but I would need to know where to store the data.  @pmatilai any suggestions?

**Comment by pmatilai** [comment]
From rpm POV, the revocation problem is exactly the same as expiry: software doesn't get uninstalled or become inaccessible by somebody somewhere revoking something. Rpm would need to use a different policy for installed packages to make that possible, and it all spins out of hand real fast.

The sanest thing for rpm to do would be dropping support for subkeys because that opens up all manner of complications that just don't exist with primary keys. When subkey parsing support was added in 355c9b069f25d3a9c3dc224fb39a90522c04ca28 , I doubt the complexities were considered at all.

The other thing to keep in mind wrt rpm key support is that rpm's imported == trusted key model means that you only feed very curated material into rpm. It doesn't generally need to handle arbitrary key data off the net, like a general purpose OpenPGP implementation does.

**Comment by mlschroe** [comment]
IMHO Rpm should just behave like gpgv in regards to subkeys, key expiration, and revokations.

**Comment by teythoon** [comment]
> This alone isn’t sufficient for primary keys. The person with a copy of the secret key can just make a signature that claims to be from when the key was still valid. They could also create a new self-signature that makes the key no longer expired.

While that is true, I would assume that the set of trusted OpenPGP certificates on old installations is fixed and won't be updated.  Under this assumptions, the attacker can not extend the expiration time.  Thus, honoring the expiration closes an attack vector by invalidating newer signatures.

There is the caveat that an attacker can backdate the signature creation time.  To protect against that, the creation time must be corroborated by other means, the OpenPGP implementation cannot do that alone, one needs to consider context.

Invalidation of cryptographic material, either via expiration or revocation, is tricky.  But, ignoring expiration times certainly doesn't help.

**Comment by nwalfield** [comment]
> A better way is to look at the creation time of the signature you want to verify, then ask the question whether the certificate and its signing subkeys are valid at that point in time.

FWIW, this is the policy that I chose in the Sequoia backend for rpm.  [The signature is check at the current time](https://gitlab.com/sequoia-pgp/rpm-sequoia/-/blob/bf085711/src/lib.rs#L438-445).  And [a view of the certificate is create as of the signature's time](https://gitlab.com/sequoia-pgp/rpm-sequoia/-/blob/bf085711/src/lib.rs#L455).

**Comment by DemiMarie** [comment]
> > A better way is to look at the creation time of the signature you want to verify, then ask the question whether the certificate and its signing subkeys are valid at that point in time.
> 
> FWIW, this is the policy that I chose in the Sequoia backend for rpm. [The signature is check at the current time](https://gitlab.com/sequoia-pgp/rpm-sequoia/-/blob/bf085711/src/lib.rs#L438-445). And [a view of the certificate is create as of the signature's time](https://gitlab.com/sequoia-pgp/rpm-sequoia/-/blob/bf085711/src/lib.rs#L455).

That’s valid, thanks!
