### ISSUE TITLE
Make 'rpm -V' more resistent against rpmdb manipulations

### ISSUE THREAD

**Issue by robert-scheck** [rpm-software-management/rpm#196]
https://github.com/x0rz/EQGRP/blob/33810162273edda807363237ef7e7c5ece3e4100/Linux/doc/old/etc/user.mission.generic.COMMON.old refers to "DIZZYTACHOMETER", which is a tool to manipulate the rpmdb in order to avoid `rpm -V` reporting manipulated/changed/replaced binaries/files of installed RPM packages. While this is indeed nothing really new (on a technical level, didn't personally see such a tool described in the wild), it still would be IMHO handy to make `rpm -V` in the future more resistent against rpmdb manipulations – however that would finally look like.

**Comment by n3npq** [comment]
Hmmm ... its not clear what  exploit is used (from just reading the file at the URL you gave).

The RPM versions (4.1/4.2) mentioned in the URL are quite ancient (circa RHL 8/9).

Even on those ancient systems, /var/lib/rpm requires access to root:root (or rpm:rpm) in order to modify an rpmdb (but the derivative task of the exploit is hiding a rootkit, where root:root has already been achieved, by changing information in the rpmdb).

The provision in RPM for careful rootkit forensics is to use "rpm -Vp ..." from a CDROM (or other offline/immutable media).

Hardening the manifest of installed packages (i.e. what is in an rpmdb) on an already exploited system would require a security protocol to authenticate/authorize rpm installations, most likely using a TPM and a trusted boot to ensure that the RPM executable was not compromised, and then to keep track of the list of package headers which SHOULD be installed, as well as verifying header signatures before verifying package contents.

This isn't an easy problem to solve.

**Comment by robert-scheck** [comment]
> Hmmm ... its not clear what exploit is used (from just reading the file at the URL you gave).

I think "DIZZYTACHOMETER" doesn't exploit anything itself, but is just hiding e.g. a rootkit installation by manipulating the rpmdb based on already existing write permissions gained before. I didn't find the binary nor any source for "DIZZYTACHOMETER", but the way of usage makes me assuming "regular" rpmdb manipulations, not a RPM related security flaw.

> The provision in RPM for careful rootkit forensics is to use "rpm -Vp ..." from a CDROM (or other offline/immutable media).

Immutable media…something that is harder and harder to get when looking to Fedora or RHEL (last with CDN). Sometimes (e.g. at EPEL as 3rd party repository) the RPM package has been already orphaned and thus removed from the repository when it comes to a verification case.

> This isn't an easy problem to solve.

Right, and I don't expect a quick solution. Just wild ideas: Blockchains for rpmdb? Optionally trusted (digital) timestamping for rpmdb? But yes, maybe also a further verification tool that somehow handles the situation that offline media is going away. I do not have a specific idea how this could be solved, finally.

**Comment by n3npq** [comment]
Blockchain  can establish that an rpmdb event happened. That isn't enough because a root kit can either fake an rpmdb event, or skip using blockchain to register the event.

On a compromised system, any executable, including the tools used to track installs, can be altered.

Creating a trusted 3rd party store of "orphaned" metadata (like you are describing with EPEL) might use a blockchain to track its updates, and provide metadata and file digests for "rpm -Vp" instead of RO media.

(aside)
There are security protocols in the TCG MTM spec to handle software installations and forensics for manage mobile devices that could be used for an rpmdb. However adding rpm to the "trusted base" would take an effort comparable to switching to "secure boot" on linux.

**Comment by n3npq** [comment]
FWIW, rpm.org has the first (but insufficient) step to hardening forensics on a compromised system.

E.g Here is rpm-4.13.90 output of "rpm -Vvv popt"
`
...
D:  read h#   27079 Header V3 RSA/SHA256 Signature, key ID 81b46521: OK
D: Plugin: calling hook init in syslog plugin
D: Plugin: calling hook init in systemd_inhibit plugin
D: ========== +++ popt-1.16-7.fc24 x86_64/linux 0x2
D:  read h#   34281 Header V3 RSA/SHA256 Signature, key ID fdb19c98: OK
...
`
Hood: DIZZYTACJOMETER is likely replacing/deleting package headers in an rpmdb, not modifying headers.

Importing only "trusted" pubkeys (i.e. rpm's current conception of "trust") with well known pubkey id's and verifying the rpm executable isn't compromised (by using an offline copy of /usr/bin/rpm, or by checking the digest of /usr/bin/rpm with offline forensic tools), is a start at manual forensic procedures.

Verifying pubkey certification signatures could also be attempted (but its non-trivial to alter pukey parameters without also altering the keyid fingerprint). It may (very unlikely, but I've not checked rpm.org recently) be possible to replace the signature on an package header with a different pubkey, or replace the pubkey parameters in the keystore used by RPM.

(Disclaimer: I'm not suggesting that RPM is vulnerable/deficient here, merely stating possible attacks that would make RPM's signature verification described above untrustworthy.)

Some of the manual procedures (like forcing the rpm package to be verified before proceeding with --verify) could be automated without too much difficulty.

A simpler/stricter mode of operation for rpm --verify with exit on failure in a multistep procedure would also help forensic analysis. The current "best effort" (i.e. continue in spite of failures) mode of operation in RPM is too goose-loosey for useful forensics of a compromised system.

Protecting an rpmdb against package header replacement/deletion attacks (what DIZZYTACHOMETER is likely doing to hide rootkits) is unsolved (and not easily solvable).

**Comment by ffesti** [comment]
There is not much one can do on a compromised system as even the tools themselves may be compromised. But there is support for Integrity Measurement Architecture (IMA) and the Linux Extended Verification Module (EVM) in rpm since 4.13 which puts signatures to the security.ima extended file attribute of all (non config) files. Together with storing the keys in the TPM and checking the kernel signature at boot time this much better than anything RPM can hope to achieve with software only.

Closing.

**Comment by pmatilai** [comment]
Just FWIW, #811 is also a step into this direction.
