### ISSUE TITLE
Rpmlua - missing features

### ISSUE THREAD

**Issue by mkoncek** [rpm-software-management/rpm#2095]
I wrote a helper LUA script to help with some code removal where regular expressions are not enough.
I would like ta have it interpretable by `rpmlua` so that we don't have to add  a dependency on lua.
I encountered two problems see: https://github.com/fedora-java/javapackages/pull/90#issuecomment-1154958640
1) shebang
2) CLI arg passing

**Comment by pmatilai** [comment]
I don't know what upstream Lua does for shebang, the problem is that `#` is not a comment character in Lua. Various tricks around this exist, eg: https://lua-users.org/lists/lua-l/2015-01/msg00633.html

rpmlua does accept arguments but has its own quirks, namely that any arguments must go after --. IIRC this is exactly the same as with normal Lua, it's just not so prominent when you use a shebang. So to call rpmlua, use `rpmlua <script> -- <options>`. Couple of examples in https://lua-users.org/lists/lua-l/2015-01/msg00633.html

**Comment by mkoncek** [comment]
Consider the following script:
```lua
print(arg[-1])
print(arg[0])
for k, v in ipairs(arg) do
        print(k, v)
end
```
And invoking it:
```
[root@55eace74b25d javapackages]# rpmlua ./java-utils/java_remove_symbols.lua -- param -p flag
-1      nil
0       nil
1       ./java-utils/java_remove_symbols.lua
2       param
3       -p
4       flag
[root@55eace74b25d javapackages]# lua ./java-utils/java_remove_symbols.lua -- param -p flag
-1      lua
0       ./java-utils/java_remove_symbols.lua
1       --
2       param
3       -p
4       flag

```
`rpmlua` behaves differently from `lua`, both in using `--` as separator and in numbering the `arg` parameter. I can separate the functions from arg handling code to make it work with both `lua` and `rpmlua` but I see this difference in behaviour as a problem. Although I doubt you are going to change it.

**Comment by pmatilai** [comment]
The reason rpmlua behaves the way it does is for compatibility with rpm itself: this is how macros and scriptlets receive their arguments since day 1, and we can't change those without breaking the world.

**Comment by pmatilai** [comment]
FWIW, the off-by-one argument thing is documented in https://rpm-software-management.github.io/rpm/manual/lua.html#lua-scriptlets but that's going to be hard to discover when you're just running `rpmlua`. Probably worth a mention in the `rpmlua` manual, so lets at least document this.

**Comment by mkoncek** [comment]
Maybe the `arg[-1]` should still be set to `rpmlua`?
