### ISSUE TITLE
rpmdsRpmlib has inconsistent arg usage

### ISSUE THREAD

**Issue by eezstreet** [rpm-software-management/rpm#2112]
RHEL6:
```cpp
static rpmds baseDependencies = NULL;
if(baseDependencies == NULL) {
  rpmdsRpmlib(&baseDependencies, NULL); // returns 0
}
```

RHEL7 and up:
```cpp
static rpmds baseDependencies = NULL;
if(baseDependencies == NULL) {
  rpmdsRpmlib(&baseDependencies, NULL); // does not return 0
}
```

This is unexpected. However! If we flip the arguments, it works fine on RHEL7 and up:

```cpp
static rpmds baseDependencies = NULL;
if(baseDependencies == NULL) {
  rpmdsRpmlib(NULL, &baseDependencies); // returns 0
}
```

Why? The type of `rpmdsRpmlib` hasn't changed between now and then. The name of the args hasn't changed. Is the documentation wrong? What gives?

**Comment by pmatilai** [comment]
The arguments and the functionality is unchanged, 

```
rpmds ds = NULL;
rpmdsRpmlib(&ds, NULL); 
```

is what rpm itself has always used and at least in current versions does also return 0 as expected. RHEL 6-7 rpm is long since unsupported upstream, but FWIW in ancient versions like the one in RHEL 6, rpmdsRpmlib() always returns 0 regardless of errors.
