### ISSUE TITLE
4.17.0: NoSource files are not deleted with --rmsource

### ISSUE THREAD

**Issue by kloczek** [rpm-software-management/rpm#2133]
When it is execuret "rpmbuild -bp foo.spec --rmsource" and in spec fiel is specified "NoSource: 0" what is listed in "Source0:" is not deleted.

**Comment by ffesti** [comment]
This is intentional. At least there is special code to leave those files alone. It is called `rmsource` and these are `No(t)Source`. The deeper reason is that those are not packaged in the SRPM but need to be supplied from somewhere else. So just deleting them may lead to data loss or at least be pretty inconvenient. So RPM is the opinion that it does not manage these files and as such it won't delete them.

**Comment by kloczek** [comment]
OK if it is intentional how to clean all NoSource files after build or on %prep execution?
Source listed in NoSource cau have URL and can be downploaded from that URL.
