### ISSUE TITLE
Cannot build any packages on my Fedora 36 installation due to "error: Empty %files file /root/rpmbuild/BUILD/package-name/debugsourcefiles.list"

### ISSUE THREAD

**Issue by birdie-github** [rpm-software-management/rpm#2160]
Description of problem: I cannot re/build any src.rpm packages on my Fedora 36 system

Version-Release number of selected component (if applicable):
```
rpm-4.17.1-3.fc36.x86_64
rpmautospec-rpm-macros-0.3.0-1.fc36.noarch
rpm-build-4.17.1-3.fc36.x86_64
rpm-build-libs-4.17.1-3.fc36.x86_64
rpm-libs-4.17.1-3.fc36.x86_64
rpm-plugin-selinux-4.17.1-3.fc36.x86_64
rpm-sign-libs-4.17.1-3.fc36.x86_64

annobin-plugin-gcc-10.81-1.fc36.x86_64
gcc-12.1.1-1.fc36.x86_64
gcc-c++-12.1.1-1.fc36.x86_64
gcc-plugin-annobin-12.1.1-1.fc36.x86_64
libgcc-12.1.1-1.fc36.i686
libgcc-12.1.1-1.fc36.x86_64

binutils-gold-2.37-27.fc36.x86_64
binutils-2.37-27.fc36.x86_64
```
How reproducible: always

Steps to Reproduce:
`# rpmbuild --rebuild anything`

Actual results:
```
Processing files: package-debugsource-1.2.3-0.fc36.x86_64
error: Empty %files file /root/rpmbuild/BUILD/package-1.2.3/debugsourcefiles.list

RPM build errors:
    Empty %files file /root/rpmbuild/BUILD/package-1.2.3/debugsourcefiles.list
```
Additional info:
```
# rpm -V `rpm -qa | grep rpm`; echo $?
0
```
The system is fully updated.

I don't understand where to look.  This is a copy of https://bugzilla.redhat.com/show_bug.cgi?id=2121050

**Comment by pmatilai** [comment]
It may look like "anything" to you, but you'll need to supply a concrete reproducer if you want someone to investigate it.

That error means the debuginfo machinery didn't find any source files. That can be caused by a number of things, including but not limited to
- package doing nasty things in its build, eg building outside its designated directory
- package not honoring $RPM_OPT_FLAGS in its build flags, and not supplying -g on its own
- a local config overriding some crucial bits (such as -g in the compiler flags) that are required for debuginfo extraction to work

**Comment by pmatilai** [comment]
Oh, and don't build as root.

**Comment by birdie-github** [comment]
I'm trying to build firejail with new sources, version 0.9.70: https://github.com/netblue30/firejail/releases

So, I took this file: https://src.fedoraproject.org/rpms/firejail/raw/f36/f/firejail.spec

And made the slightest modifications:
```diff
-Version: 0.9.66
-Release: 3%{?dist}
+Version: 0.9.70
+Release: 0%{?dist}

-Source0: %{url}/archive/%{version}/%{name}-%{version}.tar.gz
+Source0: %{url}/archive/%{version}/%{name}-%{version}.tar.xz

-%doc README RELNOTES CONTRIBUTING.md
+%doc README RELNOTES
```
Now building it fails under root and a normal user with the same issue.

I have verified I now do _not_ have either /etc/rpm/macros or ~/.rpmmacros.  I'm completely lost.

[build.log.gz](https://github.com/rpm-software-management/rpm/files/9415609/build.log.gz)

**Comment by pmatilai** [comment]
Does the same thing happen with something that doesn't emit suspicious warnings about debug files to begin with, such as https://kojipkgs.fedoraproject.org//packages/popt/1.18/7.fc36/src/popt-1.18-7.fc36.src.rpm ?

**Comment by birdie-github** [comment]
> I haven't seen this warning in any other package, may be related:

This is because this spec file seemingly does something weird, mixes normal and debug files probably?

```
%files
%doc README RELNOTES CONTRIBUTING.md
%license COPYING

%{_bindir}/firecfg
%{_bindir}/firemon
%{_bindir}/jailcheck
%{_bindir}/%{name}
%{_libdir}/%{name}
%{_exec_prefix}/lib/debug/%{_bindir}/
```

> Does the same thing happen with something that doesn't emit suspicious warnings about debug files to begin with, such as

The only warnings I get are:

```
RPM build warnings:
    user mockbuild does not exist - using root
    group mock does not exist - using root
    user mockbuild does not exist - using root
    group mock does not exist - using root
    user mockbuild does not exist - using root
    group mock does not exist - using root
```

**Comment by pmatilai** [comment]
The point of building in mock is that if it works, then it's certainly your installation where the problem is, and you that you have a way of building packages nevertheless. Which is what you're trying to do here, right? This isn't exactly a support hotline so there's a limit how far we're interested to chase what appears to be a one-off local issue, whatever the reason.

Also, we've yet to see the exact command you're using to launch the build in the first place. Which is crucial as you can override arbitrary macros in the command line. So, as a regular user, run 'rpm --rebuild` on the popt package above and post the entire result here, from starting line to end.

**Comment by birdie-github** [comment]
> This isn't exactly a support hotline so there's a limit how far we're interested to chase what appears to be a one-off local issue, whatever the reason.

I've never used a single bug tracker as a support hotline :( I thought I'd uncovered a bug.

> So, as a regular user, run 'rpm --rebuild` on the popt package above and post the entire result here, from starting line to end.

`rpmbuild --rebuild popt-1.18-7.fc36.src.rpm`

[popt.log.gz](https://github.com/rpm-software-management/rpm/files/9416371/popt.log.gz)

**Comment by birdie-github** [comment]
I've found the root cause.

# pwd
/root/rpmbuild

# ls -la BUILD BUILDROOT
lrwxrwxrwx. 1 root root 8 Oct 19  2021 BUILD -> /dev/shm
lrwxrwxrwx. 1 root root 8 Oct 19  2021 BUILDROOT -> /var/tmp

# mount | egrep '/dev/shm|/var/tmp'
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev,seclabel)
tmpfs on /var/tmp type tmpfs (rw,nosuid,nodev,relatime,seclabel)
```

This used to work for at least a decade, now it doesn't. I wonder if it's because they are symlinks or because of these mount flags `nosuid,nodev`.

**Comment by birdie-github** [comment]
And to track it down further,

If `~/rpmbuild/BUILD` is a symlink to `/dev/shm` rpmbuild fails.

**Comment by birdie-github** [comment]
I'd love to keep it this way but considering this is not a support hotline, I'll figure something out. Never been blamed for this but whatever. I'm now afraid to post bug reports. I feel like absolute crap.

**Comment by pmatilai** [comment]
Well, there were many problematic things in this bug report.
- claiming that nothing at all can be built, but it appears to have been one specific package
- claiming this is a "bog standard" installation, when such symlinks in rpmbuild certainly are NOT standard
- not mentioning how this came to be: that it used to work in the first place, then something happened (what? a distro upgrade? just applying updates?), and now it doesn't
- opening two tickets on the same issue, with an excess sense of urgency

Based on experience, this had the air of a one-off weird setup thing from a mile away. There are a hundred million ways a setup can be subtly broken and I would've never guessed the reason in the time I can dedicate to a this kind of isolated case. You figured it by yourself in a matter of hours in the end :+1:  It usually pays off to go that extra mile to troubleshoot ones issues, and compare to another, clean installation before reporting.

It doesn't seem to be the tmpfs as the same happens with a regular fs (BUILD symlinked to /var/tmp) too, and it doesn't seem to be the suid binary either because dropping that has no effect, and it really does seem specific to firejail because with that I can reproduce the issue with a symlinked BUILD, but when tried a bunch of different packages (popt, rpm, util-linux, shadow-utils) everything else builds fine in this setup.

I have no idea whether this is a bug in firejail or find-debuginfo.sh, but if you present this case as it is to debugedit maintainers (https://sourceware.org/debugedit/), they may be able to help you.

**Comment by birdie-github** [comment]
@m-j-w

Could you please take a look?

**Comment by birdie-github** [comment]
@m-j-w

Could you please take a look?

**Comment by m-j-w** [comment]
Wrong recipient, I guess. Don't know what's going in here. Sorry.
