### ISSUE TITLE
CI seems terminally broken

### ISSUE THREAD

**Issue by pmatilai** [rpm-software-management/rpm#2182]
This is as much for general awareness to contributors as it is a ticket for us to do something about it:
our SemaphoreCI based CI seems terminally ill in the last couple of weeks, with jobs running as expected but failing to return status to GH, which leaves pull-requests dangling in la-la-land and requiring big red button overrides to merge.

Apologies for the inconvenience, we really need to get our CI functional again ASAP.

**Comment by dmnks** [comment]
OK, turns out the culprit was the recent permission cleanup in the rpm-software-management GH organization where the original "owner" of the API token for the RPM project on SemaphoreCI was removed which confused the system and broke the linkage to the GH repo, causing the CI to not report back the results.

I fixed this by creating a new project (with the same configuration) and linking it with this repo, see test PR #2187. I've kept the original project in place, just in case (it also contains the history & logs of all the past builds) but disabled it, we may want to remove it later.

**Comment by pmatilai** [comment]
Oops :laughing: 

It's a good thing though, we can't very well have inactive people holding something as vital as the keys to our CI.

**Comment by pmatilai** [comment]
Hmm, looking into this a bit, it seems that we should be connecting to Semaphore through a GH app, rather than oauth which is tied to individual users.

**Comment by pmatilai** [comment]
...except that doing that probably requires removing the oauth setup first. Not going to mess with that now.

**Comment by dmnks** [comment]
Turns out this isn't a complete remedy, the existing PRs would *all* have to be recreated since the new CI project isn't taking on existing PR branches... We're investigating further, I'll reopen the issue to indicate that.

**Comment by dmnks** [comment]
OK, the original CI project is now re-linked properly, it seems (the fix was rather trivial: just "change" the repository to the same, that re-creates the tokens etc.), so all the existing PRs should now work when re-pushed :trophy:

**Comment by dmnks** [comment]
Nor is it possible to select the auth method when creating a new project, from what I've seen...

**Comment by dmnks** [comment]
Anyway, the outage is now over I believe, so let's keep on rolling.

**Comment by pmatilai** [comment]
Cool, thanks!
