### ISSUE TITLE
Macro arguments do not support quoting

### ISSUE THREAD

**Issue by pmatilai** [rpm-software-management/rpm#222]
Originally came up while discussing #217:
Especially now that rpm is expanding macro arguments, it needs a way to quote the arguments to handle whitespace, empty arguments etc.

This matches what shell does when undefined arguments are passed to functions:
```
rpm --define "%foo() 1:%1 2:%2" --eval "%foo %nil bar"
1:bar 2:%2
```

In some cases that's exactly what's wanted, in some cases it absolutely is not - what the shell has and we don't is a way to quote the arguments to preserve empty ones etc. We need that too, and I think this is a blocker for 4.14 release.

Teaching argvSplitString() to handle quotes (optimally when a flag is enabled to preserve compatibility) would serve various other places too. And if there's a way to quote, there needs to be a way to escape those quotes to pass literal quotes.

**Comment by ignatenkobrain** [comment]
```
[brain@ignatenko-w541 kojilogs]$ ~/Projects/upstream/rpm/rpm --define "%foo() 1:%1 2:%2" --eval "%foo %nil bar"
1:bar 2:%2
```

**Comment by pmatilai** [comment]
@ignatenkobrain, that's the unquoted case. What we're interested about here is:

```
rpm --define "%foo() 1:%1 2:%2" --eval "%foo '%nil' bar"
```
...which should return "1: 2:bar". This is not resolved yet, the patches were reverted in commit fe7cf85bff534f97025ef1701deaa209a485004e as it wasn't ready yet. Reopening.

**Comment by ignatenkobrain** [comment]
@pmatilai ohhh, sorry then

**Comment by pmatilai** [comment]
Implemented in commit 47f0a899eff78230d2b9a00d23474845579d1582, thanks Pavlina.

**Comment by pmatilai** [comment]
So... this is not going to fly, too many macros rely on quotes passing untouched (and why shouldn't they, that's the way its been all this time). We'll need some other kind of solution that's opt-in one way or the other. Reopening.

**Comment by pmatilai** [comment]
@mlschroe and others too of course: ideas welcome...

**Comment by pmatilai** [comment]
Examples of stuff that broke:
https://bugzilla.redhat.com/show_bug.cgi?id=1481025
https://bugzilla.redhat.com/show_bug.cgi?id=1481133

**Comment by n3npq** [comment]
Leave bad enough alone imho.

Every macro templating language in the world has quoting problems: its the nature of the beast.

And a Principle of Least Surprise "Do what bash does!" sets expectations that are wildly out of line with reality.

FWIW, the only place that macros MUST be used (instead of bash/lua/etc) is in the preamble and in %files. Use whatever language you wish to program in, and use macros for tempting, not programming.

RPM macros are a gawd awful way to attempt to solve programming issues ...

**Comment by proyvind** [comment]
Lack of quoting support was actually what made me put the python interpreter support implemented @rpm5.org to use, which in turn made templating a shitload easier with a language which supports overloading of parameters, OOP etc.
Lack of support for such in lua (combined with not exactly widespread knowledge of the language amongst packagers) is why it's not suitable for the task, hence #190 (which again makes templating fully possible for whatever plugin that implements the rpminterp.h api, that can be implemented and maintained by third parties for ie. turning existing package/spec generators into superiour single line spec files requiring minimal package maintenance)</shamelessfeaturelobbying>;)

**Comment by pmatilai** [comment]
Since there are no nice quote characters left, implemented with the help of a special %{quote:...} macro. It might not be the prettiest solution in existence but at least it makes it *possible* to quote the arguments without stepping on any existing uses I'd hope.

**Comment by jnpkrn** [comment]
Looks like a perfect timing regarding discovery and fixing
of silent issues in one of my specfiles:

```
%py_byte_compile '%{__python3} \-I' '%{buildroot}%{_datarootdir}/%{name}/ext-plugins'
```

Why nobody told me that quotes are taken literally and only spaces/tabs
play the role in word/argument splitting, nor any warning/error about
argument number mismatch was raised?!  As you can, see, I was already
forced to escape the dash, which was originally indicating this true
reality, but I managed to silence it by force :-)

Luckily, the problem was exposed recently thanks to this change:
https://src.fedoraproject.org/rpms/python-rpm-macros/c/05333eb5866a865282e37ad4d8d24f0b2b6cabb1?branch=master#diff-file-1
and thanks to `%1` not being escaped at line 18, which resulted in an
invalid bash syntax (``unexpected EOF while looking for matching `''``)
because of:

```
python_version=$('/usr/bin/python3 -c "import sys; ...
```

So I figure `%{quote:...}` is likely the proper solution here,
thanks for that!

However!
Is there any trick that would make using that construct at least
partially compatible with older rpm versions, e.g. conditionalizing
its usage somehow?  If not, I'd strongly suggest it'd be considered
prior to `rpm-4.14.2-release` so that mutual compatibility can be
achieved (in my case, for instance, it would be using merely python
path without additional switches when explicit quoting not supported)!

**Comment by n3npq** [comment]
RPM macros are context free: expanded within quotes, within comments, everywhere a % is found.

Always been that way.

**Comment by n3npq** [comment]
There are 2 issues that would need to be solved if you wish portability within versions of rpm macro expansion:

* adding -I to the Python interpreter in use
* handling a possible space in the file name

There are means to solve both of those issues by not using parameterized macros (because it's unclear whether -I is a parameterized macro or a Python option) and by elimininating the usage of position sensitive %1 (by expanding within single quotes before executing Python).

YMMV, everyone's does. Retrofitting macro context within single quotes (or the very ugly %{quote: ...}, or changing behavior to expand arguments before passing to a parameterized macro, is almost certainly going to have a legacy code behavior debt that cannot be solved adequately.

**Comment by n3npq** [comment]
(after looking at recent changes to macro expansion)

Parameterized macros use posix getopt(3) for parsing macro options/arguments, and getopt is perfectly capable of honoring quoting similar to bash.

Sadly the implementation in rpm does not use getopt argv but attempts its own parser in order to expand each macro argument individually, honoring not only quoting, but also %(...) diversions, %{...} macro scoping, and (most painful of all to get right for positional args) empty arguments that expand to "".

The parser in rpmio/macro.c needs fixing to handle quoting (without the ugly %{quote: ...} construct), as well as the possibility that a single parameterized macro argument may lead to multiple arguments to pass to getopt(3) some of which may need quoting (because empty or having white space embedded) before being executed.

**Comment by n3npq** [comment]
(after looking at recent changes to macro expansion)

Parameterized macros use posix getopt(3) for parsing macro options/arguments, and getopt is perfectly capable of honoring quoting similar to bash.

Sadly the implementation in rpm does not use getopt argv but attempts its own parser in order to expand each macro argument individually, honoring not only quoting, but also %(...) diversions, %{...} macro scoping, and (most painful of all to get right for positional args) empty arguments that expand to "".

The parser in rpmio/macro.c needs fixing to handle quoting (without the ugly %{quote: ...} construct), as well as the possibility that a single parameterized macro argument may lead to multiple arguments to pass to getopt(3) some of which may need quoting (because empty or having white space embedded) before being executed.

**Comment by n3npq** [comment]
(after looking at recent changes to macro expansion)

Parameterized macros use posix getopt(3) for parsing macro options/arguments, and getopt is perfectly capable of honoring quoting similar to bash.

Sadly the implementation in rpm does not use getopt argv but attempts its own parser in order to expand each macro argument individually, honoring not only quoting, but also %(...) diversions, %{...} macro scoping, and (most painful of all to get right for positional args) empty arguments that expand to "".

The parser in rpmio/macro.c needs fixing to handle quoting (without the ugly %{quote: ...} construct), as well as the possibility that a single parameterized macro argument may lead to multiple arguments to pass to getopt(3) some of which may need quoting (because empty or having white space embedded) before being executed.
