### ISSUE TITLE
libmagic detection relies on downstream pkg-config patches

### ISSUE THREAD

**Issue by andrewzah** [rpm-software-management/rpm#2246]
Hi all, I'm trying to build this on centos 8stream.

Firstly, the deps:
```
# dnf -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
# dnf config-manager --set-enabled powertools
# yum install -y \
  autoconf \
  automake \
  cmake \
  bzip2 \
  file-devel \
  file-libs \
  gcc \
  gettext-devel \
  git \
  gzip \
  gnupg2 \
  libarchive-devel \
  libgcrypt-devel \
  libsqlite3x-devel \
  libtool \
  lua-devel \
  make \
  popt-devel \
  tar \
  xz \
  zlib-devel \
  xz-devel \
  bzip2-devel

```

`file-devel` and `file-libs` are installed, but I get this error:
```
[root@ea7c2cfd7893 _build]# cmake ..
-- Checking for module 'libmagic'
--   Package 'libmagic', required by 'virtual:world', not found
CMake Error at /usr/share/cmake/Modules/FindPkgConfig.cmake:556 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPkgConfig.cmake:778 (_pkg_check_modules_internal)
  CMakeLists.txt:120 (pkg_check_modules)


-- Configuring incomplete, errors occurred!
See also "/tmp/rpm/_build/CMakeFiles/CMakeOutput.log".
```

**Comment by pmatilai** [comment]
Right, the autotools build didn't rely on pkg-config for libmagic, now we do, out of sheer short-term convenience rather than being a carefully considered decision.  Buildability on RHEL 8 is not a requirement at this point, but apparently upstream libmagic pkg-config file appeared in file >= 5.39 from 2020, which is a bit on the new side for rpm to require.

Thanks for reporting, we'll consider this.

**Comment by pmatilai** [comment]
The log shows the failures are mainly due to missing fakechroot, without which the test-suite shouldn't execute at all. There was test on that but it was broken (doh), fixed since a couple of days ago.

**Comment by andrewzah** [comment]
installed fakechroot, which now has most tests passing: [rpmtests.log](https://github.com/rpm-software-management/rpm/files/9953028/rpmtests.log)

**Comment by pmatilai** [comment]
One of the failures is due to missing "cpio" utility in the environment, add that to the yum install to fix.

The others are a bit strange:
> +/usr/bin/python3.6: symbol lookup error: /usr/local/lib64/rpm-plugins/dbus_announce.so: undefined symbol: rcalloc

It does point out a difference to the autotools build: we're not explicitly linking plugins to rpm libraries. But there also shouldn't be any need: these are plugins, and the missing symbols are supposed to be provided by the program that is running.
