### ISSUE TITLE
Using %{undefined} in expression breaks argument parsing for macros

### ISSUE THREAD

**Issue by hroncok** [rpm-software-management/rpm#2354]
This is a followup from https://bugzilla.redhat.com/show_bug.cgi?id=2160716

It appears that when `%{undefined ...}` or `%{defined ...}`  is used in an expression in a macro definition, it breaks parsing of options.

See e.g.

```
$ rpm --define '%xxx(r) %[ %{undefined yyy} ? "" : "" ]%{-r:the -r option was set}%{!-r:the -r option was not set}' --eval '%xxx -r'
the -r option was not set
```

Using `%{expr: }` instead of `%[ ]` works.

```
$ rpm --define '%xxx(r) %{expr:%{undefined yyy} ? "" : ""}%{-r:the -r option was set}%{!-r:the -r option was not set}' --eval '%xxx -r'
the -r option was set
```

While I understand `%[ ]` and `%{expr: }` behave differently, I don't understand why parsing of macro options should be affected this way. I reckon it is a bug.

-----

The %undefine/%define macros are:

https://github.com/rpm-software-management/rpm/blob/ccfca4146d3c0c7ac3a3be37b3ea501620954d2f/macros.in#L80-L81

------

This is RPM 4.18.0.

**Comment by mlschroe** [comment]
What's happening is that the macro expansion happening in the expression code pops the macro arguments, because the macro level is not correct. We had this problem with lua as well. See commit 1767bc4fd82bfacee622e698f9f0ae42c02126fa.

A fix would be to change the doExpressionExpansion code to save/restore the level/depth like with lua, i.e.:
```
    rpmMacroContext mc = mb->mc;
    int odepth = mc->depth;
    int olevel = mc->level;
    mc->depth = mb->depth;
    mc->level = mb->level;
    result = rpmExprStrFlags(buf, RPMEXPR_EXPAND);
    mc->depth = odepth;
    mc->level = olevel;

```

Panu, do you think this is the correct fix?

**Comment by pmatilai** [comment]
Oh, *that*. Rings a bell indeed, so presumably the same fix works there too.
