### ISSUE TITLE
Macro %-x modifies original flag if argument follows without intervening space

### ISSUE THREAD

**Issue by rhabacker** [rpm-software-management/rpm#2454]
See the following example:
```
$rpm --version
RPM version 4.14.3

$ rpm --define '%foo(b:) %{-b}' --eval '%foo -b2'
-b 2
```
The macro adds a space between flag and argument, which may affect passing to applications as shown by the following example:

```
$ python3 -bb
Python 3.6.15 (default, Sep 23 2021, 15:41:43) [GCC] on linux
Type "help", "copyright", "credits" or "license" for more information.
<CTRL-D>
``` 
Passing the option through a rpm macro returns: 
```
$ rpm --define '%foo(b:) python3 %{-b}' --eval '%foo -bb` 
python3 -b b
```
Running the generated command fails: 
```
$`rpm --define '%foo(b:) python3 %{-b}' --eval '%foo -bb'` 
python3: can't open file 'b': [Errno 2] No such file or directory
```

**Comment by ffesti** [comment]
See #2455

**Comment by pmatilai** [comment]
Looking again at case and the PR, I do think the rpm behavior to enforce a uniform output for %x is intentional and sane. The macro arguments exist for *modifying macro behavior*, not for passing through to other programs, and we can't allow external program requirements to set the rules for rpm macros. 

If you do pass an option through to some other program, it's the macros responsibility to handle any conversion needed.

**Comment by pmatilai** [comment]
Discussed this with the team to the same conclusion, closing.

**Comment by pmatilai** [comment]
Perhaps more to the point: rpm macros accept flag arguments with or without an intervening space. If we accepted a change to this, that would no longer be true: some macro may then require the caller to supply arguments in a certain way just because it's passed through to some other program, but the caller has no way to know that. That's why it is, and must be, the responsibility of the macro writer to handle argument passdown to other programs.
