### ISSUE TITLE
Ensure %clean always succeeds

### ISSUE THREAD

**Issue by praiskup** [rpm-software-management/rpm#2519]
Could the default %clean script automatically change the mode of directories
before doing `rm -rf`?  To avoid build failures caused by unsuccessful `rm` calls:

```
$ mkdir nonremovable
$ touch nonremovable/protect-parent
$ chmod a-r nonremovable
$ rm -rf nonremovable/
rm: cannot remove 'nonremovable/': Permission denied
```

Note this problem can cause problems Mock/Copr: See also https://github.com/rpm-software-management/mock/issues/1081

**Comment by pmatilai** [comment]
Yeah, rpm itself suffers from this too. Both from the POV that rpmbuild may leave cruft behind (which does look like a bug when you look at it that way), but also when building rpm itself the test-suite can be non-removable afterwards.

**Comment by dmnks** [comment]
FTR, CMake does something similar on `make clean` as I discovered the other day. As for the test-suite artifacts, we already do exactly [that](https://github.com/rpm-software-management/rpm/blob/ea19571b86ff1f828efc264744715b69e30d6832/tests/mktree.fedora#L82). It just seems natural to have `%clean` follow suit...

**Comment by pmatilai** [comment]
Another case where we'll run into this is if/when we add support for vpath builds in read-only tree (#2985). 

The default a macro now, making this kind of thing easy.

**Comment by pmatilai** [comment]
Actually the whole %clean thing is redundant since 9d35c8df497534e1fbd806a4dc78802bcf35d7cb because everything is under that one directory and we need to be able to nuke it, no matter what.

Fixing this would be a one-liner to build.c:
```
     if (what == RPMBUILD_RMBUILD) {
+       fprintf(fp, "chmod -R u+w '%s'\n", spec->buildDir);
        fprintf(fp, "rm -rf '%s'\n", spec->buildDir);
```

...but because %clean is still trying to do its own thing of removing the buildroot, it fails before it gets to %rmbuild, which would handle it. Doh. I'll need a fresher head to think if there's still a case for that separate %clean or should we just flush it...
