### ISSUE TITLE
Macros before 'BuildArch' statement are expanded twice

### ISSUE THREAD

**Issue by AndreySV** [rpm-software-management/rpm#2545]
Simple test spec
```
# Uncomment following line to have single macro expansion
# BuildArch: noarch
%global custom_cmds %{?custom_cmds} echo 'Custom Prep1'
%global custom_cmds %{?custom_cmds} echo 'Custom Prep2'

Summary: Test example
Name: double-macro
Version: 1.0
Release: 1
# Uncomment following line to have double macro expansion
BuildArch: noarch
License: GPLv3+

%description 
Test example to show double macro expansion

%build
%{?custom_cmds}
```
rpmbuild output:
```
$ rpmbuild -bc rpm/test.spec 
Executing(%build): /bin/sh -e /var/tmp/rpm-tmp.IrvpKm
+ umask 022
+ cd /home/andrey/rpmbuild/BUILD
+ echo Custom Prep1 echo Custom Prep2 echo Custom Prep1 echo Custom Prep2
Custom Prep1 echo Custom Prep2 echo Custom Prep1 echo Custom Prep2
+ RPM_EC=0
+ jobs -p
+ exit 0
```

If BuildArch is moved before custom_cmds macro, then macros are expanded only once. Value of 'BuildArch' doesn't matter, it can be any valid value (noarch, i586, ...).

```
rpm --version
RPM version 4.18.0
```

**Comment by pmatilai** [comment]
Yes, this issue is as old as rpm macro, it happens because the spec parse recurses at BuildArch. There's no easy way to fix that, so you get to work around it in specs.

For one, avoid unnecessary use of %global. Despite what certain distro packaging guidelines say, using %global for everything is not a good idea.

While we can't really fix this, it should be documented at least...
