### ISSUE TITLE
RPM DB query creates DB directory and files

### ISSUE THREAD

**Issue by sshedi** [rpm-software-management/rpm#2572]
If a query is run specifying a non existent dbpath, rpm implictly creates a db directory and db files at the specified location.

For example:
```
mkdir t
cd t
rpm -q rpm --dbpath $PWD/t
```

The above commands result in:
```
root@ph5dev:~ # mkdir t
mkdir: created directory 't'
root@ph5dev:~ # cd t
/root/t
root@ph5dev:~/t # rpm -q rpm --dbpath $PWD/t
package rpm is not installed
root@ph5dev:~/t # ls
t
root@ph5dev:~/t # ls t
rpmdb.sqlite  rpmdb.sqlite-shm  rpmdb.sqlite-wal
root@ph5dev:~/t # realpath t/*
/root/t/t/rpmdb.sqlite
/root/t/t/rpmdb.sqlite-shm
/root/t/t/rpmdb.sqlite-wal
```

And:
```
rpm -q rpm --dbpath /tmp
```
The above command creates sqlite.* files under /tmp

RPM Version:
```
root@ph5dev:~ # rpm --version
RPM version 4.18.0
```

Is this a feature or an intended behavior?

IMO, query commands should query the db and error out if the directory doesn't exist or DB doesn't exist inside the specified directory with a proper error message. Thanks.

**Comment by pmatilai** [comment]
It's a long-standing behavior that at some point was clearly intentional, but one we'd like to get rid of  (see commit afbc2b07839c9ffe9f274f3a4bc2395c76d65472). Eventually. Because we had to revert that change: 4d04e84ac4421bc3d9c2f9572a10c7980ff8d43f.

So for the foreseeable future it's a behavior we'll just need to live with. One way to work around it is to run queries as a non-privileged user who *cannot* create the database.

**Comment by sshedi** [comment]
Thanks @pmatilai.
