### ISSUE TITLE
Wrong version comparison

### ISSUE THREAD

**Issue by mattiaverga** [rpm-software-management/rpm#2574]
Trying to compare two package versions with snapshot information produces wrong comparison:
```
$ rpmdev-vercmp 1.7.0~202307168f43b0b 1.7.0~20230709062d5b2
1.7.0~202307168f43b0b < 1.7.0~20230709062d5b2
```
The first has `~20230716...` so it should evaluate higher than `~20230709`.

The version comparison seems to fail because the second hash digit is a letter and not a number:
```
$ rpmdev-vercmp 1.7.0~202307168 1.7.0~202307090
1.7.0~202307168 > 1.7.0~202307090

$ rpmdev-vercmp 1.7.0~202307168f 1.7.0~2023070906
1.7.0~202307168f < 1.7.0~2023070906

$ rpmdev-vercmp 1.7.0~202307168f 1.7.0~2023070906
1.7.0~2023071681 > 1.7.0~2023070906
```

**Comment by decathorpe** [comment]
originally filed here:
https://pagure.io/rpmdevtools/issue/113

As I said in that ticket, I don't think this is a bug. It's a result of concatenating date + commit hash without separator character - hexadecimal commit hashes start with different number of decimal digits - so even a number that should sort lower lexicographically will sort higher just because the number parsed from the string has more digits.

**Comment by mattiaverga** [comment]
I may well be the intended behavior, but my opinion is that it is really confusing.
For example,
```
$ rpmdev-vercmp 1.7.0a 1.7.0b
1.7.0a < 1.7.0b
```
is quite understandable, as it is evaluated as `rpmdev-vercmp 1.7.0.a 1.7.0.b`, but 
```
$ rpmdev-vercmp 1.7.0.1a 1.7.0.ab
1.7.0.1a > 1.7.0.ab
```
it's not because RPM evaluates that as `rpmdev-vercmp 1.7.0.1.a 1.7.0.0.ab`, which is not what any user would think.

**Comment by ffesti** [comment]
Life is confusing and RPM reflects that. There is no bug here and we are not changing the version comparison breaking thousands of packages.
