### ISSUE TITLE
Wrong line reported on %filetriggerin parse error

### ISSUE THREAD

**Issue by davide125** [rpm-software-management/rpm#2584]
I'm hitting build failures for asahi-scripts in Rawhide, while it works fine on f38:

```
error: line 100: Dependency tokens must begin with alpha-numeric, '_' or '/': %transfiletriggerin -n update-m1n1 -- /usr/lib64/m1n1 /usr/share/uboot/apple_m1 /boot/dtb/apple
```

https://src.fedoraproject.org/rpms/asahi-scripts/blob/rawhide/f/asahi-scripts.spec is the spec. See https://koji.fedoraproject.org/koji/taskinfo?taskID=103911043 for a build failure example in Koji.

**Comment by pmatilai** [comment]
I see you found and fixed the issue in https://src.fedoraproject.org/rpms/asahi-scripts/c/3b58fb7eaa651161c345cc320a1c2f0d4a4682b9?branch=rawhide already, but to clarify to others:

The actual error was %{python3_sitearch} being unexpanded in the %filetriggerin line. Apparently in F39, the definition of that macro has either moved, or the package is no longer being pulled into the buildroot with this set of dependencies, which causes the previously working spec to fail there. That's not due to anything changing in rpm.

So, this is actually rpm finding a packaging bug where an unexpanded macro is used in a dependency name. But, the reported line number and message itself is on the wrong line :facepalm: thus being very misleading and making it hard to see the real issue. That is a bug worth fixing, so thanks for reporting even if it was a bit different than you probably thought.

**Comment by pmatilai** [comment]
Here's a minimal reproducer:

```
Name: badline
Version: 1.0
Release: 1
Summary: Testing error reporting
License: GPL
BuildArch: noarch

%transfiletriggerin -- /something %{nosuchmacro}
echo bad

%files
```

rpmspec/rpmbuild fails on this with "error: line 11: Dependency tokens must begin with alpha-numeric, '_' or '/': %files" which is obviously wrong. If one removes /something so the undefined macro happens first, you get a much better error: "error: line 11: file trigger condition must begin with '/': %{nosuchmacro}". The line number is still wrong on that too, but it's pretty trivial to see what the issue is.
