### ISSUE TITLE
rpmbuild: default to LANG=C.utf8 ?

### ISSUE THREAD

**Issue by juhp** [rpm-software-management/rpm#2587]
It is not unusual for software to require UTF-8 encoding to build these days.

It seems rpmbuild still defaults to LANG=C nowadays.
I think most platforms support LANG=C.UTF-8 now, so could the default be changed?
At least for platforms like Linux where it is available?

For example I think mock already defaults to C.utf8 for quite some time.

**Comment by Conan-Kudo** [comment]
For what it's worth, I think we should _at least_ consider making a build flag to switch RPM to use `C.UTF-8` instead of `C`, and make our CMake default to it for Linux.

From my research, it seems that Darwin/macOS does the "interesting" thing of overlaying UTF-8 support to the C locale by doing the following combination: `LANG=C` + `LC_CTYPE=UTF-8`. It's not _wrong_, but I don't think anyone else does it.

FreeBSD has had a `C.UTF-8` locale for a while, but with FreeBSD 13, it is now the default: https://github.com/freebsd/freebsd-src/commit/09ef995baf45333d45ab214daf8c03e1a25f8fcc

OpenBSD has supported `C.UTF-8` in some form for at least ten years, and NetBSD's `C` locale is UTF-8 aware (and `C.UTF-8` is an alias to `C` there).

So at least at this point, the only odd duck is macOS.

**Comment by gotmax23** [comment]
The current rpm version doesn't build on MacOS to begin with according to https://github.com/rpm-software-management/rpm/issues/2222, so I don't think that should be a consideration here.

**Comment by Conan-Kudo** [comment]
We shouldn't make the problem worse, and there are plenty of people using RPM on macOS for various reasons. We will have support for it one way or another.

**Comment by keszybz** [comment]
Please default to `C.UTF-8`, this is generally correct setting. An option can be provided to override for the fringe cases that need it.

**Comment by juhp** [comment]
Thank you, great news!
