### ISSUE TITLE
rpm core in rpm.daily

### ISSUE THREAD

**Issue by JetXujing** [rpm-software-management/rpm#2612]
In the following scenario, a core dump occurs on the rpm command in the rpm.Daily file.
For example, if I want to upgrade rpm-4.15.rpm to rpm-4.17.rpm, this will cause rpm-libs-4.15.rpm to upgrade to rpm-libs-4.17.rpm. After the rpm upgrade and before the rpm-libs upgrade, if a crontab task is triggered and the rpm.daily script is executed during this period, the rpm command is 4.17 and the related .so file is 4.15. As a result, a core dump occurs.

**Comment by pmatilai** [comment]
Yes, the system as a whole cannot be considered working normally during (major) upgrades.

I don't remember offhand whether there was a soname bump between those versions but it doesn't take anything more exotic than that. Berkeley DB (which still was the default in 4.15) has it's own notorious quirks between versions, but degraded to read-only support (if built in at all) in 4.17 so that's not going to work in any case without arranging for some kind of rpmdb migration.

It's the responsibility of distro maker to run major upgrades in a suitably isolated environment and arrange any database migrations etc as necessary.
