### ISSUE TITLE
RPM signature verification for files from installed packages

### ISSUE THREAD

**Issue by birdie-github** [rpm-software-management/rpm#2671]
Let's talk about a major security issue which I think is very important, yet is not currently solved in any shape or form.

RPM packages can be signed, and Fedora and RHEL packages are.

The issue however is neither Fedora, nor RHEL keeps intermediate update packages on the server, so it's quite a common configuration to have packages are installed where the source Fedora/RHEL packages cannot be downloaded or found anywhere on the Internet since they have been deprecated and replaced with newer updates.

This results in an ability to verify the integrity of the installed files and whether they have been tampered with because it's relatively easy to modify `rpmdb.sqlite` to make it look like files on the disk are pristine and the system is running normally without any malware, etc.

Here's my proposal how to fix this issue.

We sign the metadata of the RPM file separately (i.e. the package description, filenames, timestamps, permissions, scripts, etc) and upon installation the metadata gets stored somewhere, even in `rpmdb.sqlite`.

Then it becomes trivial to verify whether your system still runs signed packages even when their source binaries have long been lost/deprecated/whatever.

Of course this can be "solved" by enabling `keepcache` but it comes with its drawbacks, i.e. the need to keep stale unneeded update files (i.e. the kernel package in Fedora is updated almost every week, so we are talking about 52 kernel packages every year which is a ton of space).

**Comment by Conan-Kudo** [comment]
> The issue however is neither Fedora, nor RHEL keeps intermediate update packages on the server, so it's quite a common configuration to have packages are installed where the source Fedora/RHEL packages cannot be downloaded or found anywhere on the Internet since they have been deprecated and replaced with newer updates.

Two things:

1. RHEL does keep intermediate packages published forever. RHEL derivatives may not necessarily do that, though.
2. Fedora has a huge archive repo that is not shipped/enabled by default that keeps all shipped updates for a release. If you install the `fedora-repos-archive` package, you'll get the updates archive. It's used by Fedora CoreOS primarily, but it's available to any Fedora user to use optionally.

That said, the problem you describe is potentially worth solving regardless.

**Comment by pmatilai** [comment]
> This results in an ability to verify the integrity of the installed files and whether they have been tampered with because it's relatively easy to modify `rpmdb.sqlite` to make it look like files on the disk are pristine and the system is running normally without any malware, etc.

I don't think you've actually tried that. 

> Here's my proposal how to fix this issue.
> 
> We sign the metadata of the RPM file separately (i.e. the package description, filenames, timestamps, permissions, scripts, etc) and upon installation the metadata gets stored somewhere, even in `rpmdb.sqlite`.

You know, this (header-only signatures) was *the* major feature of rpm v4 format in 2000 :sweat_smile:  
That's right, almost a quarter century ago, and years before my time. Rpm v3 signatures covered both the header and the payload and thus wasn't verifiable after installation, v4 added header-only signatures (and digests) for this very purpose, and that has been in action ever since. Few people ever notice.

If you look at 'rpm -qavv' output, you'll see rpm checking digests and signatures of each package processed. Any failed check will result in loud complaints. By default this happens on each and every rpmdb access you do, including of course 'rpm -Va' . 

The gotcha is that it's possible to effectively *delete* a signature of an installed package, and then adjust a digest to match a modification of the header. There's #811 for that, but if you have sufficient permissions (root) to manipulate the rpmdb at will, then you also have sufficient permissions to disable the enforcing signature checking in configuration. Protecting against a rogue root is tough.

**Comment by birdie-github** [comment]
Wow, there's a ton of things I've never known about even though I've been an avid user of `rpm -V`. Thank you very much for the information!

I've just double checked `man rpm` and nothing that you've written is there, so please forgive me for this intrusion.

@pmatilai 

My final question is what's the command to see the following information for all the installed RPMs:

1) Whether the package is signed or not
2) The key which is used to sign it
3) Whether the signature verification passes.

You've mentioned `rpm -qavv` but it's impossible to parse as a human being. I'd like to see something like,
```
acl-2.3.1-6.fc38.x86_64: Signed. Signature: OK. Key ID eb10b464.
acpid-2.0.34-2.fc38.x86_64: Signed. Signature: OK. Key ID eb10b464.
```

Or something similar.

**Comment by pmatilai** [comment]
Yeah both the documentation and the integration with the rest of rpm for that major feature is tragically inadequate. The technical side of the format change was covered in https://rpm-software-management.github.io/rpm/manual/hregions.html back then, but there's never been any UI to this feature - basically do the equivalent of 'rpmkeys -K(v) *.rpm' on the database. I see that as a part of #811 because this is all about verifying really.
