### ISSUE TITLE
RFE: file trigger scriptlet arguments

### ISSUE THREAD

**Issue by pmatilai** [rpm-software-management/rpm#2755]
Splitting this from #2655 as this is a clearly separate thing that should be doable without massive redesign of the whole thing:

- First argument should reflect the triggered package count
- Non-trans scriptlets have should get a second argument reflecting the triggering package count

**Comment by dmnks** [comment]
>     * Non-trans scriptlets have should get a second argument reflecting the triggering package count

I wonder if we want the triggering package count (`arg2`) to be an *aggregate* count of all the triggering packages or just that of the *first* match?

There's a subtle difference in the semantics between regular triggers and file triggers in the way they are fired. A regular trigger can only ever be triggered by *one* package (e.g. `%triggerin -- foo, bar, baz` means "fire if any of these packages is installed"), whereas a file trigger can be triggered by *multiple* packages (e.g. `%filetriggerin -- /etc/foo.d` means "fire if any file with such a prefix is installed, regardless of which package it belongs to").

In both cases, the trigger only executes once, however the semantics of "which package triggered it" differs. Therefore, for regular triggers, `arg2` is straightforward (it's always the one triggering package), however for file triggers, it's not.

As an example, consider the following scenario:

```
# bar.spec:
%filetriggerin -- /etc/foo.d

# foo.spec:
%files
/etc/foo.d/foo.conf

# baz.spec:
%files
/etc/foo.d/baz.conf
```

If `bar` is installed first, installing `foo` or `baz` afterwards results in the trigger being run once for *each* of those, so the triggering count (`arg2`) is straighforward (same as with regular triggers).

However, if `foo` *and* `baz` are installed first, installing `bar` afterwards results in the trigger being run once for *both* of those (with both filenames served via stdin), so the trigerring count (`arg2`) is now ambiguous - it can either be the count of `foo` *or* `baz`, or it can be the sum of both.

My take: The count should be an aggregate since that enables a file trigger script to detect when *all* the files subject to the prefix are being removed (which is one of the purposes of the arguments in the first place).

Any thoughts?

**Comment by dmnks** [comment]
Thanks, the part about usefulness is actually on point :smile: That said, I haven't given it too much thought either, this is just the most obvious solution that comes to mind. I'll ponder about it a bit more but there's probably not much to ponder about anyway.

**Comment by pmatilai** [comment]
The thing to ponder about is whether there are other arguments that should be passed in addition or in stead of these. The only "vision" or "design" behind this ticket description is "something close enough to other scriptlets that someone familiar with should feel at home". Which may leave some room for improvement from a more technical perspective :laughing:

**Comment by dmnks** [comment]
Good point! We shouldn't just blindly copy what the normal triggers do here. There's enough difference that it makes sense to step back for a moment and think about what functionality and use cases we really want to cover. Thanks, I'll take that into account :smile:

**Comment by dmnks** [comment]
Note that there's no technical reason for *not* adding the second argument (the number of triggering packages) to transaction scriplets here, too. It's the same code path underneath.

Whether it's useful or not is another question but I'll probably lean towards consistency here and include it.

**Comment by dmnks** [comment]
As for arg2 and the question of "should it be an aggregate count?", I've come to realize that it actually should **not** be an aggregate since that would prevent the script from detecting a package upgrade. It would also be inconsistent with regular triggers. Hence, no aggregate count in #2883.
