### ISSUE TITLE
Support for 'm' in sysusers file?

### ISSUE THREAD

**Issue by mlschroe** [rpm-software-management/rpm#2816]
Does it make sense to add support for 'm' lines in sysusers config files? This would mean the following changes:

- add a provides for every `m` line, e.g. "group-member(groupname) = base64_line"
- feed all such provides to systemd_sysusers tool (after all the user/group lines)

The sysusers.sh scripts already has support for 'm' lines.

**Comment by mlschroe** [comment]
Should the `m` lines generate user()/group() requires?

**Comment by pmatilai** [comment]
Supporting 'm' would be nice of course. It was left out of the initial implementation due to lack of time/energy to think about how to properly implement it, rather than a "never" decision.

The implicit user/group creation is indeed something that would cause problems when an explicit entry exists, so I think adding hard requires for both the user and the group is needed. Alternatively we'd need some special logic for dependency resolution of these items, where we'd favor a user/group with an EVR over one without it.

**Comment by pmatilai** [comment]
On a related note, we should probably also generate a group require on a case like this:
`u     cyrus    76:mail        "Cyrus IMAP Server"   /var/lib/imap  /sbin/nologin`
