### ISSUE TITLE
Document rpm design philosophy in the manual

### ISSUE THREAD

**Issue by pmatilai** [rpm-software-management/rpm#2897]
Max-rpm has a section on [philosophy](https://ftp.osuosl.org/pub/rpm/max-rpm/ch-rpm-philosophy.html) but it's a source one doesn't really want to link to because it's *soooo* outdated now. We should have a section explaining the fundamental design principles of rpm in our reference manual, many/most people probably don't even realize rpm *has* a philosophy.

This came up indirectly when somebody asked about interactivity in rpm (install) scriptlets. Somehow one of the most important aspects of rpm - the fact that by design all operations are unattended - doesn't seem to be mentioned *anywhere at all*. This is just tribal knowledge, those in the tribe just know, and those outside it, like the average 3rd party commercial vendor who wants to present an EULA for their software at install time... and we can' even point them to any canonical source of information as to why that's a total no-no. Max-rpm mentions unattended builds, but non-interactive installs is just as vitally important.

**Comment by ffesti** [comment]
List of things to talk about:

- Upstream tarball + patches to see what are the packager's changes
- SRPM has all needed to rebuild the package on its "home" distributing - assuming the distribution ships all (devel and tooling) packages
  - nosource as an exception 
- Optimized for updates - especially quick security updates
  - Package name as a line of updates instead of one time packaging (obsoletes as name change or split/merge)
  - Unattended updates
- Handle full life cycle of all owned files - but ignore all other files
- Scriptlets are supported but should be used very sparingly.
  - Most things can be done with file trigger only
    - E.g. register stuff in centralized catalogs, update caches  
  - Do all that can be done during build! Compiling and copying unowned files around is frowned upon!

**Comment by pmatilai** [comment]
Yup, there's a lot of related detail which deserves to be documented, but this must not become a 1000 page packaging guide. My primary goal here is a TLDR version of the higher level principles behind rpm operation, such as pristine sources and unattended operation, that you can point the uninitiated to without totally overwhelming them with the details. The finer details can and should be expanded on in other sections.

**Comment by ffesti** [comment]
I agree, may be just a few sentences per item or may be even only one and the link to the rest of the manual for details.

**Comment by richm** [comment]
I wonder if there are other packages like the Microsoft case where they require an explicit acceptance of a EULA in order to install the package.  Rather than their current solution of requiring an environment variable to be set, or prompting on the terminal, perhaps we can recommend something like this?

> If your package requires some sort of confirmation before installation (for example, the user must accept a EULA before installing the package), then the package can have a `%preinstall` script which looks for a file with specific content.  For example, the package can look for `/etc/$VENDOR/EULA.txt` with the content `yes`.

**Comment by Conan-Kudo** [comment]
There are package management extensions at higher layers that should probably be considered to incorporate into this for stuff like EULAs...
