### ISSUE TITLE
rpmsign --delsign leaves behind 0 padding

### ISSUE THREAD

**Issue by JanZerebecki** [rpm-software-management/rpm#2965]
**Describe the bug**
rpmsign --delsign leaves behind 0 padding, previously similar problem in https://github.com/rpm-software-management/rpm/issues/2382 fixed by https://github.com/rpm-software-management/rpm/pull/2396

**To Reproduce**
1. rebuild locally: osc co openSUSE:Factory scout && cd openSUSE\:Factory/scout/ && osc build --clean -x '' --release 2.1 --build-opt=--disturl=obs://build.opensuse.org/openSUSE:Factory/standard/d2d01ca7d9d5f8c1de2fe35a07f4c223-scout --no-service
2. get remote build result: osc getbinaries openSUSE:Factory scout standard x86_64
3. rpmsign --delsign 2.rpm
4. diffoscope 1.rpm 2.rpm
5. should be no difference, but it seems there is additional 0 padding in rpms from step 2
6. @bmwiedemann tested the same also with Fedora its rpm and rpmsign
7. cp 1.rpm 3.rpm
8. rpmsign --addsign 3.rpm
9. rpmsign --delsign 3.rpm
10. content of 1.rpm and 3.rpm is the same

[tar.gz of 1.rpm and 2.rpm and the one the remote one before deleting the signature](https://github.com/rpm-software-management/rpm/files/14575260/rpms.tar.gz)

**Expected behavior**
rpmsign --delsign does not add different amount of 0 padding

**Environment**
 - OS / Distribution: Fedora, openSUSE Factory, Tumbleweed
 - Version rpm 4.19.1.1

**Additional context**
@bmwiedemann reported this for openSUSE Factory, which is now supposed to be bit reproducible except signature: https://old.reddit.com/r/reproduciblebuilds/comments/1bcz7r2/got_closer_to_reproducible_rpm_builds/

**Comment by pmatilai** [comment]
rpmsign cannot know what the previous reservation (if any) was, so it *cannot guarantee* going back to the former state on --delsign. 

That said, there's something very wonky here, the reserved space doesn't appear to get used at all on signing, although it does reclaim the space from the --delsig. Thanks for reporting!

**Comment by JanZerebecki** [comment]
Bernhard mentioned that the size of the rpm stays the same on --delsign, but should shrink by 1104 bytes. I haven't calculated it myself but the direction of that looks right and a quick read of the code looks like it should be doing that (but I would need look much more careful to identify why it doesn't here).

So it looks to me like it is not reclaiming the space during --delsign. Where or why do we disagree?

It looks to me like the reservation is hard coded. So as long as the rpm that was used to build and the one that was used to --delsign is the same it should be able to guarantee it, right?

When adding a signature locally output size remains the same as the input, with rpm-4.19.1.1-3.1.x86_64 from Tumbleweed, same result with input binary from step 1 and 2.

I think the signing code that produced 2 is from https://github.com/openSUSE/obs-sign , so that might be creating a binary that this projects code can not deal with. And that project also changed. Though with some older version of both projects this worked.

Even if an rpm has too much padding, the intent of the code for --delsign seems to me to fix that by further decreasing the size to what it has hard coded, but fails here.

**Comment by pmatilai** [comment]
> So it looks to me like it is not reclaiming the space during --delsign. Where or why do we disagree?
> 
> It looks to me like the reservation is hard coded. So as long as the rpm that was used to build and the one that was used to --delsign is the same it should be able to guarantee it, right?

Except for a bare minimum, the reservation is macro configurable, so it can be anything at all. And that's why it cannot possibly *guarantee* to restore it. In an arbitrary situation that is.

When the signature fits in the original reservation then it should restore it to original condition though. So like I said, there's something very wonky here. As in, it's a bug or more likely, regression.

**Comment by bmwiedemann** [comment]
After 2022-06-20 we changed to a new rsa4096 signkey for the project.
%__gpg_reserved_space seems to default to 4096 bytes so that should fit. And indeed, rpm --delsign leaves the size as is.

With [this dump-rpm-headers.py](https://gist.github.com/koseki/9737a4490128bcb8b426c22a0b7c3885) I get this diff between our delsigned OBS build and my local build:
```diff
--- dump-rpm-headers.py binaries/strip-nondeterminism-1.13.1-33.11.src.rpm
+++ dump-rpm-headers.py binaries.nachbau/strip-nondeterminism-1.13.1-33.11.src.rpm
@@ -13,15 +13,15 @@
    version: b'\x01'
   reserved: b''
     nindex: 7
-     hsize: 4868
+     hsize: 4276
 ==== Signature Section - Index Entries ====
-[  0] tag:   62  type: BIN          offset:4852  count:  16   # RPMTAG_HEADERSIGNATURES
+[  0] tag:   62  type: BIN          offset:4260  count:  16   # RPMTAG_HEADERSIGNATURES
 [  1] tag:  269  type: STRING       offset:   0  count:   1   # RPMSIGTAG_SHA1
 [  2] tag:  273  type: STRING       offset:  41  count:   1   # Unknown
 [  3] tag: 1000  type: INT32        offset: 108  count:   1   # RPMSIGTAG_SIZE
 [  4] tag: 1004  type: BIN          offset: 112  count:  16   # RPMSIGTAG_MD5
 [  5] tag: 1007  type: INT32        offset: 128  count:   1   # RPMSIGTAG_PAYLOADSIZE
-[  6] tag: 1008  type: BIN          offset: 132  count:4720   # RPMSIGTAG_RESERVEDSPACE
+[  6] tag: 1008  type: BIN          offset: 132  count:4128   # RPMSIGTAG_RESERVEDSPACE
 ==== Signature Section - Data ====
 [  1] RPMSIGTAG_SHA1
 b'34a3e2de398c3a6598b6b4b9d01d9a7fa96fda48'
@@ -42,43 +42,6 @@ RPMSIGTAG_RESERVEDSPACE
 0000 0000 0000 0000 0000 0000 0000 0000 
 0000 0000 0000 0000 0000 0000 0000 0000 
 0000 0000 0000 0000 0000 0000 0000 0000 
-0000*
```

So there is a difference of 592 bytes, which is around the size of a 4096-bit sig.

**Comment by pmatilai** [comment]
Just FWIW, there's now an in-tree tool for looking at low-level package structure:
https://github.com/rpm-software-management/rpm/blob/master/tools/rpmdump.c

**Comment by JanZerebecki** [comment]
Had a very old version of rpm around and this worked, I can confirm it is a regression in rpm.

**Comment by bmwiedemann** [comment]
I think, the problem has 2 components.
1. The obs-sign we use in OBS has its own signing code and adds bytes to the header instead of using the reserved space.
2. The `rpm --delsign` leaves the (increased) size as is, only zeroes it out.

I was able to get bit-identical results to OBS using "--define=%__gpg_reserved_space 4688" in the replication build to add as many header bytes as obs-sign did, but that is certainly not the nicest solution.

**Comment by pmatilai** [comment]
I seem to have missed the last update here:

> The obs-sign we use in OBS has its own signing code and adds bytes to the header instead of using the reserved space.

This is where things go into the weeds. Like I said in an earlier comment, rpm *cannot guarantee* going back to the original state of the package because it has no idea what the reservation size was. It operates by the assumption that the reserved space is used.

>  The rpm --delsign leaves the (increased) size as is, only zeroes it out.

This is by design. Resizing is expensive, so it doesn't make sense to shrink the file on --delsign because we might get signed again and then we might need to an expensive grow, again. And, since we don't know what the original reservation was so we wouldn't know what to resize to even if we wanted to.

So this is not a regression, you should teach the obs-sign thing to take advantage of the reserved space when available, and then it'll play ball with rpmsign --delsign.

Very old rpm does not know about reserved space so it behaves differently. IIRC it was added in 4.13.

**Comment by mlschroe** [comment]
FYI: obs-sign now uses the reserved space. See commit https://github.com/openSUSE/obs-sign/commit/07b30f65ec0185e915b906f4a5cab4f317edc91b

**Comment by pmatilai** [comment]
Nice, thanks for that. It's also a huge performance win especially on large packages.
Note that in v6 packages the reserved space tag will be different (999, to get it out of the normal tag range).

**Comment by mlschroe** [comment]
Yes, I already saw that when I looked at rpm git master to find out the exact implementation of this in rpm. But thanks for the pointer.
