### ISSUE TITLE
RFE: ensure unwritable buildroot during %check

### ISSUE THREAD

**Issue by pmatilai** [rpm-software-management/rpm#3010]
On the heels of the xz incident, one of the ideas (from @keszybz it seems) to harden against malicious tests is to make buildroot readonly during %check.  Picked from https://github.com/rpm-software-management/rpm/discussions/3009 as a clear actionable item.

**Comment by mlschroe** [comment]
There's not much you can do against a malicious upstream.

**Comment by pmatilai** [comment]
I opened this ticket from the discussion specifically because it's such a no-brainer when you see it: "tests should not be able to affect built binaries". How feasible it is in practise is another story, but it's worth at least investigating.

**Comment by xsuchy** [comment]
I opened https://github.com/rpm-software-management/rpm/issues/3015, which I believe will be much easier to implement. And will gain the same benefit.

**Comment by pmatilai** [comment]
Having a separate short-circuit for check is fine, but it's NOT the same benefit! I get that you look at the world through mock lenses, but not everybody does :smile:

**Comment by mikhirev** [comment]
This issue shows misunderstanding of how the xz backdoor was intended to work. Although its payload was hidden in the test files, it was extracted [when running the `./configure` script][cox] that happens at the `%build` stage. If you run tests on read only filesystem or even disable them, that wouldn't prevent the backdoor from being injected. So it is incorrect to speak about malicious tests, all tests worked correctly and did what they were expected to do.

Of course, we can imagine a situation when some backdoor is injected when running tests, and proposed changes could prevent such a situation. However this wouldn't help against the particular backdoor and it definitely won't help against hypothetical future backdoors targeted at rpm systems because their developers will take into account protections you are going to implement. I think, it is only makes sense to implement them if it is easy to do and won't cause additional overhead by copying or hashing numerous files that can be very large in some cases.

[cox]: https://research.swtch.com/xz-script

**Comment by nmanthey** [comment]
I understand the difference between %build and %check, as well as the problem of this could be worked around by future actors. I would still like to understand the potential as a building blocks for hardening.

Do you see a path for a hashing-like validation in the %check phase that could be enabled by an additional run time parameter of the tool? This way, feature is available to potential users, but not enabled by default?

**Comment by mikhirev** [comment]
There are simpler ways to ensure that `%check` stage does not affect files in the build directory. E.g. we could use an overlayed filesystem (overlayfs, aufs etc.) to mount an empty directory on top of the build directory before executing `%check` but use the original build directory for `%install`. This will have much lower overhead than hashing, but this is unportable between different OSes and will add new dependencies. And I still think this does not solve the real issue because altering binaries will remain possible at `%build` and `%install` stages. A completely different approach is required to avoid this.

**Comment by nmanthey** [comment]
Yes, this approach will never be complete. Something like the proposed feature is only a building block. For the other stages, there could also be the requirement to not modify files that have been available already. IMHO, other attack vectors should be addressed with other tools.

What data would you need to be more willing to accept a PR the implements the requested idea? While the hashing approach might be more IO heavy, it seems like a portable solution. Furthermore, this approach does not require extra permissions for additional jailing.

**Comment by pmatilai** [comment]
This is not about "preventing XZ", it's just somewhat inspired by it. 
I really don't know why multiple people are arguing against rpm looking to do some extra packaging hygiene enforcement here. In a similar vein, rpm would prefer an unwritable build directory during %install.

Hashing the content is not something this ticket is about.

**Comment by pmatilai** [comment]
Closing in favor of a more generic #3050
