### ISSUE TITLE
RFE: run static code analysis in CI

### ISSUE THREAD

**Issue by junaruga** [rpm-software-management/rpm#306]
I want to add `make style-check` task for static code analysis as a dependency task of `make check` in `Makefile`. Because it helps to maintain, keeping the code clean. 

Candidate tools
- C files: I do not know which tool is good.
- Python files: `flake8` [1].
- Shell (bash) files: `sh -n`, `bashate` [2], `shellcheck` [3]

I have used the tool [1], [2], [3]. and I think those are helpful.
How do you think?

[1] https://pypi.python.org/pypi/flake8
[2] https://pypi.python.org/pypi/bashate
[3] https://www.shellcheck.net/

**Comment by ignatenkobrain** [comment]
I don't think we need to run any checks on python/shell code... Although we do run static analyser from time to time locally.

**Comment by junaruga** [comment]
Thanks for the replying. What do you think so?
Why is  "we do run static analyser from time to time locally" better than running the static analyzser for each pull-request in CI?

**Comment by n3npq** [comment]
History from the FreeBSD project showed that automating static analysis tools during build just leads to gigabytes of information that slowly composts because fixing warnings from static analysis is a Sisyphean task. The issue I am pointing out is that static analysis should NOT be run on every rpm build, there's simply too many warnings to handle.

Meanwhile, rpmbuild already classifies files and passes (executable) content for dependency extraction. That same mechanism could be extended for static analysis on scripts. Just as easily,
rpmlint could/should be modified to automate static analysis on distributed python/bash scripts.

Doing C static analysis needs more context than a single file and is usually done like in coverity, by adding a wrapper to an existing build using envier's. There is nothing in a *spec file that prevents coverity-style static analysis during an rpmbuild. Again, the volume of warnings/errors usually is large enough to make the automation nothing more than an annoyance.

**Comment by n3npq** [comment]
My previous comment was wrto adding static analysis instrumentation to rpmbuild for other packages.

For static analysis on RPM itself by adding make targets, then LCOV/GCOV coverage targets and adding test cases is usually more useful than static analysis warnings.

Note that I have years of experience with static analysis tools applied to RPM sources ;-)

**Comment by junaruga** [comment]
> My previous comment was wrto adding static analysis instrumentation to rpmbuild for other packages.

Yeah, I knew that after reading your comment. `rpmbuild` and `rpmlint` are doing the analysis.
My proposal is about for static analysis on RPM itself, as you mentioned.

> For static analysis on RPM itself by adding make targets, then LCOV/GCOV coverage targets and adding test cases is usually more useful than static analysis warnings.

I agree with you.
Adding coverage test target is also useful for maintainability.

If "we do run static analyser from time to time locally.", I want to know the content as a make target.
I think we do not have to run those static analysis targets in CI as a first step.
Knowing the used analysis tools and the rules by configuration file makes us to contribute easily.
 
> Note that I have years of experience with static analysis tools applied to RPM sources ;-)

OK, let's promote it :)

**Comment by n3npq** [comment]
See https://scan.coverity.com/projects/rpm?tab=overview. Been there for years ....

The make target I use looks like this:
```
# --- scan.coverity.com manual submission in $(PACKAGE).tgz
COVDIR =        cov-int
COVBUILD =      cov-build --dir $(COVDIR)
COVDESC =       $(shell date -u "+%Y%m%d.%H%M%S")
COVFILE =       $(PACKAGE)-scan.tgz
COVSITE =       https://scan.coverity.com/builds?project=rpm
covscan:
        rm -rf $(COVDIR) $(PACKAGE).tgz
        make clean
        $(COVBUILD) make
        tar czf $(COVFILE) $(COVDIR)
        curl --form project=$(PACKAGE) \
             --form token=XXXXXXXXXXXXXXXXXXXXX \
             --form email=n3npq@mac.com \
             --form file=@$(COVFILE) \
             --form version=$(PACKAGE_VERSION) \
             --form description=$(COVDESC) \
             $(COVSITE)
```

I usually find that "static analysis" on scripts is just too much work. Python as an interpreter has too many execution paths that cause false positives, and being "schools m'arm" nagged about quoting and globbing in toy shell scripts just drives me insane. JMHO, YMMV ...

I can/will create an "rpm.org" project and run static analysis if there is sufficient interest. It just isn't that hard.

Meanwhile LCOV/GCOV targets for the existing RPM "make check" is absolutely essential to understanding the relative importance of fixing warnings detected by static analysis.

**Comment by junaruga** [comment]
> I usually find that "static analysis" on scripts is just too much work.

Well, if you do not like static analysis for scripts, I do not promote the tools for the script files (*.sh, *.py) in this project.
Focusing to interest topics, not quoting and globing and etc.
That makes sense. I can understand it.

I may run the analysis tool for python scripts on my local personally, and send pull-request for that.
That's good enough for me. Actually the number of the script files is very few.

```
$ find . -name "*.[ch]" | wc -l
243
$ find . -name "*.sh" | wc -l
12
$ find . -name "*.py" | wc -l
2
```

> The make target I use looks like this:

Thanks for the sample code.
How about a style format check for C files?

**Comment by junaruga** [comment]
Is there the coding rule for this project (for C)?
It looks K&R style.

**Comment by n3npq** [comment]
You can do style checks if you wish.

Meanwhile RPM is/was permeated with false positives like
```
    foo = _free(foo);
```
which is my own personal idiolect of C: wipe oy the pointer when you free the memory.

Huge PITA handling in Coverity: huge number of warnings about "set but unused pointer". Well yeah, I know, I wrote that code.

Have fun! Static analysis change the way I code in really complex ways: RPM was written with years of "static analysis" fixes (but with ,y own peculiar idiolect style).

**Comment by pmatilai** [comment]
> I can/will create an "rpm.org" project and run static analysis if there is sufficient interest. It just isn't that hard.
@n3npq : That'd be nice.

For the every-now-and-then use I've been making do with clang-analyzer. It might not be quite on the level of Coverity, but then I can run it locally without having to wade through terms-of-use and the like which I remember finding somehow off-putting when I last looked at Coverity - many years ago and probably changed a lot since. Anyway, clang-analyzer provides plenty of chatter to fill in the rainy days, and yeah including dead assignments (clang jargon for set-but-unused).

Analysis on CI only makes sense if it can report just the new issues introduced by that commit, otherwise it's just a truckload of electronic waste. IIRC (from another project) Coverity can do that, and also permits marking false positives as such.

**Comment by n3npq** [comment]
OK.

I'll create a RPM.ORG project at scan.coverity.com and import the code to assess the level of pain (and there _WILL_ be pain: it took me several weeks of mind-numbing clickety poo to get the level of reported positives from the coverity firehose down to something that was useful for rpm maintenance.)

clang is okay (try splint sometime ;-). OTOH coverity reuses older analyses to improve their product.
 
So even with no new scans, there are sometimes new problems reported. Quirky, but the process is at least transparent, unlike fuzzing.

**Comment by pmatilai** [comment]
Okay so we're not running static analysis on CI, the ticket just forgotten open -> closing.
