### ISSUE TITLE
RFC: give some freshness to brp scripts

### ISSUE THREAD

**Issue by ignatenkobrain** [rpm-software-management/rpm#308]
Nowadays, buildroot policy is something way more complicated than it used to be 10 years ago. We need to be able to run brp scripts depending on files which are in buildroot (something similar to dependency generators), depending on tools which are available (e.g. it doesn't make any sense to BuildRequires: libappstream-glib from rpm-build just to have some brp script which will run appstream-util validate-relax ...).

Currently packagers have to add some BuildRequires and paste same commands into their %check sections which is not best UX.

I don't have any proposals how to solve this problem yet, so filling this as RFC.

**Comment by junaruga** [comment]
What is brp script's "brp"? Though it may be basic knowledge.

**Comment by ignatenkobrain** [comment]
@junaruga it stands for `BuildRoot Policy`, scripts which are executed after build to check (e.g. for RPATH in standard places like /usr/lib). You can find them here https://github.com/rpm-software-management/rpm/tree/master/scripts (with `brp-` prefix). But those are really basic.

**Comment by junaruga** [comment]
@ignatenkobrain thank you for the kind explanation. I could understand it.
I still do not know much basic knowledge 😞

**Comment by n3npq** [comment]
I think you need to describe a more complete example of what you think needs additional "freshness" in build root policy scripts: the need cannot be deduced from the terse descriptions of problems in comment #1.

**Comment by proyvind** [comment]
Nay on this one from me.

Given the generally and relatively small number of files found in buildroots and thanks to fs caching, running 'find' in buildroot per script takes up an irrelevant amount of time, where the KISS brp- scripts does a perfectly good job (unless horribly implemented) of detecting the usual small amount of files to deal with.

This RFE seems inspired from the  the internal dependency generator which implements file classification (ending up in binary rpms post build, in contrast to what is proposed for brp- scripts in this RFE) now externalized to foo.attr files rather than hardcoded in source.
Use of this classifiation during build time to determine which files to run the relevant generator scripts are used for reducing the amount of times spent on generating dependencies as each script is invoked once  time per individual relevant file.
This is really horrible design as simply making the generator scripts spit out filename together with dependencies generated for would be able to achieve same, with each script being run just once for whole buildroot (as with the external dependency generator, which people might've noticed was much faster than the internal generator which is now taking up most of the build time for certain packages now due to how the scripts are invoked numerous times rather than just generating all deps in a single run).

For Mandriva where we've had a ton of brp- scripts run at end of build (see #122), the amount of time spent on is rather neglible from our experience, which makes me lean towards this RFE as an encouragement of overengineering and complexity that's not really necessary (unless proven otherwise).


If packagers in Fedora (I assume) have to explicitly add buildrequires in order for brp scripts to work rather than relevant package type pulling them in automatically or manually add commands to %check (which is really not the right place for adding them in lack of brp- scripts, they're supposed to be run at end of %install, ie. %__os_install_post), that's more of an issue with the packaging itself (if libappstream-glib pulls in more dependencies than desirable just for appstream-util which I assume has less dependencies, then the better solution would be to simply split appstream-util out in separate package to be pulled in automatically by rpm-build or whatever package would be appropriate).

Mind you, I might totally misunderstand your RFE, as I share similar thoughts on the matter as @n3npq ...

**Comment by Conan-Kudo** [comment]
So something I've seen in SUSE systems is that they have a brp-suse script, that reads from a drop-in directory containing brp scripts. They do this because we don't have a way of specifying vendor brp scripts out of the box in RPM.

If vendors want to have more build root policies, they have to redefine the main thing and add to it. This is clunky, inelegant, and means that as things are fixed in RPM upstream, they won't apply to the distribution using the vendor config. This could lead to quirks and breakages, too.

So I think a really simple enhancement would be to make it so that we support drop-in brp scripts like we do for macros and add a vendor search directory, too.

**Comment by n3npq** [comment]
@Conan-Kudo: Providing an additional directory where brp scripts might be found doesn't address conditionalizing which brp scripts are run dynamically.

Its rather easy to add Yet Another Directory of brp scripts (augmenting PATH), but its rather harder to determine which scripts to run.

There are two choices to conditionalize running brp scripts based on package content:

1) write the brp script to do nothing if condition is not met and run always.

2) add a build requires and invoke the script at the end of %install explicitly

**Comment by Conan-Kudo** [comment]
@n3npq 

I think that unless a brp script is provided by the package that also includes the binary to run, I think it's probably going to have to be option 1.

**Comment by n3npq** [comment]
@Conan-Kudo There is nothing stopping

3: add script to SourceN: and invoke as %SOURCEn

4) change the macros that specify what scripts to run (but that is what is being claimed "clunky" when in fact what is desired of rpm is lazy DWIM)

**Comment by proyvind** [comment]
This one too has been left without any movement on for way too long despite all issues raised has been adressed...

I notice that the existing upstream brp- has been macroized, creating conflicts with this PR and requiring it to be adapted to this change.

Again,  I don't have that great possibility to follow up on this one immediately either, @Conan-Kudo could you attend to it perhaps? :)

**Comment by ffesti** [comment]
This doen't look like it's going anywhere. Closing.
