### ISSUE TITLE
%autopatch -m/-M fall through silently if no patches are in range

### ISSUE THREAD

**Issue by pmatilai** [rpm-software-management/rpm#3093]
hello-autopatch.spec in our testsuite has this:

```
%patchlist
hello-1.0-modernize.patch
hello-1.0-install.patch

%prep
%autosetup -N
%autopatch 1
%autopatch -m 2
```

Spot the error? Automatic patch numbers start from zero, so we're telling it to apply hello-1.0-install.patch and then any higher numbered patches, so the modernize patch is never applied.
There are legitimate reasons to conditionally skip patches, but having a ranged patch that doesn't actually do anything should at least emit a warning.

How did we find out? Fedora 40 introduced stricter, more modern C compilation settings (https://fedoraproject.org/wiki/Changes/PortingToModernC ) and suddenly we had a test-case go red because it wasn't applying a patch it's supposed to, to address this very issue.

**Comment by dmnks** [comment]
Oh, right, my bad... The SRPM is of course not used in the autopatch test specifically (the tarball is separate indeed). And it's fixed in the SRPM for a reason (to avoid the compiler warning, now error).

**Comment by AdamWill** [comment]
Note, there is a pattern here that seems valid to me, which triggers this warning. See [Fedora's evolution-data-server package](https://src.fedoraproject.org/rpms/evolution-data-server/blob/rawhide/f/evolution-data-server.spec). An edited extract:

```
# 0-99: General patches

# 100-199: Flatpak-specific patches
# https://gitlab.gnome.org/GNOME/evolution-data-server/-/merge_requests/144
Patch100: Make-DBUS_SERVICES_PREFIX-runtime-configurable.patch

...

%prep
%autosetup -p1 -S gendiff -N

# General patches
%autopatch -p1 -m 0 -M 99

# Flatpak-specific patches
%if 0%{?flatpak}
%autopatch -p1 -m 100 -M 199
%endif
```

that is, it wants to carry "general" patches **IF ANY** in the range 0-99, and "flatpak-specific" patches **IF ANY** in the range 100-199. The problem comes if we don't have at least one general patch and one flatpak-specific patch, because now that triggers this warning. But you can see the logic of what the package wants to do, and it makes sense, and I don't see how it could avoid this warning...

**Comment by pmatilai** [comment]
Hmm, I could've sworn we had a disabler for the warning ... and ... we do, but it's only documented in the macros file :facepalm: 

`# -q            Don't warn if there are no matching patches`

Added to the manual too now in 109d8aaf18ec29c0f0e1b2a6d598a25059930091. Thanks for pointing this out!

But these are all of course just band-aid workarounds, the real fix is to allow conditional patching in %autosetup itself (#3110)
