### ISSUE TITLE
RFE: automatic creation of langpacks subpackages

### ISSUE THREAD

**Issue by ignatenkobrain** [rpm-software-management/rpm#310]
We have %find_lang thing in RPM, and I don't see any reason why we can't automatically generate language subpackages. It would be really great experience for users, it will save space and so on.

IIRC @Conan-Kudo told me one day that openSUSE does it already somehow, so probably we could adapt their approach..

**Comment by proyvind** [comment]
See %_install_langs.

Whatever locale is defined by will be the only files with matching %lang() attribute installed.

So the only thing this RFE would accomplish would be reducing the size of the particular binary rpm itself, while generating tons of additional small packages with additional complexity put on dependency resolver to pull in the relevant language package.

IMO this would be rather undesirable to both users, packagers and developers.

**Comment by Conan-Kudo** [comment]
Wrong. The big problem with `%_install_langs` is that you can't get the content if the system changes. Instead, you have to reinstall the whole package.

By having subpackages, we can generate them with the correct rich dependencies such that when a new locale is installed, all the software on the system would have their langpacks installed with it.

We cannot do this with `%_install_langs`.

**Comment by proyvind** [comment]
k, I can see that being corner case useful, at least for traditionally installed distributions (ie. distro installation from packages).

But I guess live installers/image dumps are becoming more common these days (or might just've become even what's considered common these days..? *dinosaur*) I can see the usefulness.

 and when re-reading the RFE, I understand that the idea was probably a single language package of %lang files per package rather than individual ones per language, no?

Makes more sense, yet I'm uncertain whether I like approach though, but without giving it much further thought at the moment, I might as well dismiss this as a personal preference of implementation aestethics for now.. ;)

**Comment by ignatenkobrain** [comment]
@proyvind no, idea is to have package-per-language. We can use weak deps for instance to cope with %_install_langs or any other mechanism.. Also it reduces package size significantly in some cases (IIRC it was ~100MiB for evolution package).

Currently in fedora, people have to create such subpackages manually -- see https://fedoraproject.org/wiki/Packaging:Langpacks

**Comment by n3npq** [comment]
Creating package-per-language manually isn't exactly hard: see the macro at the link.

(aside)
For extra credit: someone ought to put up an example of how to map boilerplate macros into %SOURCEn directives that can be included (and %include is essentially just a %{cat %SOURCEn}) or inserted with %{load:....} (if multiple %define's in initialization is somehow seen as "ugly"), which would perhaps be deemed more aesthetic and remove a perceived RFE need to do better "automagic" packaging.

Automating creation has to make choices on which locales to create sub-packages for: mere existence of a subdirectory containing *mo files isn't a sufficiently strong hint. Other inclusion policy criteria (e.g. no. of fuzzy or untranslated items) is usually needed for selection.

Even other additional policies based on *po context could be implemented with gettext tools wrapped in macros/scripts but there's hardly a need.

Again manually generating subpackage-per-langi=uage isn't all that difficult and is little more than a list of what locales are desired.

**Comment by ignatenkobrain** [comment]
@n3npq while I agree that it is not hard at all, asking packagers to do manual work is always bad..

Could you elaborate more on

> Automating creation has to make choices on which locales to create sub-packages for: mere existence of a subdirectory containing *mo files isn't a sufficiently strong hint. Other inclusion policy criteria (e.g. no. of fuzzy or untranslated items) is usually needed for selection.

...? Some concrete examples would be awesome.

**Comment by Conan-Kudo** [comment]
@ignatenkobrain There's no obvious way to determine what should be the "base" langpack bundled with the main software and the translations that should be packaged separately.

A lot of software fall back to a base langpack when translations aren't sufficient, and there's no easy way to tell what that is. We *could* assume English, but that may not be true...

**Comment by ignatenkobrain** [comment]
@Conan-Kudo I don't think such things happen very often... But we could have opt-out or make this thing configurable..

**Comment by n3npq** [comment]
I was referring to LINGUAS (which get text uses to determine what locales are included and installed).

E.g. the Icelandic is.po file in RPM likely hasn't been touched for years: examining the contents shows that many strings have not been translated.

LINGUAS can be used to disable installing what is mostly useless (because untranslated) content.

Analogous to LINGUAS, automating language sub-packages would involve choosing which languages are "useful" (as in fully translated) and "supported". Automating the selection (and adding manual disabler/enabler override logic to give package monkeys the illusion of choice) involves choosing metrics for making the choice.

At some point -- just like with LINGUAS -- its just a list of locales that map to paths that get added to a sub-package.

Meanwhile since the real goal here (see your example above claiming a savings of ~100Mb) is to get rid of perceived "bloat" in *.rpm packages, devising a mechanism to support some imaginary policy that creates language sub-packages when "needed" is mostly a waste of time.

Teaching package monkeys how to control language sub-package automation will be much much harder than just leaving bad enough alone.

It really isn't all that hard to type in a list of locales that you want as sub-packages: you just have to care enough to do that.

**Comment by n3npq** [comment]
@Conan-Kudo: the "C" locale is the obvious choice for the "base" locale (which happens to also be English in most cases).

**Comment by ffesti** [comment]
This is just a more specific version of #329 . While the discussion here has its own merit there is no point having two tickets open. So I am closing this one. This does not imply that the use case here is not valid.
