### ISSUE TITLE
Non-root owned symlink causes install failure

### ISSUE THREAD

**Issue by dmnks** [rpm-software-management/rpm#3100]
**Describe the bug**
Installing a package that ships a file in a directory symlink that's owned by a non-root user results in a cpio unpacking error.

UPDATE:
Failing is expected here of course, the error message can be quite cryptic though.

**To Reproduce**
1. `useradd user`
2. `chown -h user /lib`
3. `dnf install -y kernel-core`

**Expected behavior**
Better error message.

**Output**
```
error: unpacking of archive failed on file /lib/modules/6.8.9-300.fc40.x86_64/build;6644c9d4: cpio: open failed - Not a directory
```

**Environment**
 - OS / Distribution: Fedora 40
 - Version rpm-4.19.1.1

**Additional context**
Filed originally in RH Jira: https://issues.redhat.com/browse/RHEL-33393. The reporter has suggested the culprit in the second comment in that issue.

**Comment by ffesti** [comment]
I guess this is very much intentional as the owner may send RPM to overwrite random files otherwise. This is the very case we did re-write the fsm for.

This still needs to give a sane error message, giving the user a fighting chance to find out what's the issue.

**Comment by pmatilai** [comment]
Yup, we can't follow non-root owned symlinks, the main issue is error message.

Ideally we'd toss the bad link with a warning and continue installation but whether that's *possible* is a whole other question.

**Comment by ffesti** [comment]
OK, we actually set `errno` to ENOTDIR explicitly. Simplest "fix" would be to set it to EPERM for this case. This results in "Operation not permitted" instead of "Not a directory". This is obviously better and closer to the truth. But this still does not quite make it obvious what's the actual issue.

**Comment by pmatilai** [comment]
EPERM is just a different kind of misleading: I'm root, what do you mean "not permitted"?

**Comment by pmatilai** [comment]
So seeing this thing was like popping a cork in my head and then all the memories of the symlink CVE's bubbling up throughout yesterday evening to entertain me... Commenting here instead of the PR because there's more to this than what's in the PR now.

This error is not a system error so there's no errno that will adequately, much less satisfactorily match the situation. Been there, pored through it. It's an rpm specific error, and that you now added here. I was about to say I don't remember why I didn't add that a specific error for this, but actually I did: 2668a2cabfe097d58adb9810da1cc8aa7fe1cc91. Only I forgot to actually use it :laughing: . So, we don't need a new code for it.

Don't add any EPERM in there, ENOTDIR is technically the right thing for mimicing O_DIRECTORY behavior as it intends to. Instead, this invalid symlink thing can happen in any number of situations, not all of them related to directories. It needs to be caught inside the "follow links" condition and reported as the already existing RPMERR_INVALID_SYMLINK. And then make sure the O_DIRECTORY logic doesn't mess up the code. I think it doesn't but you'll want to double-check.

Finally, besides reporting the invalid symlink as such when encountered, the right thing to do is to catch this in the pre-flight checks and prevent the transaction from even starting. It doesn't remove the need to handle it inside the fsm - the fsm needs to catch it real-time like it does now to prevent bad actors, but the pre-flight check should be there to catch admin mistakes such as in the original report. Failing an update mid-transaction can have pretty catastrophic consequences so we should catch what we can. I didn't chase that back then because fixing the CVE was the priority.

**Comment by pmatilai** [comment]
Heh, I'd already forgotten this one: 89ce4e7ca592f5abafc3f25aeaa07d36a7b43a61 - but truly, been there, didn't help :smile:

**Comment by dmnks** [comment]
> I guess this is very much intentional as the owner may send RPM to overwrite random files otherwise. This is the very case we did re-write the fsm for.
> 
> This still needs to give a sane error message, giving the user a fighting chance to find out what's the issue.

Oh, indeed. Actually that's also what the original RHEL ticket is about (i.e. to improve the error reporting here), I just filed this GH ticket in a rush and apparently didn't quite read through the RHEL ticket properly. I'll fix up the "Expected results" here.

**Comment by pmatilai** [comment]
The MVP to improve user understanding would be using the specific error code we have for this.
That would be something we could sneak into 4.20 at this point, but detecting this before transaction is way out of scope there, pushing this back to todo.
