### ISSUE TITLE
Please add documentation explaining how to use alternate libraries from the test suite

### ISSUE THREAD

**Issue by nwalfield** [rpm-software-management/rpm#3200]
**Describe the bug**

While working on `rpm-sequoia`, I want to run the `rpm` test suite against my version of `librpm_sequoia.so`.  `make tree` appears to take the `librpm-sequoia` library from the root file system even though I've configured it (using `PKG_CONFIG_PATH`) to look elsewhere.

**To Reproduce**

First, observe that `cmake` only works when I've set `PKG_CONFIG_PATH`, because I haven't installed `rpm-sequoia-devel`.

```
neal@fedora:~/rpm$ rm -rf _build/
neal@fedora:~/rpm$ mkdir _build
neal@fedora:~/rpm$ cd _build/
neal@fedora:~/rpm/_build$ cmake -DENABLE_PYTHON=OFF ..
-- Checking for module 'rpm-sequoia>=1.4.0'
--   Package 'rpm-sequoia', required by 'virtual:world', not found
CMake Error at /usr/share/cmake/Modules/FindPkgConfig.cmake:619 (message):
  The following required packages were not found:

   - rpm-sequoia>=1.4.0

Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPkgConfig.cmake:841 (_pkg_check_modules_internal)
  rpmio/CMakeLists.txt:21 (pkg_check_modules)


-- Configuring incomplete, errors occurred!
neal@fedora:~/rpm/_build$ cd ..
neal@fedora:~/rpm$ rm -rf _build/
neal@fedora:~/rpm$ mkdir _build
neal@fedora:~/rpm$ cd _build/
neal@fedora:~/rpm/_build$ export PKG_CONFIG_PATH=$HOME/rpm-sequoia/target/release
neal@fedora:~/rpm/_build$ export LD_LIBRARY_PATH=$HOME/rpm-sequoia/target/release
neal@fedora:~/rpm/_build$ cmake -DENABLE_PYTHON=OFF ..
...
-- Generating done (0.0s)
-- Build files have been written to: /home/neal/rpm/_build
...
```

Now I run the test suite:

```
neal@fedora:~/rpm/_build$ make && make check
ERROR: 448 tests were run,
7 failed (5 expected failures).
76 tests were skipped.
## ------------------------- ##
## rpmtests.log was created. ##
## ------------------------- ##

Please send `rpmtests.log' and all information you think might help:

   To: <http://rpm.org>
   Subject: [rpm 5.99.90] rpmtests: 90 207 failed

You may investigate any problem if you feel able to do so, in which
case the test suite provides a good starting point.  Its output may
be found below `rpmtests.dir'.

make[3]: *** [tests/CMakeFiles/check.dir/build.make:70: tests/CMakeFiles/check] Error 1
make[2]: *** [CMakeFiles/Makefile2:1595: tests/CMakeFiles/check.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:1602: tests/CMakeFiles/check.dir/rule] Error 2
make: *** [Makefile:754: check] Error 2
eal@fedora:~/rpm/_build$ cat tests/rpmtests.dir/207/rpmtests.log 
#                             -*- compilation -*-
207. rpmsigdig.at:499: testing rpmkeys --import invalid keys ...
/rpmsigdig.at:507:
runroot rpmkeys --quiet --import /data/keys/CVE-2021-3521-badbind.asc
echo exit code: $? >&2

/rpmsigdig.at:520:
runroot rpmkeys --quiet --import /data/keys/CVE-2021-3521-nosubsig.asc
echo exit code: $? >&2

--- -   2024-07-08 15:09:28.800244394 +0000
+++ /srv/rpmtests.dir/at-groups/207/stderr      2024-07-08 15:09:28.797363072 +0000
@@ -1,2 +1,3 @@
-exit code: 0
+rpmkeys: symbol lookup error: /usr/local/lib64/librpmio.so.10: undefined symbol: _pgpPubkeyMerge
+exit code: 127
 
207. rpmsigdig.at:499: 207. rpmkeys --import invalid keys (rpmsigdig.at:499): FAILED (rpmsigdig.at:520)
```

The above is complaining about the missing `_pgpPubkeyMerge` symbol.  So it looks like it is picking up the system `librpm_sequoia.so` and not the one configured via `pkg-config`:

```
neal@fedora:~/rpm/_build$ objdump -T $HOME/rpm-sequoia/target/release/librpm_sequoia.so.1  | grep pgpPubkeyMerge
0000000000062e90 g    DF .text  00000000000005d7  Base        _pgpPubkeyMerge
neal@fedora:~/rpm/_build$ objdump -T /usr/lib64/librpm_sequoia.so.1  | grep pgpPubkeyMerge
```

**Expected behavior**

I expect to be able to use an alternate library.

**Environment**

```
neal@fedora:~/rpm/_build$ git log -n 1
commit 775acf13850373c16d4b0d02a1970339c381f19b (HEAD -> master, origin/master, origin/HEAD)
Author: Panu Matilainen <pmatilai@redhat.com>
Date:   Wed Jun 26 11:04:00 2024 +0300
...
```

**Additional context**

Thanks for any help.

**Comment by dmnks** [comment]
The tests are run in containers spawned from a local Podman image tagged `rpm`. That image is built from `tests/Dockerfile` (currently only Fedora-based). Therefore, rpm-sequoia is taken from that image, not your host.

This image is made by
1. Building the base image (`rpm/base`) from `tests/Dockerfile` (which itself is based on Fedora)
2. Installing your local rpm build artifacts on top of that image and producing the final `rpm` image

This makes testing your code (rpm-sequoia as a prime example) *against* your local rpm build a bit more complicated at the moment. I plan to make this easier (tracked as #2877), however for now, one (very ugly and hacky) way is to either:

1. Adjust the shipped `tests/Dockerfile` so that it builds and installs sequoia system-wide in it

or

1. Remove the following line from `tests/mktree.oci`:
`$PODMAN build --target base -t $IMAGE/base $ARGS`
2. Build your own `rpm/base` image (e.g. run a container on top of the stock `rpm/base`, then manually build and install rpm-sequoia, then commit the container as the `rpm` image)

Yes, this is super convoluted and not user-friendly at all. I'll try to get #2877 done in the near future.

**Comment by nwalfield** [comment]
Thanks for the quick and helpful follow up.

**Comment by dmnks** [comment]
Thinking about it, a quick fix (on master) would be to allow for using a custom base image instead of `rpm/base` via a cmake option. You would still need to provide the image somehow (build it manually or from a custom Dockerfile) but at least you wouldn't have to "patch" mktree.oci like described above :facepalm:

**Comment by dmnks** [comment]
... But I need to think it through more so that we don't introduce new cmake options only to deprecate/remove them afterwards...

**Comment by dmnks** [comment]
Anyways, I can imagine this is effectively blocking your rpm-sequoia development efforts so I'll promote #2877 into our Priority queue so it gets handled quicker. Thanks again for chiming in on this! :smile:

**Comment by nwalfield** [comment]
So here's the evil thing I did:

```
$ cd ~/rpm
$ cp ~/rpm-sequoia/target/release/librpm_sequoia.so librpm_sequoia.so
```

Add the following to the `tests/Dockerfile`

```
ADD /librpm_sequoia.so /usr/lib64/librpm_sequoia.so.1
```

Then I ran `make tree && make check`

**Comment by dmnks** [comment]
Nice :smile: Maybe we could just allow for specifying a directory path on the host at cmake configure time that should be copied/mounted in the test containers (and possibly a list of env vars to set, too).

**Comment by nwalfield** [comment]
> Anyways, I can imagine this is effectively blocking your rpm-sequoia development efforts so I'll promote #2877 into our Priority queue so it gets handled quicker. Thanks again for chiming in on this! 😄

I've hacked around this for now.  As there aren't any other changes on the horizon for `rpm-sequoia`, you don't need to prioritize this for me.  Thanks though! 😊

**Comment by dmnks** [comment]
Ack, and no problem at all!

**Comment by dmnks** [comment]
Meanwhile, closing this one as a dupe of #2877 (documentation will part of the other ticket as well).
