### ISSUE TITLE
Proposal for default init.lua

### ISSUE THREAD

**Issue by jasontibbitts** [rpm-software-management/rpm#321]
I don't know if people see init.lua as something to be used or avoided, but I have played with it on and off over the past few years.  When playing with macros I generally do anything even mildly complicated in lua, and I ended up with a basic debugging framework and a set of utility functions.  Having those by default in the namespace is useful, but not generally possible unless a specfile invokes a macro which defines them or you use init.lua.

But one obvious problem with it is that it's a monolithic file, so you can't  have a package drop in additional functions.  I solved this with the following init.lua file, which just loads other lua files from /usr/lib/rpm/lua.d.  Note that I wrote this with the intent of shipping this in one of the Fedora RPM-related packages but did not get to the point of actually doing that.

I can already see various improvements to be made (such as making sure the list is processed in order) but I figured I would at least offer something to start a discussion.

```
-- Master Fedora Lua init file for RPM

-- RPM will execute this file at each run.  It should do nothing other than
-- sourcing other Lua files in /usr/lib/rpm/lua.d

-- Originally written by Jason Tibbitts <tibbs@math.uh.edu> in 2016.
-- Donated to the public domain.  If you require a statement of license, please
-- consider this work to be licensed as "CC0 Universal", any version you
-- choose.

-- My hope is that other distributions, or RPM itself, will adopt this method.
-- If RPM does, this file should go away.

local rpm_lua_dir = "/usr/lib/rpm/lua.d"

package.path = package.path .. ";" .. rpm_lua_dir .. "/?.lua"

local i, file
for i, file in pairs(posix.dir(rpm_lua_dir)) do
    local name = file:match("(.*).lua")
    if name then
        require(name)
    end
end
```

**Comment by Conan-Kudo** [comment]
I think this is an excellent idea, but I'm not sure of the semantics of what happens when something is redefined in another lua file.

For example, if `/usr/lib/rpm/lua.d/foo.lua` ships function `do_foo` and `/usr/lib/rpm/<RPMCANONVENDOR>/lua.d/bar.lua` (in Fedora's case, the `RPMCANONVENDOR` is `redhat`) ships a function `do_foo` and it's initialized later, what happens?

In regular RPM macros, the former is clobbered by the latter. If there's a different behavior, things get really tricky very quickly.

**Comment by n3npq** [comment]
Everyone wants modules: rpm needs to support both LPATH and CPATH, in a private rpm tree as well as "standard" system paths.

init.lua "support" has been in place since 2003 and no-one (that I know of) has made any serious attempt to use.

**Comment by jasontibbitts** [comment]
My understanding is that the later definition simply overrides the former.  But I would expect that conventions for namespacing would work to prevent accidental conflicts and if you can't redefine then you would just use functions in a namespace.  I don't see why that would be mandatory, though of course actually documenting the behavior would be a great idea.

And, well, I certainly thought I was making a serious attempt to use it.  And in any case why does it matter that "nobody" has tried to use it?  RPM is esoteric and there are only a few people who even get down to this level.

I don't know how early init.lua is parsed but if it's after rpmrc files are parsed then it would certainly be possible to look in private directories.  Should be easy to determine that in any case.

And sure, I'd love to see better Lua support.  I'd really like to see more RPM state exposed in the Lua symbol table, but I'm not yet sure how to do alter things to make that happen.

**Comment by ignatenkobrain** [comment]
@jasontibbitts just FYI, 4.14 is out so master is open for breaking (kinda joke) ;)

**Comment by n3npq** [comment]
@jasontibbitts: apologies if you have interpreted "serious" as a criticism of your personal efforts
That wan not my intent.

Meanwhile, your suggested patch -- the only positive suggestion of what you wish -- is little more than force loading a number of modules based on globbed names, regardless of usefulness (to rpm embedding of lua), total ignoring the support within the lua language to load modules (either scripts or C level bindings) through LPATH/CPATH, including envvar overrides. Otherwise, your patch would be a vital first step to changing how rpm+lua functions: meanwhile prior art exist, using what is implemented in lua-5.x since 2003. Just ... why reinvent round wheels imperfectly?!?

(aside)
I claimed no "serious" attempt to use rpm+lua since 2003. That is in fact not true: there is an entire *nix distribution that chose to use rpm+lua embedding in order to create a distribution, which "worked" but alas, not rpm4.org code. Meanwhile, I will quote the person who used rpm+lua to do that distribution
* "If rpm had embedded perl instead of lua, I would not have used rpm+lua".
I'm sure you can find the distribution that I refer to.

Now for other interpretations of "serious"
* there have been no attempts to patch init.lua until your RFE (that I am aware of). You are welcome to examine the last ~15y of rpm releases to ascertain the objective truth of my claim.
* using patterns to force load modules -- while well intended -- ignores changes to support LPATH/CPATH requires(foo) loading that are now part of lua (for at least 4y now, albeit lua has abandoned at least one module loading scheme since 2003).
* force loading modules (as in your patch) forces another lua layer to "require" whatever modules rpm deems useful. There is no well defined way to track module existence within rpm dependencies, particularly when (as likely) lua is being used in %pretrans scripts. Specifically: what is rpm to do when, say, some module is unavailable in an *empty* tree after chroot(2) has been performed? Returning an error is not a satisfying answer imho.

A "serious" implementation for rpm+lua embedding with init.lua has (at a minimum, imho) MUST attempt to deal with chroot(2) path prefixes on *empty* chroot's using (if up to me) mount -bind calls to map trees from the host into the hosted chroot tree. YMMV.

**Comment by pmatilai** [comment]
Okay so actually a drop-in directory for Lua bits was always implemented in rpm itself (/usr/lib/rpm/lua/), only the last time it was functional is was so long ago that practically nobody was using Lua for anything back then. It has just recently been fixed in upstream by commit dd6c65044c41922193f520ace668e2c5e55f1004 and since then, and included in the stable 4.14.2.1 release as well.

Closing, we don't need a special init.lua for this now.

**Comment by jasontibbitts** [comment]
Indeed, thanks.

**Comment by prymar56** [comment]
I see there are internal lua objects: %patches %sources, why can't there be %packages?
