### ISSUE TITLE
Unpack failure on update can cause unmodified %config files to be erased

### ISSUE THREAD

**Issue by ffesti** [rpm-software-management/rpm#3284]
See https://issues.redhat.com/browse/RHEL-54386 for details

This need examination to check whether this affects newer versions, too. rpm in RHEL 8 has a modern version of the fsm. So it is possible that this is an general issue. It could also be an unfortunate interaction between the new fsm code and the surrounding rpm-4.14.3 code.

**Comment by pmatilai** [comment]
The actual issue is that any file unpack failure during an update can cause unmodified %config files to be deleted on the cleanup stage. This is because normally to-be-installed files are unpacked to a temporary suffix which is then safe to remove, but unmodified config files are handled with FA_TOUCH to only update their metadata instead of rewriting the file, and so must be skipped during cleanup. Affects all rpm >= 4.14 versions AFAICS.

If %_minimize_writes is used, this will have a much wider impact than just unmodified config files.
