### ISSUE TITLE
Add rpmLogOnce to filter log message 

### ISSUE THREAD

**Issue by ffesti** [rpm-software-management/rpm#3395]
**Is your feature request related to a problem? Please describe.**

Many log messages are repeated over and over and need to be filtered down to just one instance. One example is #3333.  
There needs to be a way to limit the lifetime of this (see #3336). Unfortunately the whole logging is currently using global instances.

**Describe the solution you'd like**
The rpmlog module should offer a simple API to do that without needing local book keeping.

**Additional context**
#3389 was a first attempt adding this to rpmts. See dicussion there.

**Comment by ffesti** [comment]
#3336 calls for this to be independent of the process life time. The issue here is that the whole logging system is bound to the process as it is build on top of a global variable.

The right thing IMHO would be adding this functionality to the global log context for now and deal with the issue of non-global logging separately. For now we could add just one new function:

void rpmlogOnce (const char * key, int code, const char *fmt, ...);

`rpmlogClose` would also clear the memory of what has already logged. So far this is only used in `rpmcliFini` which is only called at the end of the command line tools.

So this is basically a non solution but it moves it in with the logging global context issue that we do have anyway.

**Comment by pmatilai** [comment]
Let's look at the bigger picture here a bit, because #3336 is an isolated use-case and rather unusual at that so it's actually not that interesting in itself. The typical case of log suppression we'd want is of the "last message repeated 123 times" kind rather than silence *all* the following messages.

We have at least the following cases with different needs wrt lifetime:
1) per transaction
2) per package in transaction
3) spec parse (optionally followed by package build)
4) process lifetime

1-2 and 3 are kinda separate groups and typically don't exist within the same process. I'm quite sure we technically have stuff that would qualify for 1) besides #3336, and 4) is all we have at the moment. 

I see two ways to think about #3336: either its about unknown key tracking with specific semantics, or its just a warning message with a particular implementation. In the latter case we could just replace the existing behavior of unknown key tracking with the "last warning repeated 123 times" that the rest of the log suppression wants. I don't know if we have anything else that has the same semantics as the current unknown key warning - maybe we do, I just don't remember any atm.

**Comment by pmatilai** [comment]
Hmm, so you could of course easily count the times you get called per each key, and then optionally emit a "repeated X times" when on reset so you'd basically get the #3336 behavior and the more regular log suppression style from the same thing.

The lifetime could be handled by throwing in a context or id to the mix, this could be an arbitrary 64bit int so you can pass in a pointer (ts, spec, whatever), have the keys hang off that, and then have a function to reset the context.

So that'd become something like this, with id 0 (zero) being a global aka per-process lifetime context always, the rest are up to the caller:

void rpmlogOnce (uint64_t id, const char * key, int code, const char *fmt, ...);
void rpmlogReset(uint64_t id, int suppress);

One thing here is that I'd much rather add an internal-only API for this first, that lets us experiment and fiddle with it until we're happy and then make it public if/when the time comes.

**Comment by ffesti** [comment]
Hmm, "last warning repeated 123 times" works fine if there is only one message repeated all over. There surely are cases like this in rpmbuild. But for things like the signature results they are interwoven with other messages. Same is probably true with for other things. E.g. warnings for non declared macros - if we want to add those. Alternative would be listing the suppressed messages and their number at the end. Or we could add "further messages are left out" to the second message.

**Comment by pmatilai** [comment]
Yeah there are two separate things there: for the "last warning repeated 123 times" you'd want to have automatically detected and supressed on all rpmlog() calls. The other case - the original case this ticket started with - is the case where the caller needs to be aware and do their own suppression mechanism. For this case, you'd optionally output on the context reset with a slightly different message based on the key and the actual message.

**Comment by ffesti** [comment]
OK; let's start with the second thing first.

void rpmlogOnce (uint64_t ctx, const char * key, int code, const char *fmt, ...);
void rpmlogReset(uint64_t ctx, int suppress);

Look fine to me. `suppress` probably morphing into a enum for the different modes of operation.

**Comment by pmatilai** [comment]
Right, there could be more than two modes of operation for reset, so "suppress" might be overly limiting as a name - see what comes up.

**Comment by pmatilai** [comment]
> The lifetime could be handled by throwing in a context or id to the mix, this could be an arbitrary 64bit int so you can pass in a pointer (ts, spec, whatever), have the keys hang off that

Realized today with some amusement that this was very much a C hacker proposal. We, we could just use a std::string for the domain without it being any harder :smile: Not saying that you should change the current PR (we can always do it later) but certainly wont oppose if you do.
