### ISSUE TITLE
RFE: add shorthand options for rpmkeys operations

### ISSUE THREAD

**Issue by pmatilai** [rpm-software-management/rpm#3435]
--list etc gets boring to type real fast, we should have one letter shorthands for all the major modes.

**Comment by ffesti** [comment]
`-l` and `-i` is pretty obvious. But I stumbled over `-e` for `--export` and it felt weird as `rpm -e` doesn't exactly export anything. Then I was wondering whether we shouldn't have `rpmkeys --erase` in parallel to `rpm --erase` instead of `rpmkeys --delete` which is yet another word for removing something.

If we don't want to touch that I wonder whether `-x` for `--export` is a better choice - not that is isn't weird in itself...

**Comment by pmatilai** [comment]
-x for export seems fine to me.

As for --delete/--erase I agree, we should probably support -e/--erase as an alias for --delete. Too bad we only realize this now after --delete went official in 4.20, but such is life.
