### ISSUE TITLE
rpmsign --delsign / --addsign regression can corrupt packages in rpm >= 4.18.1

### ISSUE THREAD

**Issue by pmatilai** [rpm-software-management/rpm#3469]
A regression found by RH QE while testing something related:

```
[pmatilai🎩︎lumikko ~]$ rpmkeys -Kv /tmp/bash-5.2.26-4.el10.x86_64.rpm 
/tmp/bash-5.2.26-4.el10.x86_64.rpm:
    Header OpenPGP V4 RSA/SHA256 signature, key ID 199e2f91fd431d51: NOKEY
    Header SHA256 digest: OK
    Payload SHA256 digest: OK
    Legacy OpenPGP V4 RSA/SHA256 signature, key ID 199e2f91fd431d51: NOKEY
[pmatilai🎩︎lumikko ~]$ rpmsign --delsign /tmp/bash-5.2.26-4.el10.x86_64.rpm
[pmatilai🎩︎lumikko ~]$ rpmkeys -Kv /tmp/bash-5.2.26-4.el10.x86_64.rpm 
/tmp/bash-5.2.26-4.el10.x86_64.rpm:
error: /tmp/bash-5.2.26-4.el10.x86_64.rpm: hdr magic: BAD
[pmatilai🎩︎lumikko ~]$
```

It's caused by https://github.com/rpm-software-management/rpm/commit/a94e971dbb10e8bc929108a65c7bb1d5b1d9e77e, ie fix for #2382 . It doesn't happen with all packages, probably has to do with the RH signing server not adjusting the reserved space at all when signing packages, and something on the rpmsign assumptions then fails miserably.

Once the issue is properly understood, crafting a public reproducer shouldn't be too hard.

**Comment by ddelabru** [comment]
> The root cause is RH signing server placing file signatures outside the immutable region of the signature header

The signing server produces raw IMA file signatures. Release engineers then insert these signatures into the RPM header on the client end, most likely using the [rpm-head-signing](https://github.com/fedora-iot/rpm-head-signing) Python package.

I am trying to pinpoint the source of this incorrect behavior in rpm-head-signing. My understanding of the header structure is somewhat limited, but this is what I have been able to glean so far: rpm-head-signing calls rpm's `headerPut()` function via a C extension to perform the actual header signature and IMA signature insertion; for header signatures it applies the `HEADERPUT_DEFAULT` flag, but for IMA file signatures it uses `HEADERPUT_APPEND` instead. My understanding of the `headerPut()` function from a cursory reading of its implementation is that when the `HEADERPUT_APPEND` flag is passed, it should append to an existing tag of the same tag number, within its existing region, if that tag is already present in the header. I think this in itself is correct behavior for inserting the IMA signatures, but I am looking for clues in the surrounding header-manipulation code of `rpm-head-signing` to pinpoint what is causing these tags to be written outside the immutable region.

**Comment by pmatilai** [comment]
APPEND has no effect on regions, it cannot. The immutable region is *immutable* so you cannot append anything into it.
The fix is to simply put the file signatures into the signature header before signing the package as a whole. The signing step pulls the signature header content into a contiguous region that gets written on disk then. I don't remember what exactly the signing server does (does it call rpmsign at some point or does it do all on its own) but clearly it gets this right, otherwise the normal signatures would have the same problem as well.

**Comment by ddelabru** [comment]
> I don't remember what exactly the signing server does (does it call rpmsign at some point or does it do all on its own) but clearly it gets this right, otherwise the normal signatures would have the same problem as well.

The signing server does handle the insertion of "traditional" signatures into the RPM header. It can also "traditionally" sign only an extracted RPM header, which can then be reinserted into the RPM using `rpm-head-signing`. Where the server does **not** actually touch the header is in the case of IMA signing. When the IMA signing feature was implemented, a decision was made to direct users to `rpm-head-signing` to handle the operations of extracting file digests from the RPM before IMA signing and subsequently inserting IMA signatures into the RPM header.

I wasn't really thinking through the problem of when amongst these header operations that region **becomes** immutable; if I understand correctly it's at the moment that the header is signed, because anything in the region must be part of the signed data. Part of the problem here is that I was given a diagnostic listing of tags and region markers from an RPM header as an example and while an "rpmdump" tool was mentioned I haven't actually found the exact executable or command to replicate that so I can distinguish well-formed RPM headers from malformed headers. But based on what you've said here I think I can see an underlying problem.

It seems like the order of operations in `rpm-head-signing` is wrong for this purpose. `rpm-head-signing` performs the insertion of a "traditionally" signed header **and** the IMA file signatures in a single function. The implementation of this function does the IMA signature insertion after inserting the signed header. It sounds like this would be expected to produce a malformed header, but then the premise of handling these operations in a single function is already problematic because the header should not have been "traditionally" signed until after the IMA signatures were inserted. Likewise, the header extraction used for "traditional" signing of the header and the file digest extraction used for IMA signing are also done in a single step; this could be okay if users were able to subsequently insert IMA signatures into the extracted header before signing it.

So if this is actually the nature of the problem, one solution would be to separate these IMA signature insertion and signed header insertion operations into different functions in `rpm-head-signing` and enable the correct workflow (IMA signing and IMA signature insertion followed by "traditional" header signing and signed header reinsertion), and document/communicate the problem for users of `rpm-head-signing` and the signing server so they can adjust their processes, preferably with a deprecation warning on the legacy functionality.

This solution could be enhanced by handling the insertion of IMA signatures into the RPM header on the server, combined in a single request with "traditional" signing of the header. This would enable the server to ensure the correct order of operations (insert IMA signatures into the header, and **then** sign the header). I think in most cases for IMA signing, we are dealing with very large RPMs, so we will still want reinsertion of the header into the RPM itself to happen on the client side.

**Comment by pmatilai** [comment]
> Part of the problem here is that I was given a diagnostic listing of tags and region markers from an RPM header as an example and while an "rpmdump" tool was mentioned I haven't actually found the exact executable or command to replicate that so I can distinguish well-formed RPM headers from malformed headers.

`rpmdump` is only part of rpm since >= 4.20, located in /usr/lib/rpm/rpmdump, but should be easy to compile against older rpm versions too if you need. The source in the tools/ directory of the rpm repo.

> The implementation of this function does the IMA signature insertion after inserting the signed header. 

Right - there you have the problem, look no further. As for code organization and all that, I don't know these signing tools enough to comment.

BTW a closed ticket is not the best place for questions - if you have more, please open a new topic in https://github.com/rpm-software-management/rpm/discussions.
