### ISSUE TITLE
Add an API for libsolv, libdnf, et al to use to check if rpmdb has changed and trivially get path to rpmdb

### ISSUE THREAD

**Issue by Conan-Kudo** [rpm-software-management/rpm#388]
Quoted from @pmatilai in https://github.com/rpm-software-management/libdnf/issues/362#issuecomment-341325991:
> Of course, libdnf is not poking at rpmdb directory just for fun, it does it to see if the rpmdb was changed since the last time. That information is something that librpm should be providing via an API. And now that this came up, I remember going through this same discussion at least twice before in the last 8-9 years but nothing ever got implemented in rpm, so my bad I guess :-/

Also quoted from @pmatilai in https://github.com/rpm-software-management/libdnf/issues/362#issuecomment-341325991:
> AFAICS libdnf does this to see if there is a valid rpmdb cache it can use, which seems fairly reasonable as such, but then libsolv also has similar logic in it. So there's probably something else to streamline etc besides rpm needing to add that rpmdb cookie API.

I'm currently beginning experiments with non-BDB rpmdb, but these assumptions made about how the rpmdb exists causes problems, as I need to patch them to "know" the alternative paths used by the different backends.

It'd be nice if there was a nice backend-agnostic set of APIs to solve these problems in libsolv, libdnf, and dnf so that this stops being a problem and even as more backends and changes to existing ones occur, everything won't break.

(Also filing this so it doesn't get forgotten again...)

**Comment by n3npq** [comment]
Presumably the desired rpm API is some Boolean valued function that returns the value "changed" with minimal hassle.

What isn't clear is what changed means: time stamp since ... ? package count has changed since ... ? digest on files composing an rpmdb?

There is certainly existing prior art in yum detecting rpmdb changes (though it's unclear whether yum knows about anything but BDB). There are also nitpicking details (like w yum) about what "changed" means that need to be defined. E.g. yum complains if an rpmdb is changed by a manual rpm command.

Since the predominant paradigm of depsolvers like DNF/libsolv is to strip all rpmdb info initially and then run a install/upgrade/erase transaction (with implicit rpmdb changes under exclusive write lock), it's unclear (to me anyways) how an API would be used.

Detecting paths to multiple back ends based on macros isn't that difficult. Harder is the problem of, say, having multiple co-existing back ends: which back end should be used to compute "changed"?
Shoukd a back end switch, or a --rebuilddb, constitute a "change"?

There is the further problem of keeping time stamps across --rebuilddb to prevent backup software based on time stamps from needlessly backing up rpmdb's

All solvable problems, just not sure whether an API is all that useful.

**Comment by n3npq** [comment]
Presumably the desired rpm API is some Boolean valued function that returns the value "changed" with minimal hassle.

What isn't clear is what changed means: time stamp since ... ? package count has changed since ... ? digest on files composing an rpmdb?

There is certainly existing prior art in yum detecting rpmdb changes (though it's unclear whether yum knows about anything but BDB). There are also nitpicking details (like w yum) about what "changed" means that need to be defined. E.g. yum complains if an rpmdb is changed by a manual rpm command.

Since the predominant paradigm of depsolvers like DNF/libsolv is to strip all rpmdb info initially and then run a install/upgrade/erase transaction (with implicit rpmdb changes under exclusive write lock), it's unclear (to me anyways) how an API would be used.

Detecting paths to multiple back ends based on macros isn't that difficult. Harder is the problem of, say, having multiple co-existing back ends: which back end should be used to compute "changed"?
Shoukd a back end switch, or a --rebuilddb, constitute a "change"?

There is the further problem of keeping time stamps across --rebuilddb to prevent backup software based on time stamps from needlessly backing up rpmdb's

All solvable problems, just not sure whether an API is all that useful.

**Comment by pmatilai** [comment]
A simple cookie API implemented in PR #712 , comments welcome.
