### ISSUE TITLE
Extend %changelog to accept filename.

### ISSUE THREAD

**Issue by voxik** [rpm-software-management/rpm#393]
Currently, the changelog entries can be either listed in a .spec file or they could be included by ```%include``` directive. However, usage of the ```%include``` has one major downside, that the included file must be explicitly listed as one of sources, otherwise the file would not be available for build from SRPM.

Would it be possible to extend the ```%changelog``` section, so it would accept ```-f``` parameter with filename. If that file was available, it would do two things:

1. Liste the content of that file as changelog
2. Include that file in generated SRPM

That would give a way to remove the long ```%changelog``` sections from .spec files, making it more readable and it would enable to autogenerate the %changelog entries from SCM logs.

**Comment by voxik** [comment]
Actually, if ```%include``` automatically included the referenced file into SRPM, that would be helpful as well. I realize, that the path could be arbitrary, but if there was restriction, that could work ...

**Comment by pmatilai** [comment]
Splitting spec into multiple pieces (whether %include or otherwise) tends to have all sorts of downsides, especially because it breaks long-standing expectations of specs being standalone entities. I'm not actually opposed to adding %changelog -f but I'm also not convinved it's be best way to deal with pulling changelogs from scm, because then you'd still need the silly one-liners in each spec. Yes you can automate that, but then you might just as well automate slapping the changelog itself at the tail of the spec, so that the spec ending up in src.rpm's remains standalone and by looking at the srpm you don't actually know the changelog came from outside. Which is probably what you'd want if you were to rebuild a distro package locally.

**Comment by voxik** [comment]
Well, one big advantage from the %include/%changelog way would be the possible opt-in. If you want to automate "slapping the changelog itself at the tail of the spec", then it means you have to actually change the build infrastructure to do it.

TBH the biggest issue I see currently is that the SRPM changelog duplicates the .spec changelog. And these two might be possibly different. This should not happen.

If I am thinking about the workflow how to obtain the log from SCM and get it into SRPM, I think that the "rpmbuild -bs" could call some macro to update the changelog. But at that moment, you probably don't want to modify the .spec file which as about to be packaged into SRPM. Modifying some changelog file would be more acceptable IMO.

**Comment by pmatilai** [comment]
Yeah there are any number of ways to do it. Multiple distros are doing it via other tooling sitting on top of rpm, that's an entirely valid route and already proven route. Other options include having rpm execute some hook to pull data from an outside source into the spec (and yes putting that modified version of the spec into an src.rpm because that's what really was packaged). Etc.

Lets just say that my motivation for implementing something special primarily for Fedora (because everybody else is already doing it one way or the other) is not sky-high because a) others clearly manage without rpm modifications b) Fedora is pathetically bad at implementing new rpm features anyway.

**Comment by pmatilai** [comment]
https://github.com/rpm-software-management/rpm/pull/69 is related and has some relevant discussion of the caveats etc.

**Comment by voxik** [comment]
Of course some distributions found their way despite RPM upstream being reluctant to support this or similar feature. The #69 just proves that. I did not mentioned Fedora anywhere and I don't think that #69 was proposed by Fedora people.

**Comment by pmatilai** [comment]
The reluctancy is to add features that end up entirely unused. Oh, and features which don't really fit rpm design principles to begin with. 

Personally, I'd *love* to see Fedora get rid of the changelogs maintained in specs and happy to help with it from my behalf, but until somebody actually commits to driving such a project ... it's just a whole lot of talk, recurring year after year after year.

**Comment by n3npq** [comment]
The real issue is that %changelog carried in *.rpm is mostly useless bloat these days, not how to integrate with other VCS systems, or ChangeLog files.

Setup a reliable persistent display of package spec changes, and %changelog will wither away like the human appendix ;-)

**Comment by pmatilai** [comment]
I see %changelog -f as something that would create more issues than it solves, but like said above, we too would very much like to see better integration with external changelogs. Let's continue the external changelog discussion in a dedicated topic: https://github.com/rpm-software-management/rpm/discussions/2768
