### ISSUE TITLE
rpm ignores architecture when creating self-erasures

### ISSUE THREAD

**Issue by mlschroe** [rpm-software-management/rpm#408]
This issue once was https://github.com/rpm-software-management/rpm/pull/253

When you have foo-1-1.i586 installed and you do 'rpm -U foo-1-1.i686', rpm will not add an erase element for the i586 package.

**Comment by n3npq** [comment]
Rpm also does not use foo-1-1.i586.rpm when given the explicit argument foo-1-1.i686.rpm.

**Comment by n3npq** [comment]
Apologies for the deleted comment.

Meanwhile twisting in concepts of "compatible arch" strings including aliasing in all its flaming glories is going to open a world of buggy painfulness even if narrowly limited to what you are calling "self-updates".

The circumstances where a system-wide transition from, say, i586 -> i686 are usually quite rare, and are better handled in depsolvers and installers rather than in rpm.

It's also not too hard (and there have been hysterical RFE's) to imagine that upgrade decisions should include additional info like DistTag:, Vendor:, Buildtime:, desired LC_ALL settings, etc.

At a minimum, using a platform string (and "platform compatibility") should be attempted if you choose to move forward with automated arch compatibility scored upgrade decisions.

**Comment by mlschroe** [comment]
This is fixed with commit 0fcf8c2b8692fbe06b0bb353247f9d70c91c14a1
