### ISSUE TITLE
hardlinked symlinks

### ISSUE THREAD

**Issue by svpv** [rpm-software-management/rpm#418]
Symlinks can be hardlinked, too, and rpm once willingly created packages with hardlinked symlinks. Such packages were pronounced "broken" and sort of outlawed in `rpm-4.6.0-rc1~93` (5c71ced2da7d99b870a07a83dd8f7e8d1f1b7e4b).

Whether such packages are really broken is a matter of opinion, but even if they are, rpm handles them less than gracefully - it fails with "cpio bad magic" (which means it tries to read the magic number in the wrong place, and can be misdirected).
```
$ sudo rpm -i hardsymlinks-1.0-0.x86_64.rpm
error: unpacking of archive failed: cpio: Bad magic
error: hardsymlinks-1.0-0.x86_64: install failed
```
What's worse, it leaves some of the unpacked files in the filesystem.
```
$ ls -l /usr/share/{a,b,c}
ls: cannot access '/usr/share/c': No such file or directory
-rw-r--r-- 1 root root 4 Mar 18 02:12 /usr/share/a
lrwxrwxrwx 1 root root 1 Mar 18 02:12 /usr/share/b -> a

$ rpm -q hardsymlinks
package hardsymlinks is not installed
```
I understand modern rpm supports transactions of sorts.  I'm now tempted to ask a poignant question: what do you exactly mean by transactions if the package is not installed but its garbage is scattered all over filesystem?  Quite a perfect scandal. :-)
```
Name: hardsymlinks
Version: 1.0
Release: 0
Summary: Contains hardlinked symlinks
License: GPL
Group: System
%description
%install
mkdir -p %buildroot%_datadir
cd %buildroot%_datadir
echo foo >a
ln -s a b
ln b c
%files
%_datadir/*
```

**Comment by n3npq** [comment]
See also https://bugs.launchpad.net/rpm/+bug/913572

**Comment by pmatilai** [comment]
Building the reproducer spec with rpm 4.4.x I get this:
```
[pmatilai@sopuli zz]$ rpm2cpio ~/rpmbuild/RPMS/hardsymlinks-1.0-0.x86_64.rpm |cpio -idv
./usr/share/a
./usr/share/b
cpio: warning: skipped 124 bytes of junk
1 block
```
Ie rpm produced a garbage archive which cpio cannot handle, classifies as "broken" in my books.  Built with modern rpm the produced archive is sane and so is the installation.

Yes, rpm doesn't handle broken archives gracefully, it's on the todo along with million other things, been since forever.

**Comment by pmatilai** [comment]
Sigh, and "executed as a whole or not at all" sounds more like ACID than not, bad description. More like, the entire set of operations is aborted if there are pre-determined problems, beyond that it's "best effort" because in the face of omnipotent scripts and anything that can happen on a live system, all bets are off.

**Comment by ffesti** [comment]
Well, this may be technically a regression. But these packages can no longer be created for quite some time. So we are not adding support for them back now. Sorry.
