### ISSUE TITLE
RFE: ensure all %(...) system-wide macros don't pollute stderr

### ISSUE THREAD

**Issue by praiskup** [rpm-software-management/rpm#424]
Some RPM installed `%( shell )` macros pollute stderr (under e.g. `rpmbuild -bs`) if some of their run-time dependencies is missing, e.g.:
```
%python_sitelib %(%{__python} -Es %{_rpmconfigdir}/python-macro-helper sitelib)
%python_sitearch %(%{__python} -Es %{_rpmconfigdir}/python-macro-helper sitearch)
%python_version %(%{__python} -Es %{_rpmconfigdir}/python-macro-helper version)
```
Parsing specfile using this macros without having %__python interpreter works just fine, but stderr contains:
```
sh: /usr/bin/python: No such file or directory
sh: /usr/bin/python: No such file or directory
...
```
It's common mistake that bug reporter assumes it is bug in package which uses this macro (or e.g. bug in rpmlint); so to not confuse everybody -- IMO we should ensure that such macros don't pollute the standard error output, by some checks like:

`%(test ! -f %__python && echo unknown && exit; ...)`

Any other idea is welcome.

(Moved from https://bugzilla.redhat.com/show_bug.cgi?id=1243292)

**Comment by n3npq** [comment]
Surely it's April Fools Day approaching if RPM is expected to stop "stderr pollution" ;-)

**Comment by praiskup** [comment]
Good one, thanks! ;) And yeah, maybe this is more like "documentation fix" request, or request like "hey, rpm maintainers, please show us exemplary rock-solid macros ...".  Because RPM is certainly not responsible for all those kind of errors..  But with all the minimization efforts, those "No such file or directory" errors are getting tiring.  And what's worse, if there's some accidental FTBFS, people stop reading the error log output and automatically consider this to be the cause.

**Comment by n3npq** [comment]
One (controversial) approach to stopping "stderr pollution" is to embed Python in rpm, thereby guaranteeing that Python is always available.

Entirely equivalently, there is no real reason why Python needs to be invoked repeatedly: all the extracted strings are static.

And it's possible to write a macro that executes a shell exactly once, and then saves the output, avoiding the cascade of stderr pollution.

Meanwhile, the Python packaging macros need to be moved to the Python packaging, but that's a different type of pollution that needs to be solved ;-)

**Comment by n3npq** [comment]
If the interpreter info extraction were wrapped like this:

%python_sitelib %{expand:%%global python_sitelib %(...)}

that would solve the cascade problem.

For extra-credit, that wrapping can likely be done using a parameterized macro that takes 2 args, the macro name and the script to run (but I will leave that exercise to someone else).

**Comment by sergiomb2** [comment]
Hello , thinking we saw this problem in mock, in rpmdev-bumpspec and in fedpkg these 3 commands execute foo.spec and some system-wide does not work , but maybe should the programs that not print out that warnings because for them they aren't important .
I hadn't time to look rpmdev-bumpspec code , but some warnings are useful because command didn't work others are not . 
I'm thinking if fix this is not fix the commands that use foo.spec

**Comment by ffesti** [comment]
The proper solutions is to have these kind of macros split out into separate packages that have dependencies on the tools they are using/probing. This has already be done for Python and a few others.

Closing this ticket. Please open new ones for cases that still need work.

**Comment by sergiomb2** [comment]
> The proper solutions is to have these kind of macros split out into separate packages that have dependencies on the tools they are using/probing. This has already be done for Python and a few others.

I'm sorry, but I don't agree , we talked about this some years ago , rpm can't require python-devel , perl-devel and  many other packages,  just to not pollute stderr because some macros have binaries that doesn't yet exit.  And %(...)  can have whatever we want and example [1] on ufraw.spec .

So what we need is something like run rpm with an especial that mute error when expand macros  . 
Or apps when run rpm know if the exit code is success or not ... ( I will investigate this second option )   . 

Thank you . 

[1] 
 rpm -E  "%(/usr/bin/gimptool --gimpplugindir)/plug-ins"
