### ISSUE TITLE
Add deltarpm support

### ISSUE THREAD

**Issue by ffesti** [rpm-software-management/rpm#433]
Allow rpm to directly process delta rpms. One way would be to have a previous unpack step that places the files on disk with tsid suffixes - just as rpm does during installation. The delta rpm would then be added to the transaction with a special flag. Most operations would be done just like with a normal package. Just during the installation files would not be unpacked. Instead fsmCommit() would move the previously placed files to their final location.

This may need some extra code to remove or not even place the files that are excluded by (command line) options.

This should save a lot of diskspace during updates and also time and IO. This will probably need support from the updaters unless they can be tricked by deltarpm that they are now dealing with proper packages.

**Comment by n3npq** [comment]
Deltarpms are between specific versions of rpm packages.

Installing deltarpms using the local install - at best - will only be possible between specific versions of packages that are 1) never changed 2) never have missing files.

There's no obvious solutions with "upgrades" based on local/static deltas while running a transaction (which is not the right place to go substituting an actual package for a delta package).

Performing a "can a delta package be installed?" earlier has to be done before dependency checking to ensure that metadata is available when needed.

At that point, a separarate CLI tool that ensures that the package elements are installable and continues by running rpm becomes feasible. But that is essentially what depsolvers are currently doing with deltarpms.

But perhaps you are just suggesting that deltarpm handling be included in rpmlib for access by depsolvers as a download/reconstruction layer before install/upgrade proceeds. Deltarpms between specific package versions has a combinatorial failure making all possible (or even all "useful") deltas available with fallbacks to full packages when a deltarpm doesn't exist.

**Comment by ffesti** [comment]
The lmitations of delta rpms are well known.
My idea is that instead of building the new rpm package from the delta rpm and the data on disk a separate tool would create the altered files on disk with a suffix. This would be done before the rpm transaction by the updater. If this fails the files would be cleaned up and the full package would need to be downloaded - just as if the construction of the new rpm package had failed.

The rpm part of this would just add the header from the delta rpm to the transaction. But instead of putting the files to disk from the payload it would leave the unchanged files in place and use the previously placed files for the others. So the changes needed in rpm are probably pretty small. But it would save moving all the unchanged data around which makes delta rpms very unattractive right now. Especially as network traffic has become so cheap compared with local IO.

**Comment by n3npq** [comment]
You may wish to change the title and description from "Add deltarpm support" to indicate that you are well aware of the deficiencies of deltarpm.

So iiuc you wish to remove some of the intermediates involved in deltarpm, which applies per-file deltas in order to re-create a *.rpm whose payload is redundantly uncompressed and reinstalled.

That will work, but you should likely try to preserve the sanity/digest checks (like package file size and payload digest) on the original (now "virtual" in the sense never written to disk) package while staging the re-created payload files.

Since you will be fiddling with how rpm re-opens *.rpm files to position at the payload, please also try to accomodate AUTOINSTALL (I.e. permitting applications to simply append tags to package headers before adding to a transaction), the logic should be very similar to what you are proposing for deltarpm.

**Comment by n3npq** [comment]
Note that early unpacking/undeltafying of payload files is also going to disable file digest verification while installing files.

This potentially exposes a TOCTOU (time of check to time of use) security flaw unless you also choose to verify the file digest before renaming.

**Comment by n3npq** [comment]
One solution to the TOCTOU issue is to change the convention for creating temporary files from appending a .tsid suffix to inserting a .tsid sub directory in the path so that the parent directory permissions can be controlled.

**Comment by n3npq** [comment]
The recompression involved in reconstructing the *.rpm could be avoided if deltarpm was permitted to produce a package with an alternative (I.e. no compression) payload.

Adding a compression override tag to, say, the signature header might be useful to avoid both the recompression and decompression when doing funky deltarpm transport.

**Comment by n3npq** [comment]
Even simpler than a compression override tag would be to use the payload archive magic instead of the metadata compression tags to determine how the payload should be unpacked.

**Comment by n3npq** [comment]
AFAICT the ancient sanity check on sizeof lead+sigh+metah+payload has been ripped out in RPM4 (but I'm on an iPad without grep, sigh). Likely eliminated as part of implementing rpmarchive and uint64_t payload size replacement, but that is just a savvy guess, ICBW.

Either way: using magic instead of payload format/compression flags makes a lot of sense for deltarpm recompression/decompression overhead elimination.

At worst, deltarpm would need to fiddle up a new file size shanty check by replacing a tag in the signature header when switching a reconstructed package to no (or lzo if you must minimize disk space usage but improve performance) in deltarpm.

There is also (IMHO) a need to convert payload compressions, and augment verifications of header/payload digests: the header/payload digests in the package are the definitions of what was originally used when the package was built no matter what funky transport (I.e. deltarpm) transforms on the original package content have been introduced as part of downloading and reconstruction.

**Comment by ffesti** [comment]
May be one could construct a package with only the modified (and config) files in the payload. That might only require very minimal changes on the rpm side.

**Comment by ffesti** [comment]
Doesn't look like this is happing any time soon. Closing.

**Comment by Conan-Kudo** [comment]
😢
