### ISSUE TITLE
RFE: All macro expansion failures should include line numbers for original macro location.

### ISSUE THREAD

**Issue by codonell** [rpm-software-management/rpm#491]
While developing glibc.spec for Fedora I ran into this issue:
fedpkg srpm
warning: Macro %glibc needs whitespace before body
warning: Macro %glibc needs whitespace before body
Wrote: /mnt/ssd/carlos/fedsrc/glibc-rawhide/glibc-2.28-3.fc29.src.rpm

This was caused by the following line:
1243 # glibc-common:
1244 %define glibc-common_docdir %{glibc_build_sysroot}%{defaultdocdir}/glibc-common

Which used a '-' in a name instead of an underscore, but the error had no line number.

The cause of this is that the expandMacros API contains no line or source file information for any of the macros which are going to be expanded. This appears to be an oversight. Since the API is external I don't know how much can be changed, but it would have been much more helpful to have a line number associated with the failure such that it could be printed to the user.

You basically have to plumb line numbers through:
expandMacros -> doExpandMacros -> expandMacro -> doDefine.

Your best option to avoid ABI issues would be to define rpmExpandMacros2 which takes a rpmSpec structure so you can access the current line number.

Not having the line number available makes debugging harder than it should be.

**Comment by n3npq** [comment]
The recommended debugging is to add %trace (it's a toggle) around the problematic area and visually identify the flaw by examining the expansion.

There is also %dump that will display all currently defined macros.

But I agree that both a line no and containing file are sorely needed: users are attempting hugely complex macro expansions beyond what was anticipated when implemented.

**Comment by codonell** [comment]
@n3npq Thanks for the pointers about %trace and %dump. In the end they would not be needed if there was source and line information ;-)

**Comment by n3npq** [comment]
We agree that file/line info would help find where to fix. But then you often need to convince some other entity like the Fedora packaging committee to apply the fix, and then argue the need to backport everywhere, and finally try to convince other distro's to adopt the changes. That process takes years, and file/line no helps little.

Meanwhile, use shell or lua if you need to program: rpm macros are a templating language with rather primitive programming constructs. At least rpm macros aren't as bad as, say, XSLT or Haskell ;-)

**Comment by codonell** [comment]
@n3npq What are the restrictions on changing external interfaces like this? Are the structures and APIs frozen forever and backwards compatible?

**Comment by n3npq** [comment]
Most macros are instantiated in configuration files where associating file/line no information isn't visible.

Macros are stored in a context structure that is opaque, so extending with file/line no info is easy.

Your case of %define in a spec file, with the expectation of the spec file line no in an error message, is harder because macro expansion happens on a stream before line-by-line parsing occurs.

There are further difficulties with nesting: rpm supports a seldom used %include to interpose text outside of macros, as well as %{load:...} to read a new macro config file. It's also possible (but pathological) to interpolate text into a spec file using a %(cat /some/file) diversion. So there are potentially multiple files and line nos that might have to be displayed.

Similarly difficult is that these constructs may be embedded within recursive macro expansions, including additional %define statements that act as local definition overrides, where it's not just the file/line no that is informative, an entire expansion stack might be needed to identify wtf is going on.

That's  all doable: pushing/popping each %trace message onto a stack that can be dumped if there is an error.

But the harder problem can be determining what is an error, and triggering an unwind, as there are classes of macro expansion errors that are detectable only when the successful expansion leads to say a shell syntax failure.

Note that macro expansion could use an exception handler when, say, popen(3) failed or spewed on stderr. That too is doable, but setjmp(3)/longjmp(3) in C are tricky to get right.

**Comment by n3npq** [comment]
I should be more careful: the macro context and item structures are not opaque, but could be made opaque: no one I know of (other than me) has ever attempted any coding with those structures.

**Comment by codonell** [comment]
@n3npq Just as an example I added line numbers to the warnings in https://github.com/rpm-software-management/rpm/pull/494 so you can see what I'm thinking about and how to extend the existing interface to a new one with minimal change. Then have the spec file parser use the new interface. The line number is always the one the maps back to the spec file, and the user then has at least an idea of what line has the problem. I agree that things can quickly get complicated, but at a minimum this helps me and should help others with warnings. Really I think rpmMacroEntry is probably the right place for this information, but they get created in the backend, and we still need to get location information down from the parser to the entries. That can come later.

**Comment by n3npq** [comment]
@codonell: what you miss is that macros were implemented to unify CLI options and configuration within rpm to get rid of clunky rpmrc based key:value configuration, and to provide fully recursive expansion, not just symtab like lookup which was already in place in rpm 2.X.Y.

There was never any conscious intent to provide a macro templating interface to packagers other than as a mostly read only convenient interface to retrieve strings without having to design some gawd awful key:value retrieval interface like what is/was in M$ Windows and NEXT (now MacOS).

The usage case has sprawled far beyond what was intended, and there is need to overhaul the entire macro subsystem IMHO including
* name spacing for macro names
* more sophisticated use of macro contexts (rpm only uses 2 contexts: global and CLI, much better could and should be done)
* read only macros that cannot be changed to provide error messages if change is attempted
* refactoring all the per-interpreter gunk (macros and helpers) out of rpm itself
* making macro loading sensitive to rpm modes (I.e. build/install/query/verify etc)
* capturing the macros actually used during a build so that old dead wood can be eliminated
* permit macros into rpm headers: think of the pain involved with /lib and /usr/lib unification 

There are RFE's already for some of the items I just mentioned here.

**Comment by n3npq** [comment]
See issue #495, of which file/line no diagnostic information is just part of what needs to be done.

**Comment by pmatilai** [comment]
There was a previous attempt at something like this back in 2013:
http://lists.rpm.org/pipermail/rpm-maint/2013-January/003350.html. The thread continues in February, including some initial comments from me at http://lists.rpm.org/pipermail/rpm-maint/2013-February/003415.html. However Alexey didn't pursue it further and nobody picked up the pieces so...

**Comment by codonell** [comment]
@pmatilai Thanks for the reference Panu. I'm deeply involved in glibc, so I won't have time to get back to this, but I thought I'd take a stab at a problem I saw as inherently structural that could be resolved in an incremental fashion without an external API change. Overhauling the entire macro subsystem has to be undertaken by a more senior community member, or someone dedicated to fixing this, which is probably why it hasn't been fixed yet. It might be good to come up with a plan for this such that we can work on it in stages. In addition to this problem I also see rpm's lack of per-symbol-ABI tracking something which would be useful for distributions (https://bugzilla.redhat.com/show_bug.cgi?id=1320954). I'm going to leave this issue open, but feel free to close it if you want and track the RFE elsewhere.
