### ISSUE TITLE
RFE: eliminate all remnants of rpm network access in man pages and code

### ISSUE THREAD

**Issue by n3npq** [rpm-software-management/rpm#521]
Again this RFE is a result of assessing how to send a patch to simplify lib/rpminstall.c

It is very clear that years of refactoring has managed to remove almost all ability for rpm to access the network (the one exception I can find is in lib/rpminstall.c)

Meanwhile the rpm.8 man page still documents --ftpport proxy overrides and there are utterly useless macros for hkp:// pubkey retrieval and defaults that cannot possibly have worked for years.

It's your trash now, not mine. I'd suggest biting the bullet and hauling out gobs and gobs of uselessness in rpm code that likely has not worked for almost a decade.

**Comment by pmatilai** [comment]
The ftp-proxy business was indeed outdated, we haven't supported an actual ftp proxy since 2007 or so, only ftp-access through http-proxy. Fixed in commit bc91962b6a528cadd64f340c1e248897d7919b29,  thanks for pointing that out. 

Other than that, I suggest you actually try the network access support.

**Comment by n3npq** [comment]
I don't need to try network access to know what flaws there are.

Ok we will deal with the issues case by case
