### ISSUE TITLE
Skip showing Group in output of `rpm -qi`

### ISSUE THREAD

**Issue by xsuchy** [rpm-software-management/rpm#534]
This follows up https://github.com/rpm-software-management/rpm/pull/532#issuecomment-415312692

I agree that Group should not be displayed at all. Fedora does not use it. I am really curious about the usage in other distributions as @Conan-Kudo  mentioned.

**Comment by Conan-Kudo** [comment]
SUSE Linux distributions follow this guideline for categorizing packages with the Group tag: https://en.opensuse.org/openSUSE:Package_group_guidelines

Mageia follows this policy: https://wiki.mageia.org/en/RPM_groups_policy

OpenMandriva follows a similar policy to Mageia.

ALT Linux, PLD Linux, PCLinuxOS, and several other distributions also use the Group tag in this manner.

The key reason why Red Hat/Fedora never bothered to extend the groups is because we've never had a tool in Fedora (prior to dnfdragora) that was capable of organizing packages by the Group tag that was using the default package manager.

With apt-rpm, of course, there was Synaptic, which did organize it that way. And smart's GUI did too. But none of the GUI interfaces for YUM ever did, so there was not as much reason to extend the classifications for packages to actually support the wider array of packages.

However, DNF does today through [dnfdragora](https://github.com/manatools/dnfdragora) on every distribution except Fedora, where it is built with `-DENABLE_COMPS=1` (which incidentally makes it much slower to map all the packages to groups due to the M:N relationship and the fact it's a subset mapping that has to be built up as the app starts). 

In SUSE distributions, both Zypper and YaST2 are capable of sorting through packages by the Group tag. In Mageia and OpenMandriva, RPMDrake (the legacy package manager) and dnfdragora (the new one) both sort by the Group tag. While DNF does not yet present the Group information at the CLI (it's something I am going to do at some point), urpmi (the legacy package manager) does.

I don't know where the decision to not sort packages came from, but that's pretty much the difference between Fedora and every other distribution.

**Comment by n3npq** [comment]
Re "... key reason ..." 

This is revisionist history without basis in fact by an outsider who was not present at RedHat

Adding Group by value in package content forces rebuilds to Get It Right!.

The better implementation associates Group values with packages, not within packages, so that the Group taxonomy can be changed, or so that multiple taxonomies organized by Group can be supported simultaneously.

Readding support for the Group tag in packages within rpm libraries for alternative depsolver usage 15+ years later without addressing better implementations is a monumental mistake.

**Comment by xsuchy** [comment]
Personally, I would much rather see support for Tags instead of Groups.

Nevertheless, If this will be approved:
   https://fedoraproject.org/wiki/Changes/Remove_Group_Tag
Then this tag does not have any value for Fedora and can be displayed conditionally as some other tags.

**Comment by jasontibbitts** [comment]
Various options:

* Fedora could simply patch this downstream; it's just one popt file.
* RPM could leave the Group field in the header empty instead of hardcoding "Unspecified".  Then the popt file could just conditionally include the line.  I've no idea what else would break, though.
* The popt language could grow syntax to allow the Group line to be shown only if the Group tag is not equal to unspecified.

Or Fedora could just live with it.  dnf won't show useless group tags and I expect that's the more often used interface for getting package information.

**Comment by Conan-Kudo** [comment]
> Or Fedora could just live with it. 

I like this option. :)

**Comment by n3npq** [comment]
@jasontibbitts: presumably you meant --queryformat, not POPT, which already can conditionally test for existence of tags in headers.

**Comment by pmatilai** [comment]
NAK for simply removing from the output, as most distros are still actively using Group. I never understood why Fedora is so compelled to get rid of it, I find routinely find the group info far more useful than what's slapped into summary/description for example, but that's just me...

Conditionally showing group only if it exists would be okay I guess. Pretty much all versions of rpm are supposed to handle a missing group tag where relevant in the code (index data) but I doubt anybody has tested it in the last 10+ years. Also RPMTAG_GROUP is specified as a required tag in LSB. For whatever that is worth.

**Comment by pmatilai** [comment]
For some background (and a trip down the memory lane), see commit 784fe494b772bcb54b23fdc6d017f301c606d0fd and c094de4d1017af3ffbe89fdbb1db5bb821467c73

Unfortunately I negletted to mention what besides LSB broke...

**Comment by n3npq** [comment]
@pmatlai: LSB tried to adopt package standards already deployed: GROUP was mandatory in RPM at the time.

The rpm-3.0.6 format that LSB chose as a standard has been irrelevant since 2002.

Removing GROUP from package content != eliminating GROUP usage entirely.

**Comment by pmatilai** [comment]
After sleeping over it a bit...
Fedora wanting to get rid of a single line from an output that next to no normal user will ever see is just not worth it to break expectations written even in standards, not to mention various tools that deal with packages.

So, Fedora can live with it the best they see fit, end of story.
