### ISSUE TITLE
RFE: don't prevealuate lua macros

### ISSUE THREAD

**Issue by nim-nim** [rpm-software-management/rpm#556]
A rather annoying "feature" of the current lua integration is that the lua code is evaluated before executing any rpm section

So if you provide a lua macro that does not blindly pass arguments somewhere else, but does some test or processing on them

```specfile
%luamacro somevalue
```

will work and do what you'd expect

But if a packager takes your macro, and writes
```specfile
for value in somevalue othervalue ; do
  %luamacro ${value}
done
```
the processing will fail, because the lua code will process `${value}` and not `somevalue` followed by `othervalue`

So I'd rather see the lua code evaluated at the `%{lua:` entry point, instead of pre-evaluating like tight now.

**Comment by n3npq** [comment]
@jasontibbitts: %luamacro would need to be implemented as a co-routine because of rpm's embedded  lua interpreter has a persistent global environment.

That is very different than shell code, where a sub-shell inherits but cannot change its parent's environment. With rpm+lua, all lua invocations run in the same globally persistent environment.

That is/was actually the intended feature so that variables in the lua context could be shared/passed between, say, %pre and %post scriptlets implemented using embedded lua.

**Comment by jasontibbitts** [comment]
I swear I received a notification email about a reply, but I came here to read it and see nothing.  How bizarre.

**Comment by pmatilai** [comment]
@jasontibbitts yes, it's been going on a lot recently, see https://github.com/rpm-software-management/rpm/issues/551#issuecomment-425060771 

@n3npq, repeatedly posting and then deleting your comments is disruptive and abusive behavior and continuing to do so even after being warned just earned you a 30 day block on the rpm-software-management GH organization and rpm-maint mailing-list.
