### ISSUE TITLE
RFE: make %{load: } work in %prep

### ISSUE THREAD

**Issue by nim-nim** [rpm-software-management/rpm#571]
Right now `%{load: }` is unconditionnaly evaluated before `%prep` starts, making it impossible to load a macro file present inside a source archive. That adds quite a lot of complexity when you want to version-control a macro file in an upstream macro project

`%{load: }` should be evaluated at the point it occurs in the spec file.

Otherwise packagers have to write hacks like
https://src.fedoraproject.org/rpms/fontpackages/blob/master/f/fontpackages.spec#_84

**Comment by pmatilai** [comment]
This is essentially the same misunderstanding as ticket #556: macros are essentially a *pre-processor* for the spec, they are never dynamically executed during the build.

If you need to do something dynamically in the build scriptlets, you need to do it with the shell.

**Comment by nim-nim** [comment]
Well this is clearly doable in some form since whoever wrote the linked bit of spec @rh did it.

The limitation seems to be that the result are shell variables not rpm variables but from a practical POW the result is the same: the spec can use values defined in macros it ships itself, and the macro file is in the source archive , not a separate source.

So can we get some form of cleaned up and generalized form of this bit of code in rpm please? Even if the only thing it does is generate the corresponding shell code during the preprocess phase?

**Comment by pmatilai** [comment]
> whoever wrote the linked bit of spec 

Err, what exactly are you referring to?

**Comment by jasontibbitts** [comment]
But that only shows that @pmatilai's point was correct:  If you need to do something dynamically in the build scriptlets, you need to do it with the shell.

That bit of the spec does things via the shell.  So, yes, it's clearly doable in some form: with the shell.

I don't understand how what you ask for could possibly be implemented.  RPM writes out a shell script and passes it off to the shell to be executed.  It has no idea when the shell will get to the point where your %{load:} macro gets called.  RPM has completed its parsing of the spec (and thus the expansion/execution of any macros, Lua or otherwise) before any of those scripts are run.

Now, what you could ask for is some way to get some lua code called just before the scripts generated from %prep, %build, %install, etc. are actually executed (and perhaps at various other points in the build process).  I can think of a number of ways this could be useful but it depends on a number of things and I don't really have much of a clue about how it could be implemented.

Since Lua functions are first class, rpm could just call functions from a table:
```
table.insert(rpmhooks.prep, function () do_stuff() end)
```
It would also work to have a set of "magic" macros and have RPM call back into the macro processor to expand those (rpmExpandMacro) at specific points during the build process:
```
%global ___prep_hook %{lua: do_stuff()}
```
But I've no idea if you can call rpmExpandMacros after parsing is complete or if there's even still an rpmMacroContext around to use.

And obviously in order to do anything useful the lua code would have to be able to modify RPM state, the environment of the scripts or the actual contents of those scripts and I've no idea if that's reasonably possible.  (I guess there are a number of things it could do if it just gets the script filename.)  And I do know that "hook" actually has a different meaning inside RPM that I haven't quite figured out yet; I just don't know what else you would call this.

**Comment by pmatilai** [comment]
@nim-nim , ah sorry I missed the link in initial description and somehow thought the "linked bit" meant something entirely different.

The issue here is not that %{load:..} does not work from %prep. It does, but at the time of *parse*, not build. And since the macros file in question is packed inside the source tarball, it's only available after unpacking - in other words, during build. If macros.fonts were a separate standalone %{SOURCE}, you could %{load:..} it from the spec.

**Comment by pmatilai** [comment]
Actually rpm does perform further expansions at the time of build too for the various section templates, BUT the script itself from the spec is not re-expanded. PR #480 sort of does this, except that it escapes all percent signs automatically which in turn prevents actual macros from being expanded, which makes it all a bit moot. With a bit of modification to disable the escaping, #480 actually allows you do place %%{load:...} at the beginning of %prep and evaluated during build. Even then it's fairly non-obvious and klunky because the macro will not be evaluated in the context of the shell script it appears in, so eg relative paths wont work. So it becomes
```
%%{load:%{_builddir}/%{buildsubdir}/rpm/macros.fonts}
```

...and I'm not at all conviced that all this makes it somehow better and less hacky than using the shell.

**Comment by nim-nim** [comment]
Thanks a lot Panu, it like it a lot better than the shell script option!

Unfortunately I've just seen another similar package wants to use the info in the shipped macros to `ExclusiveArch` itself so that rules out using a `%prep` method.

I may end up replacing all this by sed-ing things in macro files from spec definitions, like fedora-release does, which kind of sucks since the result is not too readable and puts the master definition in the spec file not the scm-managed macro project.

Though I guess it should be possible to write a macro that automates such kind of sed-ing. fedora-release could use it. As does fontpackages. As does go-macros. And there are probably others I have no knowledge of.

@pmatilai do you think a macro
 * that takes as first argument a rpm constant or function defined in the spec,
 * that takes as second argument a macro filename available somewhere in _builddir during %prep
 * and puts the spec definition of the rpm constant or function in the macro file
 * eventually replacing exisiting defs in this file
Is doable?

The main problem I see it things that take multiline definitions (esp if you need to replace an existing def). Is there a way to scope those easily in rpm ?

Alternatively, one could force the use of a @@foo@@ anchor in the target macro file, by changing "put spec def as-is in the target macro file" with "replace the anchor with the def of xxxx in zzz macro file"

What do you think ?

**Comment by nim-nim** [comment]
And of course then we'll hit
https://github.com/rpm-software-management/rpm/issues/551

because that will want to use the main workdir in `_builddir`, which should be `%{buildsubdir}` except the way it is set is not ideal, and it is not set before the end of `%prep'.

**Comment by ignatenkobrain** [comment]
> Unfortunately I've just seen another similar package wants to use the info in the shipped macros to ExclusiveArch itself so that rules out using a %prep method.

This won't work at all. The ExclusiveArch goes to SRPM headers so by the time %prep is executed, it is already too late.

**Comment by nim-nim** [comment]
> > Unfortunately I've just seen another similar package wants to use the info in the shipped macros to ExclusiveArch itself so that rules out using a %prep method.
> 
> This won't work at all. The ExclusiveArch goes to SRPM headers so by the time %prep is executed, it is already too late.

Yes, that was my conclusion too, that’s why I’m exploring fedora-release-like sedding macro file sedding from spec definitions
