### ISSUE TITLE
rpm --setcaps sets empty security.capability when there is no caps

### ISSUE THREAD

**Issue by maage** [rpm-software-management/rpm#585]
rpm-4.14.2.1-1.fc29.x86_64
libcap-2.25-12.fc29.x86_64

rpm --setcaps is essentially wrapper for setcap.

$ sudo strace -o '|grep xattr' -f setcap "" /usr/bin/ul
2542  setxattr("/usr/bin/ul", "security.capability", "\0\0\0\2\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0", 20, 0) = 0
$ sudo strace -o '|grep xattr' -f setcap -r /usr/bin/ul
2647  removexattr("/usr/bin/ul", "security.capability") = 0
$ sudo rpm --setcaps util-linux
$ sudo strace -o '|grep xattr' -f getcap /usr/bin/ul
3394  getxattr("/usr/bin/ul", "security.capability", "\0\0\0\2\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0", 20) = 20
/usr/bin/ul =
$ ls --color=auto /usr/bin/ul
/usr/bin/ul
$ grep -i cap /etc/DIR_COLORS
CAPABILITY 30;41	# file with capability
$ ls -l $(rpm -ql util-linux)
every file is using red background and that is the main issue here. I was very confused when I noticed some of the files being in wrong color but not visible effect.

**Comment by pavlinamv** [comment]
It is a very good point. 

Empty capabilities ('') and no capabilities are different. Because (from SETCAP(8) man page):
"setting an empty capability set is not the same as removing it. An empty set can be used to guarantee a file is not executed with privilege inspite of the fact that the prevailing ambient+inheritable sets would otherwise bestow capabilities on executed binaries"

If %|FILECAPS? is false for a given package then --setcaps should set no caps. This is a bug in the current --setcap implementation and it must be corrected.

If %|FILECAPS? is true for a given package then %{FILECAPS} contains textual representation of file capabilities. In such a case files with no capabilities and files with empty capabilities satisfies %{FILECAPS}=''. So from the value %{FILECAPS}='' it is not clear whether a file has no or empty capabilities. I checked several packages (iputils, gnome-keyring, httpd, mtr). After package installation the files with %{FILECAPS}='' usually have no capabilities. But because 
1) empty capabilities are more strict then no capabilities and 
2) %{FILECAPS} can be used as a querytag to print out capabilities of a file
I think the correct solution is: if  %{FILECAPS} = '' then capabilities should be set empty. In case of no capabilities %{FILECAPS} must contain a different value.  And with respect to this correct --setcups. 

There is another problem:
rpm -V does not differ between no capabilities and empty capabilities now. E.g. if a file /usr/bin/mc has empty or no capabilities rpm -V verifies both as correct. It should be corrected.

**Comment by pavlinamv** [comment]
The previous comment is not correct. 

If %|FILECAPS? is true and file has empty capabilities, then %{FILECAPS}='='. 
It is different from no capabilities. Thus the patch from Markus Linnala
https://github.com/rpm-software-management/rpm/pull/586
works correctly.

There is still a problem that rpm -V does not differ between no capabilities and empty capabilities.
