### ISSUE TITLE
rpm cannot run with ramdisk system

### ISSUE THREAD

**Issue by terrytian88** [rpm-software-management/rpm#587]
It will be termerited after "Preparing......" promption with ramdisk system.
and it stop at function rpmtsCheckDSIProblems().

![default](https://user-images.githubusercontent.com/24286298/47633506-21de0100-db89-11e8-80ec-402491699307.png)

**Comment by ffesti** [comment]
Well, it says that more disk space is needed. Without more details about your setup it is impossible to judge whether this is an problem with rpm or not. Can you please at least provide the out put of `df -h`.

**Comment by pmatilai** [comment]
Um, that df output is missing all normal mounts, including the root itself and details on the used filesystem. I don't know how such a system is supposed to work at all, but I'm not exactly surprised if rpm wont work in that environment - rpm relies on mount info to determine whether the installation is possible, and since there's no root then nothing at all can be installed.

You don't need to recompile to disable disk space checking for a wacko special case, just use --ignoresize
