### ISSUE TITLE
RPMBuild 4.11| error: create archive failed on file /var/lib/jenkins/rpmbuild/SOURCES/xyz.tar.gz: cpio: write  

### ISSUE THREAD

**Issue by shubhamgupta514** [rpm-software-management/rpm#601]
Hi Team,

I am getting below error while building rpm package from my custom tar file 

error: create archive failed on file /var/lib/jenkins/rpmbuild/SOURCES/xyz.tar.gz: cpio: write

I checked there is no space issue on my system and I am using Centos 7.4
Please look into it.

Thanks,
Shubham Gupta

**Comment by pmatilai** [comment]
What you're seeing is likely a permission issue due to the exotic path. I cannot begin to guess what you're trying to achieve there, but I'd suggest learning the packaging basics first with the aid of some walkthrough-tutorial, several exist on the net. This is a bug tracker, not a packaging support forum.

**Comment by vagabond1132** [comment]
I also encountered the same problem, how do you solve it? @shubhamgupta514

**Comment by hugo3452** [comment]
I don't know if you find out a solution but i found this : 
https://github.com/jordansissel/fpm/issues/335
It's a problem on the tmppath you don't have enought space on your /tmp folder to create the rpm

**Comment by vagabond1132** [comment]
Yes, I found this problem. Because of the virtual machine I used, there was
a problem with the allocated hard disk. Df found that there was
insufficient disk space.

thank you for your reply


李刚
QQ:      865853453



hugo3452 <notifications@github.com> 于2019年12月13日周五 下午9:12写道：
