### ISSUE TITLE
Tags as an alternative to Groups

### ISSUE THREAD

**Issue by jengelh** [rpm-software-management/rpm#632]
As part of the discussion about Group removal in distributions and/or rpm itself (https://github.com/rpm-software-management/rpm/issues/534 ), some passive brainstorming on the openSUSE was conducted (https://lists.opensuse.org/opensuse-factory/2018-05/msg00460.html ). The main points are:

* The `Group:` field's use is for an _explorable catalog of software_. That is to say, if the user is not looking for any particular software by name _just yet_. Imagine rummaging through the "games" section in search for something... “new”. Solitaire only is fun for a finite time.
* The `Group:` field in a `.spec` file only permits a single value. Packagers often have trouble deciding on a group.
* Likewise, that package would only be visible in one group, which led to end-users not seeing the package as they might be rummaging through a topically-similar, but still different, category.

```
atomiks.spec:Group:          Amusements/Games/Logic
atomix.spec:Group:          Amusements/Games/Board/Other
```

I therefore want to bring forward an idea of making rpm offer a new `Tags:` field, similar in style of how http://freshcode.club/ rolls it. People have also drawn parallels to the `Category` field of XDG `.desktop` files. That way, a packager could classify emacs as the jack-of-all-trades that it is, e.g.

```
 Name:           emacs
 Version:        26.1
 Release:        0
 Summary:        GNU Emacs Base Package
 License:        GPL-3.0-or-later
-Group:          Productivity/Text/Editors
+Tags:           editors mail-client operating-system
```

and put atomiks/atomix in both "logic" and "board", etc.
What do you think? Could you make such a new field available in rpm to us?

**Comment by Conan-Kudo** [comment]
This is not exactly the first time this has come up. I recall that @proyvind made a similar suggestion a few years ago in #107, though admittedly it was more confusing then...

Speaking as someone who has implemented a frontend for sorting, the M:N relationship that composition groups (or on the openSUSE side, the patterns) offer makes it very expensive for sorting, because you can't cheaply put a package entry into a single bucket.

Package management UIs would then have to not present by singular categorization, but implement indexing search based on these tags. That's pretty expensive. Mapping the tags to categories in the UI is not easy for the same reasons that comps groups and patterns as a source of categorization are not.

**Comment by jengelh** [comment]
Excuse me if I do not see the complexity here. I am seeing the tag list as a (for rpm) non-interpreted single-value just like what `Group` is, where spaces are interpreted by downstream tools. Like so:

```
rpm -qa --qf="%{NAME}: %{GROUP}\n" >cache.txt
grep -Pi '^.*?:.*\b(shoot|arcade)\b' cache.txt
```

For a DB size of 1343 packages, the rpm command takes like 0.74s on my i7-8250U system, and the grep an additional 0.013s. Upscaling that for 60000 packages (last TW size I remember) would bring grep to 0.5s. Considering this example uses PCRE _and_ effectively does a full table scan here, that looks quite competetive for not even using a proper hash/btree index.

**Comment by pmatilai** [comment]
Like noted, this has been discussed before, and multiple trivial implementations exist (I've done a version with "keywords" tag in the past, didn't commit because...). 

I don't think anybody actually objects to the idea as such, it's just that nobody has stepped up to work out the finer details like a format that is actually enforced, otherwise you'll only end up with useless typoed junk like it was with Group. And the use-case is

The term "tag" is already overloaded in rpm to mean a piece of header data and also spec entries such as Group, as per this request we'd be adding a new *tag* called "Tags", not good. It'd have to be something else, "categories" is as fine as anything.

**Comment by jengelh** [comment]
>nobody has stepped up to work out the finer details like a format that is actually enforced

That runs risk of designing something that may turn out bad in 2 years, and then we're stuck with it and go define _another_ field. The freedom of the Group field does not appear to have been a bad choice. Imagine if ewt back in the day had declared that RPM would only ever accept the 34-or-so groups of the time.

(Did a small-ish UI program to check how long parsing today's rpmdb that way would take. https://github.com/jengelh/rpm-catalog )

>end up with useless typoed junk like it was with Group.

I am not sure what you mean by "typoed junk". Typos (misspellings) happen, even so on tag-heavy systems like Stackoverflow/Freshcode. An approach would be to regularly build an overview and looking for common substrings so as to find and join/normalize e.g. "GPL-3.0" vs "GPLv3".

**Comment by pmatilai** [comment]
> Imagine if ewt back in the day had declared that RPM would only ever accept the 34-or-so groups of the time.

I'm not talking about *hardcoding* a set of groups, but rather an externally maintained set of allowed values.

> I am not sure what you mean by "typoed junk". 

Having seen a few GUI package management tools try use the Group field for presenting software to users in an organized manner, every single typo stands out like the veritable sore thumb.

**Comment by jengelh** [comment]
>every single typo stands out

Which I would consider a good thing, because then I can fix the spello.

**Comment by ffesti** [comment]
I think it is just too late to add such a feature. There are so many packages that it is unrealistic for such a feature would gain enough traction. Also keywords are so 20th century. Today people just use full text search. Just write good summary and description fields.
