### ISSUE TITLE
RFE: Disable subpackage check at SRPM build time

### ISSUE THREAD

**Issue by eclipseo** [rpm-software-management/rpm#674]
Following my issue #672:

In Golang packaging (Fedora), the `-devel` subpackages are computed by a Lua macro called `gopkg`. They are handled by the `go-rpm-macros` package. This package is a BR for all Go packages, so available when we build the RPM. However, since it is not in the default BuildRoot  (and won't ever be as it pull Golang as a dep), it is not available at SRPM build time.

As such, `gopkg` is not expanded as SRPM build time. This cause issue with package containing scriplets:

```
error: line 41: %pretrans devel -p <lua>
: package golang-github-hashicorp-cleanhttp-devel does not exist
```

The check in place notices that the `-devel` subpackage does not exist.

We would like you to disable this type of check when we're building a SRPM so we don't encounter such failures. The SRPM build part of rpmbuild should not worry about subpackages, only the RPM build part should.

**Comment by ignatenkobrain** [comment]
Meh, I think everything needs to be correctly set during build of SRPM too.

**Comment by eclipseo** [comment]
> Meh, I think everything needs to be correctly set during build of SRPM too.

What is your solution to our current conundrum then? go-rpm-macros can't be in the default buildroot and rpm fails without it.

**Comment by ignatenkobrain** [comment]
`%gopkg` should not expand to `%pre` if no package is generated by that macro.

**Comment by eclipseo** [comment]
> `%gopkg` should not expand to `%pre` if no package is generated by that macro.

I do not understand what you mean. `%gopkg` does not expand at SRPM build time, that's the crux of the issue.

**Comment by nim-nim** [comment]
@ignatenkobrain,

@eclipseo is trying to add a manual `%pre` to a spec to fix past packaging mistakes, applying one of the fedora fixup guidelines. It fails because the pre applies to a part of the spec that is not generated before `rpmbuild -bb` (not `rpmbuild -bs`) stage.

The `rpmbuild -bs` stage should not execute any assertion that applies to (sub)packages and `rpmbuild -bb`, because anything it needs has to be in the default build root, while `rpmbuild -bb` requirements can be kept build-specific via normal `BuildRequires`.

**Comment by Conan-Kudo** [comment]
@nim-nim, @eclipseo: It would be deeply flawed if `rpmbuild(8)` allowed an invalid spec file to be used for a package build. The `rpmbuild` tool serves as the validator of the spec file and attempts to fail early if it looks like a broken package spec after evaluating the macros.

**Comment by nim-nim** [comment]
> @nim-nim, @eclipseo: It would be deeply flawed if `rpmbuild(8)` allowed an invalid spec file to be used for a package build

@Conan-Kudo The spec is perfectly fine and valid, and the assertion will pass. At the *right* time, when the parts the assertion checks against are available, not at `rpmbuild -bs` time because `rpmbuild -bs` needs to be kept minimal to avoid bloating default build roots.

Arguably, the `keep default build roots small` is a modern concern, due to the explosion of possible languages and tools. Nevertheless it’s a real concern.

**Comment by Conan-Kudo** [comment]
@nim-nim Subpackages *must* be evaluated because you can put BRs with subpackages, and those are still collected and put into the main SRPM, among other things.

**Comment by nim-nim** [comment]
@Conan-Kudo `BuildRequires` are not attached to the subpackage, they’re attached to the srpm, they are not part of “subpackage evaluation”. What trips eclipseo is not srpm-misplaced-inside-subpackages is plain subpackages-which-are-irrelevant-for-srpm-creation.

**Comment by pmatilai** [comment]
> It would be deeply flawed if rpmbuild(8) allowed an invalid spec file to be used for a package build. 

Indeed, and that's really all there is to it. We cannot allow rpm to generate source / binary packages with an unparseable/inconsistent spec. Find another way to do whatever it is you're doing.
