### ISSUE TITLE
%buildarch does not reflect architecture of current %package declaration

### ISSUE THREAD

**Issue by jasontibbitts** [rpm-software-management/rpm#689]
I'm trying to better understand how %buildarch works in the case of multiple %package declarations.  For more context, see https://bugzilla.redhat.com/show_bug.cgi?id=1705656

Basically, it appears that as soon as BuildArch: noarch is seen anywhere, the value of %buildarch changes to "noarch" and is never reset.  This means that a macro expanded within a %package declaration can't reliably tell if the package currently being defined is arch-specific or not.

Looking at the source, I can see the `case RPMTAG_BUILDARCHS` stanza in build/parsePreamble.c but I don't understand how the %buildarch macro gets set.  My uneducated guess is that it simply doesn't get reset when a new %package declaration is seen.  But I could also simply be completely failing to understand how macro expansion interacts with %package declarations.

**Comment by jasontibbitts** [comment]
Looking further, it appears to me that %buildarch isn't even defined until RPM sees `BuildArch: noarch` somewhere in the spec.  At that point it gets defined to noarch and stays there.  I don't know what utility that particular behavior has.

**Comment by pmatilai** [comment]
That such a macro gets defined at all is merely rpm going "oh lookit, there's a tag I know, lets define a corresponding macro for it". This is how %{name}, %{version} and all the other crud gets defined too. 
I don't see how you could legitimately *use* the %buildarch macro for anything at all so it probably shouldn't get defined either.

**Comment by jasontibbitts** [comment]
Well we did have what we thought was a legitimate reason for knowing within a macro the architecture of the package currently being defined (expanding to some useful Provides: lines, which may or may not include architecture information.  There may of course be another way to do something similar by reworking the automatic dependency generator but the macro, had it worked as intended, would have been simpler.

**Comment by pmatilai** [comment]
There may be legit use-cases for knowing that arch, but the point is the macro created from the spec tag is not it. Hence it's better not define it at all. Ditto for several other tags for which macros are no longer created as of commit c62d91a56fa75fcabc3ab4b0d2f7822ddffbbeb5

**Comment by pmatilai** [comment]
Reopening for further discussion / reconsideration:

It turns out that Fedora is widely depending on %{buildarch} macro being set to detect noarch sub-packages for at least Python packages. Relying on %{buildarch} is essentially broken as noted above, but it does work for noarch sub-packages. Kinda.

I figured maybe it's time to finally make it possible to query the actual headers from Lua to get accurate info on all cases. Adding that is not hard, but it runs into another gotcha - many things, including the package architecture, is not set in the header until *after* the package preamble has been parsed. And if we open up the header to (read-only) access from the spec, we expose the these sort of internals in a way that might make future changes even harder.

**Comment by pmatilai** [comment]
Further discussion reveals that the %buildarch use-case was considered unnecessary and removed from Fedora, so there's no immediate need to do anything more about this, but leaving open for now.

**Comment by pmatilai** [comment]
Since there hasn't been any new developments or issues surrounding this, closing.
Opening up the buildtime headers under construction to spec inspection is a Pandora's box I have no wish to open at this time.
