### ISSUE TITLE
Treat tilde versions as higher for purpose of dependency comparison

### ISSUE THREAD

**Issue by ignatenkobrain** [rpm-software-management/rpm#715]
In Rust packaging we've found issue that we have `Requires: (foo >= 1.0.0 with foo < 2.0.0)` and package with version `2.0.0~alpha` is actually is matching this range. I think it should be treated for dependency check purpose.

/cc @ffesti

**Comment by pmatilai** [comment]
Err, no. If its sorts lower than 2.0.0 then it must match the < 2.0.0 dependency, anything else would be a mess that nobody will understand.

How exactly is this a problem for you?

**Comment by pmatilai** [comment]
To rephrase a bit, I can see why you'd sometimes want 2.0.0~alpha to be considered 2.0.0, but also that in other cases not, and rpm cannot magically know which one you want for a particular case. It'd be nice if there was a way to explicitly express both cases.

This sort of reminds me of this (otherwise unrelated) case: http://lists.rpm.org/pipermail/rpm-maint/2010-November/002948.html

**Comment by ffesti** [comment]
I guess there is no real way around using `Requires: (foo >= 1.0.0 with foo < 2.0.0~)`. Yes, this is kinda annoying.

**Comment by ignatenkobrain** [comment]
@pmatilai yeah, this is somewhat similar. Unfortunately I don't know how we could nicely express both.

@ffesti yeah, the only problem is that semver.org says you can have versions like `2.0.0----beta` which would be translated into `2.0.0~~~~beta` in RPM. Not saying it is horrible or people should be doing this, but this case is valid. Also this tilde at the end looks not really nice :/ Especially if people would have to read this in their error messages.

**Comment by pmatilai** [comment]
So what's the actual use-case here? Converting upstream dependency tracking data to rpm?

**Comment by ignatenkobrain** [comment]
For this specific one is to be used in `%autosetup` and some more places in spec. Because default %name-%version doesn't work for pre-release packages.

**Comment by ignatenkobrain** [comment]
whoops, wrong ticlket. For this one is yes -- converting upstream dependency data into the RPM one... which works fine except for this small thingy.

**Comment by jasontibbitts** [comment]
Since what you really want is a significantly different total ordering, you really need a different set of binary relations.  I certainly don't want to be the one to propose `<~`, `<=~, `>~`, and `>=~`.  Plus, for completeness, I guess you'd need a comparison operator `=~`.  That would all be... horrible.
Personally I'd take the 99% solution and use the `with foo < 2.0.0~` syntax; if the set of cases where we care ever overlaps the set of cases where someone uses the multiple tilde thing then someone will just have to handle the case by hand.

**Comment by ffesti** [comment]
As pointed out by @jasontibbitts we really don't want to go down this rabbit whole. I am closing this - even if this is not great. Sorry!
