### ISSUE TITLE
Hidden doc copy failures in rpm-4.11.x

### ISSUE THREAD

**Issue by tcely** [rpm-software-management/rpm#808]
https://github.com/rpm-software-management/rpm/blob/7b5db7d98e024ebc582242712e56e603616144c0/build/files.c#L1733-L1758

https://github.com/rpm-software-management/rpm/blob/7b5db7d98e024ebc582242712e56e603616144c0/build/files.c#L1742-L1750

By collecting the files and generating a series of `cp` commands, this means the return code check is controlled by the last `cp` line in that script.

Using something like `set -e` would allow checking for any copy failures, but may mean some copies are not attempted. A better approach is setting a failure flag for all failures and only returning success from the script if that flag was never set.

**Comment by pmatilai** [comment]
Thanks for the report, but rpm 4.11 is long since unmaintained upstream -> wontfix.

In current upstream version, those copying errors are intentionally ignored because rpm now checks for the file presence separately (see commit 1ba05a7456aafb52e89df5dd42d494d09f9ea6a4), but 4.11.x cannot do so because it only knows about the directory containing all those files.
