### ISSUE TITLE
confusing message about too few disk space

### ISSUE THREAD

**Issue by mlschroe** [rpm-software-management/rpm#879]
This pops up from time to time as a bug report. The message rpm prints for too low disk space/too few inodes is a bit confusing:
```
foo.noarch needs 377MB on the /usr/src filesystem
```
But the disk has more than 377 MB free space.

What's meant is that it needs 377 MB *more* disk space. Could you please change the
messages to:

```
installing package %s needs %" PRIu64 "%cB more space on the %s filesystem
installing package %s needs %" PRIu64 " more inodes on the %s filesystem
```
I.e. add `more space` and `more`.

**Comment by pmatilai** [comment]
It's indeed one of those annual bug reports.

We can change, but that'll affect some programs that are looking for this exact message in its current form. OTOH the ones I know (yum, and thus probably dnf too) only do so in order to "translate" the message into something nicer so maybe that doesn't matter...

**Comment by mlschroe** [comment]
Thanks!
