### ISSUE TITLE
Rpm chroot operations use user/group info from the host

### ISSUE THREAD

**Issue by larskarlitski** [rpm-software-management/rpm#882]
When running `rpm --verify` with `--root`, rpm uses `passwd` from the host to verify that user and group ownerships match. This gives wrong results, because the host's uid and gid mappings might be different from the target's.

Verifiable with `strace rpm --root $PWD/foo --verify strace`. `/etc/passwd` from the host is read before `chroot` is called.

**Comment by pmatilai** [comment]
Yup, there's not much choice about it, rpm needs to initialise the dlopen()'ed name services before chrooting because who knows what version of those libraries might be (or not) in the chroot and there's no way to tell glibc to flush it's caches when going across chroot.

The summary is overly broad though, --verify does respect root, it's just user/group information which does not.

**Comment by larskarlitski** [comment]
This means that effectively, `--root` cannot be used with `--verify`. And maybe all other operations that depend on the uid mapping, like `--query`, `--install`, `--upgrade`?

I'd say that using the host's uid mapping is always wrong, but I agree that rpm cannot run code from inside the target via nss modules. Could a solution be to ignore those and only look at the target's `/etc/passwd`? I imagine that this will be fine for the vast majority of cases, because rpm packages in practice contain files belonging to system users that are specified in `/etc/passwd`, no?

**Comment by mlschroe** [comment]
(FYI: SUSE has a patch that makes rpm look in the chroot's /etc/passwd and /etc/group file as there is no way to flush glibc's caches.)

**Comment by pmatilai** [comment]
Yup. Perhaps the bigger question is, should rpm *always* use just the local passwd/group files?
I've a feeling the answer is a strong maybe...

**Comment by coling** [comment]
I'm seeing these same issues generating images with mkosi which in turn uses dnf/rpm.

To address this I added the following to my mkosi.postinst script:
```
rpm -qa | xargs rpm --setugids >/dev/null 2>&1
```
It takes quite some time to run (1 minute on a semi-decent SSD laptop with a small number of packages installed), so if anyone has any better fixup scripts/utilities then I'm all ears!

**Comment by DaanDeMeyer** [comment]
@pmatilai Is it an option to use `fgetpwent()` and `fgetgrent()` to circumvent glibc's caching? I'm not sure if rpm needs to take into account nsswitch. If it doesn't, using those two functions could be an option.

**Comment by keszybz** [comment]
> Yup. Perhaps the bigger question is, should rpm _always_ use just the local passwd/group files?

Yes, nothing else is useful.

> I'm not sure if rpm needs to take into account nsswitch.

I don't think so. Firstly, it's not well defined what that would even mean. The host's nsswitch is irrelevant, and the targets's nsswitch cannot be used because `rpm` doesn't run code from the target. Secondly, nsswitch config would generally include things like `nss_sss` and `nss_systemd`, which require the system to be up to deliver results. So those additional modules cannot give any useful answers to `rpm` anyway. Thirdly, `rpm` cares about system users. And system users need to be resolvable early, before the network and most of the system is up, so the users that rpm cares about would not be stored in those additional nss modules anyway. So in practice hardcoding `nss_files` as the method to resolve names is fine.

> Is it an option to use `fgetpwent()` and `fgetgrent()` to circumvent glibc's caching? 

Whatever works.
