### ISSUE TITLE
RFE: Ability to have a file in %files via a command (macro) evaluated at buildtime

### ISSUE THREAD

**Issue by hroncok** [rpm-software-management/rpm#894]
I'd like to have a macro, that sees the files after `%install` is finished and can do stuff with the files in `%buildroot` and `$PWD`, and I like to use the macro in the `%files` section.

Minimal (not so useful) example with a command:

This works:

```
%files
%(echo /foo)
```

This doesn't:

```
%build
echo /foo > ./special_file
...

%files
%(cat ./special_file)
```

I know that the above could be achieved  via `%files -f special_file`, but imagine the macro I want to put in there is not simply catting a file, but doing some logic.

Currently, the usual workflow is:

1. get the command/macro output a file
2. use that file in `-f`

```
%{our_files} > special_file

%files -f special_file
```

However I want to avoid this step and be able to use:

```
%files
%{our_files}
```

What's needed to make this happen?

**Comment by pmatilai** [comment]
The reason I didn't close this offhand was that I'm curious about the use-case, but apparently forgot to ask about it :) I mean, maybe there is something that we could do to help the case without making %files parsing more special than the rest of the spec.

Note that the -f files manifest is macro expanded as well, and that expansion happens just before actually processing the file list. So you can have a macro with (complex) logic expanded at that time, it just needs to be in a files manifest instead of the spec proper.

**Comment by hroncok** [comment]
The use-case was to have a `%{pyproject_metadata}` macro like this:

```
%files -n python3-foo
%{pyproject_metadata}
%{python3_sitelib}/foo/
```

The macro would:

 * find the built Python dist-info directory, parse the metadata from it, locate the License-File filed (not yet available)  and output something like:

```
%dir %{python_sitelib}/foo-41.4.0.dist-info/
%license %{python_sitelib}/foo-41.4.0.dist-info/INSTALLER
%{python_sitelib}/foo-41.4.0.dist-info/dependency_links.txt
%{python_sitelib}/foo-41.4.0.dist-info/entry_points.txt
%{python_sitelib}/foo-41.4.0.dist-info/LICENSE
%{python_sitelib}/foo-41.4.0.dist-info/METADATA
%{python_sitelib}/foo-41.4.0.dist-info/RECORD
%{python_sitelib}/foo-41.4.0.dist-info/top_level.txt
%{python_sitelib}/foo-41.4.0.dist-info/WHEEL
%{python_sitelib}/foo-41.4.0.dist-info/zip-safe
```

-----


Instead, we can have `%{pyproject_install}` to output a special file and use:

```
%files -n python3-foo -f %pyproject_metadata
%{python3_sitelib}/foo/
```
