### ISSUE TITLE
ocaml-find-requires.sh should also consider cmxs files

### ISSUE THREAD

**Issue by olafhering** [rpm-software-management/rpm#913]
I do not know much about OCaml *.cmxs files. According to `ocamlobjinfo /usr/lib64/ocaml/unix.cmxs` this file expects a certain hash of other functions provided by other OCaml libraries. I am sure if these functions change the `*.cmxs` library can not be used anymore, just like an ordinary ELF file with unsatisfied `NEEDED` dependencies.

For some reason commit 82e7dd702013d3679fda438333de30afdec17a4f considers only `*.cma`, `*.cmi` and `*.cmo` files. I think the wildcard should also cover `*.cmxs`. Perhaps dynload was not available at that that time?

**Comment by pmatilai** [comment]
@rwmjones , care to comment?

**Comment by rwmjones** [comment]
Yes I've noticed that some dependencies are no longer being generated correctly, and quite likely we should extend this to `*.cmxs`.  However I don't really have time to test a change right now as I'm preparing for 2 full weeks of conferences and meetings.

**Comment by rwmjones** [comment]
Olaf, are you going to make this change in SUSE first?

**Comment by olafhering** [comment]
Sure. Will replace the greppery with awkery.

**Comment by olafhering** [comment]
One the other hand: are these cmxs files are really supposed to be stand-alone? If they were in the -devel.rpm along with their cm* siblings, the issue would not exist.

**Comment by rwmjones** [comment]
I don't know how to answer the question of whether they're supposed to be standalone, but I can tell you what they are.

They are compiled OCaml native code shared libraries (the equivalent of C `*.so` files).  I believe they are in fact simply `*.so` files renamed and perhaps with some OCaml-specific ELF sections added.  Historically OCaml code could only be dynamically loaded (like `dlopen`) in bytecode form, and native code could only be statically linked together.  However a few years ago they added the ability to dynamically load native code into binaries.

The dynamically loadable bytecode libraries were called `*.cma` files.  In Fedora we put those into the non-devel package because reasons lost in time (see: https://fedoraproject.org/wiki/Packaging:OCaml#Main_package).  So probably in Fedora we'd put the `*.cmxs` files in the non-devel package too, or we'd move both to the -devel package.

The Fedora OCaml packaging guidelines really need a rethink when we have time.

**Comment by olafhering** [comment]
In which order is `/usr/lib/rpm/fileattrs/*.attr` evaluated? Is there a safe way to override the content of `%_rpmconfigdir/fileattrs/ocaml.attr` (part of rpm.rpm) with another file from my own `ocaml-rpm-macros.rpm` package?

**Comment by pmatilai** [comment]
The order of .attr reading is undefined territory. The need to do so just underlines the fact that this stuff shouldn't be in rpm but in language-specific packages.

**Comment by olafhering** [comment]
The evaluation order of `*.attr` files has nothing to do with how ocaml files are handled.
It would certainly be nice if non-rpm helpers could easily replace existing rpm helpers.
But this is way off-topic.
