### ISSUE TITLE
RFE: Offer MDBX as an alternative engine to LMDB for rpmdb

### ISSUE THREAD

**Issue by erthink** [rpm-software-management/rpm#958]
MDBX (i.e. [libmdbx](https://github.com/leo-yuriev/libmdbx)) is superior to LMDB with set of additional features ([the list](https://github.com/leo-yuriev/libmdbx#improvements-over-lmdb)). For rpmdb most useful are:
1. Support 2 times longer keys than LMDB (slightly less than 1/3 of the database page size), including `MAX_PATH` with corresponding page size.
2. Automatic on-the-fly database size control by preset parameters, both reduction and increment.
3. Automatic continuous zero-overhead database compactification.
4. mdbx_chk tool for database integrity check.
5. bundled test suite.

**Comment by pmatilai** [comment]
Seeing that this is a fork of LMDB, how's the key size limit? If it's the same as LMDB then this is not any better for us.

**Comment by leo-yuriev** [comment]
@pmatilai, briefly **MDBX support 2 times longer keys than LMDB**.

In details:
 - the key size limit depends from the database page size.
 - for default (4K) pages MDBX now accepts keys up 1980 bytes (ie slightly less than half the page size).
 - but this value will soon be revised down to be slightly less than 1/3 of the page size.
 - MDBX allows you to set the page size when creating a database, ranging from 512 to 65536 bytes.

 So, MDBX allow significant large key sizes, including MAX_PATH (ie 4096) with corresponding size of database page.

P.S. Seems this should be added to the "list of Improvements over LMDB".

**Comment by pmatilai** [comment]
Ack, useful to know.

That said, what we don't need right now is more experimental backends based on new engines. In time though, who knows.

**Comment by Conan-Kudo** [comment]
@leo-yuriev I think it would be worth considering replacing LMDB with MDBX, given those improvements. I also assume MDBX would be a more responsive upstream to our needs?

**Comment by Conan-Kudo** [comment]
@leo-yuriev Would you consider getting MDBX packaged up in Fedora? That'd help us to be able to consider it for rpm upstream and do CI with it...

**Comment by leo-yuriev** [comment]
> I also assume MDBX would be a more responsive upstream to our needs?
Yes.

**Comment by pmatilai** [comment]
And how about 15 years from now? That's the kind of longevity that rpm needs from the database engines.

It's good to see new potential alternatives emerge. But to set the expectations straight, rpm is not in the business of pioneering database engines, our main interest is in technologies that have been around and widely used for a while, which helps with future projection too. 

Getting software packaged in distros is a step in the right direction of course.

**Comment by leo-yuriev** [comment]
> And how about 15 years from now?

IMHO:
 - Whatever storage engine was chosen now, this choice will look suboptimal in 15-25 years.
 - The right strategy is to be able to choose easily, rather than trying to choose the best engine "now & forever".
 - A good tactic might be to add/replace an experimental engine every 2-3 years "just for fitness", with some refactoring.

> Getting software packaged in distros is a step in the right direction of course.

I think I should explain why libmdbx is not (yet) available as packages:
 - The main reason is that changes were planned that would have resulted in incompatibility (both API and DB file format).
 - It would be irresponsible and irrational to distribute a library for which such changes are planned.
 - At the end of the summer, it was decided to make the current version libmdbx production-ready and then release at the end of 2019, but all the planned rework to do in the new MithrilDB library (with a clean slate, and a with different license).

So, libmdbx is not intended to be best engine for rpmdb forever, but it overcomes LMDB in usability, robustness and speed. Ie libmdbx (imho) is good enough to replace LMDB.

**Comment by pmatilai** [comment]
The thing is, the rpmdb is unlike your average database. People expect to be able to access it both backwards and forwards in time across chroots, containers for builds, software inventory and whatnot. And when that ability is taken away (by introducing a new engine, or just an incompatible engine file-format change), lot of s*** breaks and we get the "compliments".

**Comment by leo-yuriev** [comment]
> The thing is, the rpmdb is unlike your average database. People expect to be able to access it both backwards and forwards in time across chroots, containers for builds, software inventory and whatnot. And when that ability is taken away (by introducing a new engine, or just an incompatible engine file-format change), lot of s*** breaks and we get the "compliments".

@pmatilai, I am agree on 142%.
 
But for me, this thesis means that rpmdb should be able to work transparently with different storage engines simultaneously. Otherwise, the mentioned enduring properties are obviously unattainable.

However, this is a topic for a separate discussion, and here I would just like to note that when choosing between LMDB and MDBX, the latter wins.

P.S.
It is appropriate to mention that the desire to form and freeze the DB file format and most of the API is the main reason why "MithrilDB" is not yet released.

This same problem "wanna the best, but stable and frozen" strongly inhibits the development of many systems/projects (for instance the C++ language), and there seems to be no other solution than to allow for gradual migration.

**Comment by pmatilai** [comment]
Recent rpm versions have no problem supporting multiple backends and converting between them on the fly, that's a fairly obvious pre-requisite for ever getting off BDB in the first place.

And yeah I noticed the mentions of "MithrilDB" development with API and format considerations and that's quite a clear sign for us to not hurry jumping in. Like said, in time perhaps, but that time doesn't seem to be yet.

**Comment by erthink** [comment]
Is anyone willing to make a bet with me that [MDBX](https://github.com/erthink/libmdbx) (reasonable, no-cheating) will save half the resources? (probably up to 5-10 times, but I'm not a bookmaker).
$99.99

**Comment by pmatilai** [comment]
That is not the kind of upstream we want. Thanks for making that part clear.

**Comment by vorot93** [comment]
I'm probably late to the party, but @pmatilai what was your problem with @erthink's offer?

We at Erigon have successfully switched away from LMDB to MDBX, which has helped solve numerous issues as [documented here](https://github.com/ledgerwatch/erigon/wiki/Criteria-for-transitioning-from-Alpha-to-Beta#switch-from-lmdb-to-mdbx).

Furthermore, we have found Leonid to be extremely considerate and responsive upstream, going to great lengths to fix issues if they arise.

**Comment by Conan-Kudo** [comment]
@vorot93 It was definitely in poor taste, and given our experience with the LMDB upstream, we're pretty wary of having an upstream who wouldn't be responsive to the larger community of RPM users that would consume MDBX. We were burned once, and we don't want to be burned again. If someone wants to contribute an MDBX backend to RPM, then we can have a conversation about it once a pull request is submitted.

**Comment by vorot93** [comment]
I cannot speak for Leonid, but as you said, popular belief is that Red Hat foots the development bill, so an outsider could consider such a half-joke/half-offer acceptable. And pretty sure it was _not_ an attempt to troll anyone.

Anyway, you say you were "burned by upstream". Was it _LMDB's upstream_? Because if so, this is squarely one of the reasons why we switched to MDBX.

**Comment by Conan-Kudo** [comment]
> Anyway, you say you were "burned by upstream". Was it LMDB's upstream? Because if so, this is squarely one of the reasons why we switched to MDBX.

Yes. We were burned by attitude and broken promises from the LMDB developer.

**Comment by pmatilai** [comment]
As I said in an earlier comment, rpm is not in the business of pioneering new database engines in development. Come back in 10 years for a re-evaluation.

**Comment by Conan-Kudo** [comment]
Considering MDBX is forked from LMDB, I don't think that's exactly true in this case.

**Comment by pmatilai** [comment]
I don't know what that's supposed to mean. The point is, there's absolutely zero longevity record for MDBX at this point. As repeated multiple times now, maybe in time that may change. LMDB for its shortcomings was at least backed by a long-standing organization and widely used, so can be reasonably expected to be around in a few years. Whereas one man projects come and go - absolutely nothing wrong with that, it's the name of the game. It just doesn't match rpm's needs.

**Comment by DemiMarie** [comment]
I know we disagree a lot @pmatilai, but in this case I believe your decision was absolutely correct.  SQLite is *far* better tested, has more features, and will be supported through at least 2050.

**Comment by Conan-Kudo** [comment]
In this case, I actually _disagree_ with @pmatilai because I think RPM moves too slowly as it is, and we can easily accept another backend and have it in experimental status, like we did for NDB (which is now stable after some real-world testing).

**Comment by mikhailnov** [comment]
Do you really want to force RPM developers and contributors to be experts in DBs?

**Comment by Conan-Kudo** [comment]
People using NDB already are forced into that situation. That's not true for any backend that exists as a general database type (SQLite, LMDB/MDBX, etc.).

**Comment by mikhailnov** [comment]
What do you mean under "exists as a general database type"? Adding new features to RPM will require adding support for multiple DB backends.

**Comment by Conan-Kudo** [comment]
Being experts in databases is pretty much only required if you're implementing the database. Beyond that, we'd be relying on APIs and guidance from the database project.

**Comment by vorot93** [comment]
@mikhailnov a cursory glance at RPM codebase reveals a [neat DB abstraction layer](https://github.com/rpm-software-management/rpm/blob/master/lib/backend/dbi.h#L235) which unifies specific DB implementations.

Besides, you can consider MDBX to be LMDB with many longstanding woes fixed, so pretty sure everybody here is familiar with it already.

**Comment by pmatilai** [comment]
Yes there's an abstraction layer and a price to be for that: the more backends there are, the more it hurts *all* development in that area because all backends need to be patched whenever something changes. We don't want new backends just because a DB engine exists, this is a case where less is more.
