### ISSUE TITLE
rpmconstant API should exist in librpm itself

### ISSUE THREAD

**Issue by Conan-Kudo** [rpm-software-management/rpm#992]
Mageia (and Mandriva before it) has had a librpm extension library called [rpmconstant](https://github.com/rpm-software-management/rpmconstant) for a long time now.

I am not sure why this functionality does not exist in librpm itself, but it probably should. While I am not proposing the existing rpmconstant code gets merged in (unless we can get it relicensed to LGPLv2+ like the rest of librpm, this is probably a no-go), I think it makes sense that the API it offers is available as part of librpm, effectively obsoleting the rpmconstant project.

**Comment by ignatenkobrain** [comment]
I think it would be useful to be able to define "random" RPMTAG_* somewhere from rpm macro so that we don't have to have things like RPMTAG_MODULARITYLABEL in RPM upstream, but rather define it in Fedora/RHEL. And have RPM API to be able to retrieve such values.

**Comment by Conan-Kudo** [comment]
The problem with "randomly" defined tags is that the lack of consistency means that RPMs can become incompatible with each other, simply by using the same spots in the rpm header for different purposes. I suppose if the tag names were discoverable from the header (e.g. with rpmconstant API), then this would be less of a problem, since we wouldn't rely on fixed addresses for tags in the enum...

**Comment by pmatilai** [comment]
Um. What exactly does this thing *do*?

**Comment by Conan-Kudo** [comment]
Per the packaging description from Mageia:

> rpmconstant provides basic functions to map internal RPM constant values
> with their name. This is useful for perl/python or other language which has
> binding over rpmlib.

Based on that description and what the code _looks_ like it does, it allows a relatively trivial automatic mapping of internal values to their names (such as for RPMTAGs and other header properties).

That said, the code for rpmconstant is not documented much, it's used as a component to support the perl-RPM4 binding module.

**Comment by pmatilai** [comment]
Yeah I can imagine it does *something* like that. But "internal RPM values" doesn't sound sane at all - internals are internals for a reason. Tags have a public API in librpm as it is, and lot of the other constants in headers you'd only want to export to languages selectively if at all. Exporting all random gunk you can find in headers to language bindings without actually understanding what they are and what they do only leads to trouble - seen it all too many times by now.

Rpm API can always be improved, but I'm *not* going to accept something that blindly exports every constant there might be in rpm source tree. Specific use-cases of this rpmconstant thing would be more helpful.

**Comment by Conan-Kudo** [comment]
Perhaps @soig could explain rpmconstant use-cases? He's the maintainer of rpmconstant and perl-RPM4...

**Comment by ffesti** [comment]
"internal RPM values" is just incorrect. These are all constants declared in public rpm headers. Looking at %file_const in https://github.com/rpm-software-management/rpmconstant/blob/master/rpmh2tbl gives a better idea of what is happening here.
So this is basically the same thing we already have for tags in rpm itself (https://github.com/rpm-software-management/rpm/blob/master/lib/gentagtbl.sh) but for all the other flags and attributes: Bridging the gap between C and interpreted languages by making C macro constants available as proper data/API instead of some weird C preprocessor thing.

We also export most of them already in the Python API as attributes of the module (see pydoc3 rpm and scroll down to the DATA section). So most of them are already out there - although in a not very convenient format.
`
pydoc3 rpm | grep " = " | cut -d " " -f 5 | cut -d _ -f1 | sort -u`
give a idea of what we are already exporting to Python (slightly edited):

> 

header_magic
HEADERCONV
RPMBUILD
RPMCALLBACK
RPMDBI
RPMDEP
RPMFILE
RPMLOG
RPMMIRE
RPMPROB
RPMRC
RPMSENSE
RPMSIG
RPMSPEC
RPMTAG
RPMTRANS
RPMVERIFY
RPMVSF
tagnames
TR

So the lists on both sides are not that different.

**Comment by ffesti** [comment]
As the librpm part of RPM is licensed under both GPL and LGPL the current license of rpmconstant (GPLv2) is not compatible with the rpm code base. To integrate the code into rpm the license would need to be changed to GPL + LGPL.

**Comment by Conan-Kudo** [comment]
Or LGPLv2+, which would be equally sufficient.

`rpmconstant` only has two authors: Thierry Vignaud and Olivier Thauvin. We can probably reach both authors and request relicensing `rpmconstant` to LGPLv2+, which makes it suitable for integration into RPM.

**Comment by pmatilai** [comment]
After a closer look, sorry guys but I don't believe this API belongs to rpm at all.

These things are better handled in language specific bindings, exposing only things that the particular bindings actually implement and in ways that are native to that language.
